if (!DiabloCalc.skilltips) DiabloCalc.skilltips = {};
if (!DiabloCalc.passivetips) DiabloCalc.passivetips = {};
DiabloCalc.skilltips.witchdoctor = {
  acidcloud: {
    a: "<p>Raise a corpse from the ground that explodes for <span class=\"d3-color-green\">700%</span> weapon damage as Fire to enemies in the area.</p> <p class=\"subtle\">Unlocked at level <em>55</em>.</p>",
    b: "<p>Increase the initial area of effect of Acid Cloud to <span class=\"d3-color-green\">24</span> yards.</p> <p class=\"subtle\">Unlocked at level <em>26</em>.</p>",
    c: "<p>The acid on the ground forms into a slime that irradiates nearby enemies for <span class=\"d3-color-green\">600%</span> weapon damage as Poison over <span class=\"d3-color-green\">5</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>30</em>.</p>",
    d: "<p>Create pools of frost to deal <span class=\"d3-color-green\">720%</span> weapon damage as Cold over <span class=\"d3-color-green\">6</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>39</em>.</p>",
    e: "<p>Spit a cloud of acid that deals <span class=\"d3-color-green\">333%</span> weapon damage as Poison, followed by <span class=\"d3-color-green\">400%</span> weapon damage as Poison over <span class=\"d3-color-green\">3</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>46</em>.</p>",
    elements: {
      a: "fir",
      b: "psn",
      c: "psn",
      d: "col",
      e: "psn",
      x: "psn",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/witchdoctor_acidcloud.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">175</span> Mana</p><p>Cause acid to rain down, dealing an initial <span class=\"d3-color-green\">300%</span> weapon damage as Poison, followed by <span class=\"d3-color-green\">360%</span> weapon damage as Poison over <span class=\"d3-color-green\">3</span> seconds to enemies who remain in the area.</p> <p class=\"special\">Decay</p> <p class=\"subtle\">Unlocked at level <em>22</em>.</p> </div> </div>",
  },
  bigbadvoodoo: {
    a: "<p>The Fetish increases the damage of all nearby allies by <span class=\"d3-color-green\">30%</span>.</p> <p class=\"subtle\">Unlocked at level <em>44</em>.</p>",
    b: "<p>Increase the duration of the ritual to <span class=\"d3-color-green\">30</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>31</em>.</p>",
    c: "<p>The ritual heals all nearby allies for <span class=\"d3-color-green\">5%</span> of their maximum Life per second and reduces all damage taken by <span class=\"d3-color-green\">20%</span>.</p> <p class=\"subtle\">Unlocked at level <em>50</em>.</p>",
    d: "<p>The ritual restores <span class=\"d3-color-green\">250</span> Mana per second while standing in the ritual area.</p> <p class=\"subtle\">Unlocked at level <em>37</em>.</p>",
    e: "<p>Enemies who die in the ritual area have a <span class=\"d3-color-green\">50%</span> chance to resurrect as a Zombie Dog.</p> <p class=\"subtle\">Unlocked at level <em>58</em>.</p>",
    elements: {
      a: "phy",
      b: "phy",
      c: "phy",
      d: "phy",
      e: "phy",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/witchdoctor_bigbadvoodoo.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">120</span> seconds</p><p>Conjure a Fetish that begins a ritual dance that increases the attack speed and movement speed of all nearby allies by <span class=\"d3-color-green\">20%</span> for <span class=\"d3-color-green\">20</span> seconds.</p> <p class=\"special\">Voodoo</p> <p class=\"subtle\">Unlocked at level <em>25</em>.</p> </div> </div>",
  },
  corpsespiders: {
    a: "<p>Throw a jar with fire spiders that return <span class=\"d3-color-green\">3</span> Mana to you per hit.</p> <p class=\"subtle\">Unlocked at level <em>55</em>.</p>",
    b: "<p>Throw a jar with a spider queen that births spiderlings, dealing <span class=\"d3-color-green\">2625%</span> weapon damage as Poison over <span class=\"d3-color-green\">15</span> seconds.</p><p>You may have one spider queen summoned at a time.</p> <p class=\"subtle\">Unlocked at level <em>18</em>.</p>",
    c: "<p>Throw a jar with jumping spiders that leap up to <span class=\"d3-color-green\">25</span> yards to reach their enemy and attack for a total of <span class=\"d3-color-green\">645%</span> weapon damage as Poison.</p> <p class=\"subtle\">Unlocked at level <em>9</em>.</p>",
    d: "<p>Throw a jar with widowmaker spiders deal a total of <span class=\"d3-color-green\">700%</span> weapon damage as Physical.</p> <p class=\"subtle\">Unlocked at level <em>33</em>.</p>",
    e: "<p>Throw a jar with paralyzing spiders that have a <span class=\"d3-color-green\">100%</span> chance to Slow enemies by <span class=\"d3-color-green\">60%</span> with every attack.</p> <p class=\"subtle\">Unlocked at level <em>45</em>.</p>",
    elements: {
      a: "fir",
      b: "psn",
      c: "psn",
      d: "phy",
      e: "col",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/witchdoctor_corpsespider.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">This is a Signature spell. Signature spells are free to cast.</span></p><p>Throw a jar with <span class=\"d3-color-green\">4</span> spiders that attack nearby enemies for a total of <span class=\"d3-color-green\">576%</span> weapon damage as Physical before dying.</p> <p class=\"special\">Primary</p> <p class=\"subtle\">Unlocked at level <em>3</em>.</p> </div> </div>",
  },
  fetisharmy: {
    a: "<p>Each Fetish deals <span class=\"d3-color-green\">680%</span> weapon damage as Cold to any nearby enemy as it is summoned.</p> <p class=\"subtle\">Unlocked at level <em>34</em>.</p>",
    b: "<p>Increase number of dagger-wielding Fetishes summoned by <span class=\"d3-color-green\">3</span>.</p> <p class=\"subtle\">Unlocked at level <em>46</em>.</p>",
    c: "<p>Summon an additional <span class=\"d3-color-green\">2</span> Fetish casters who breathe fire in a cone in front of them and deal <span class=\"d3-color-green\">85%</span> of your weapon damage as Fire.</p> <p class=\"subtle\">Unlocked at level <em>52</em>.</p>",
    d: "<p>Decrease the cooldown of Fetish Army to <span class=\"d3-color-green\">90</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>40</em>.</p>",
    e: "<p>Summon an additional <span class=\"d3-color-green\">2</span> Hunter Fetishes that shoot blowdarts at enemies, dealing <span class=\"d3-color-green\">130%</span> of your weapon damage as Poison.</p> <p class=\"subtle\">Unlocked at level <em>60</em>.</p>",
    elements: {
      a: "col",
      b: "phy",
      c: "fir",
      d: "phy",
      e: "psn",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/witchdoctor_fetisharmy.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">120</span> seconds</p><p>Summon an army of <span class=\"d3-color-green\">5</span> dagger-wielding Fetishes to fight by your side for <span class=\"d3-color-green\">20</span> seconds. The Fetishes attack for <span class=\"d3-color-green\">180%</span> of your weapon damage as Physical.</p> <p class=\"special\">Voodoo</p> <p class=\"subtle\">Unlocked at level <em>30</em>.</p> </div> </div>",
  },
  firebats: {
    a: "<p>Summon fewer but larger bats that travel a long distance and deal <span class=\"d3-color-green\">500%</span> weapon damage as Fire.</p> <p class=\"subtle\">Unlocked at level <em>11</em>.</p>",
    b: "<p>Rapidly summon two bats that each seek out a nearby enemy for <span class=\"d3-color-green\">750%</span> weapon damage as Fire.</p> <p class=\"subtle\">Unlocked at level <em>45</em>.</p>",
    c: "<p>Diseased bats fly towards the enemy and infect them. Damage is slow at first, but can increase over time to a maximum of <span class=\"d3-color-green\">720%</span> weapon damage as Poison.</p> <p class=\"subtle\">Unlocked at level <em>29</em>.</p>",
    d: "<p>Firebats has an initial Mana cost of <span class=\"d3-color-green\">250</span> mana but no longer has a channeling cost.</p><p>Firebats' damage type turns into Physical.</p> <p class=\"subtle\">Unlocked at level <em>19</em>.</p>",
    e: "<p>Call forth a swirl of bats that damage nearby enemies for <span class=\"d3-color-green\">425%</span> weapon damage as Fire. The damage of the bats increases every second, up to a maximum of <span class=\"d3-color-green\">850%</span> weapon damage after 3 seconds.</p> <p class=\"subtle\">Unlocked at level <em>56</em>.</p>",
    elements: {
      a: "fir",
      b: "fir",
      c: "psn",
      d: "phy",
      e: "fir",
      x: "fir",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/witchdoctor_firebats.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">125</span> Mana</p><p>Call forth a swarm of fiery bats to burn enemies in front of you for <span class=\"d3-color-green\">475%</span> weapon damage as Fire.</p> <p class=\"special\">Secondary</p> <p class=\"subtle\">Unlocked at level <em>5</em>.</p> </div> </div>",
  },
  firebomb: {
    a: "<p>In addition to the base explosion, the skull creates a larger blast that deals an additional <span class=\"d3-color-green\">30%</span> weapon damage as Cold to all other enemies within <span class=\"d3-color-green\">28</span> yards.</p> <p class=\"subtle\">Unlocked at level <em>60</em>.</p>",
    b: "<p>The skull can bounce up to <span class=\"d3-color-green\">2</span> times.</p> <p class=\"subtle\">Unlocked at level <em>31</em>.</p>",
    c: "<p>The explosion creates a pool of fire that deals <span class=\"d3-color-green\">60%</span> weapon damage as Fire over <span class=\"d3-color-green\">3</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>38</em>.</p>",
    d: "<p>Create a column of flame that spews fire at the closest enemy for <span class=\"d3-color-green\">880%</span> weapon damage as Fire over <span class=\"d3-color-green\">6</span> seconds.</p><p>You may have up to <span class=\"d3-color-green\">3</span> Pyrogeists active at a time.</p> <p class=\"subtle\">Unlocked at level <em>47</em>.</p>",
    e: "<p>Rather than exploding for area damage, each Firebomb can bounce to up to <span class=\"d3-color-green\">6</span> additional enemies. Damage is reduced by <span class=\"d3-color-green\">15%</span> per bounce.</p> <p class=\"subtle\">Unlocked at level <em>28</em>.</p>",
    elements: {
      a: "col",
      b: "fir",
      c: "fir",
      d: "fir",
      e: "fir",
      x: "fir",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/witchdoctor_firebomb.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">This is a Signature spell. Signature spells are free to cast.</span></p><p>Lob an explosive skull that deals <span class=\"d3-color-green\">155%</span> weapon damage as Fire to all enemies within <span class=\"d3-color-green\">8</span> yards.</p> <p class=\"special\">Primary</p> <p class=\"subtle\">Unlocked at level <em>21</em>.</p> </div> </div>",
  },
  gargantuan: {
    a: "<p>When the Gargantuan encounters an elite enemy or is near <span class=\"d3-color-green\">5</span> enemies, it enrages for <span class=\"d3-color-green\">15</span> seconds gaining:<br/> <span class=\"tooltip-icon-bullet\"></span> <span class=\"d3-color-green\">20%</span> movement speed<br/> <span class=\"tooltip-icon-bullet\"></span> <span class=\"d3-color-green\">35%</span> attack speed<br/> <span class=\"tooltip-icon-bullet\"></span> <span class=\"d3-color-green\">200%</span> Physical damage</p><p>This effect cannot occur more than once every <span class=\"d3-color-green\">45</span> seconds. Elite enemies include champions, rares, bosses, and other players.</p> <p class=\"subtle\">Unlocked at level <em>29</em>.</p>",
    b: "<p>The Gargantuan gains the Cleave ability, allowing its attacks to hit multiple enemies for <span class=\"d3-color-green\">585%</span> of your weapon damage as Cold.</p> <p class=\"subtle\">Unlocked at level <em>22</em>.</p>",
    c: "<p>The Gargantuan is surrounded by a poison cloud that deals <span class=\"d3-color-green\">135%</span> weapon damage as Poison per second to nearby enemies.</p> <p class=\"subtle\">Unlocked at level <em>48</em>.</p>",
    d: "<p>Summon a more powerful Gargantuan to fight for you for <span class=\"d3-color-green\">15</span> seconds. The Gargantuan's fists burn with fire, dealing <span class=\"d3-color-green\">575%</span> of your weapon damage as Fire and knocking enemies into the air.</p> <p class=\"subtle\">Unlocked at level <em>39</em>.</p>",
    e: "<p>The Gargantuan gains the ability to periodically slam enemies, dealing <span class=\"d3-color-green\">200%</span> of your weapon damage as Fire and stunning them for <span class=\"d3-color-green\">3</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>56</em>.</p>",
    elements: {
      a: "phy",
      b: "col",
      c: "psn",
      d: "fir",
      e: "fir",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/witchdoctor_gargantuan.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">60</span> seconds</p><p>Summon a Gargantuan zombie to fight for you. The Gargantuan attacks for <span class=\"d3-color-green\">450%</span> of your weapon damage as Physical.</p> <p class=\"special\">Voodoo</p> <p class=\"subtle\">Unlocked at level <em>19</em>.</p> </div> </div>",
  },
  graspofthedead: {
    a: "<p>Increase the damage done to <span class=\"d3-color-green\">1360%</span> weapon damage as Physical.</p> <p class=\"subtle\">Unlocked at level <em>15</em>.</p>",
    b: "<p>Corpses also fall from the sky, dealing <span class=\"d3-color-green\">420%</span> weapon damage as Physical over <span class=\"d3-color-green\">3</span> seconds to nearby enemies.</p> <p class=\"subtle\">Unlocked at level <em>53</em>.</p>",
    c: "<p>Removes the Mana cost and increases the amount enemies are Slowed to <span class=\"d3-color-green\">80%</span>.</p><p>Damage type is changed to Cold.</p> <p class=\"subtle\">Unlocked at level <em>7</em>.</p>",
    d: "<p>Reduce the cooldown of Grasp of the Dead to <span class=\"d3-color-green\">4</span> seconds.</p><p>Damage type is changed to Poison.</p> <p class=\"subtle\">Unlocked at level <em>28</em>.</p>",
    e: "<p>Enemies who die while in the area of Grasp of the Dead have a <span class=\"d3-color-green\">70%</span> chance to summon a Zombie Dog.</p><p>Damage type is changed to Poison.</p> <p class=\"subtle\">Unlocked at level <em>25</em>.</p>",
    elements: {
      a: "phy",
      b: "phy",
      c: "col",
      d: "psn",
      e: "psn",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/witchdoctor_graspofthedead.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">150</span> Mana<br/><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">8</span> seconds</p><p>Ghoulish hands reach out from the ground, slowing enemy movement by <span class=\"d3-color-green\">60%</span> and dealing <span class=\"d3-color-green\">760%</span> weapon damage as Physical over <span class=\"d3-color-green\">8</span> seconds.</p> <p class=\"special\">Secondary</p> <p class=\"subtle\">Unlocked at level <em>2</em>.</p> </div> </div>",
  },
  haunt: {
    a: "<p>The spirit returns <span class=\"d3-color-green\">4291</span> Life per second.</p><p>Haunt's damage turns into Fire.</p> <p class=\"subtle\">Unlocked at level <em>18</em>.</p>",
    b: "<p>If there are no enemies left, the spirit will linger for up to <span class=\"d3-color-green\">10</span> seconds looking for new enemies.</p> <p class=\"subtle\">Unlocked at level <em>35</em>.</p>",
    c: "<p>Haunted enemies take <span class=\"d3-color-green\">20%</span> more damage from all sources.</p><p>Haunt's damage turns into Poison.</p> <p class=\"subtle\">Unlocked at level <em>48</em>.</p>",
    d: "<p>The spirit returns <span class=\"d3-color-green\">13</span> Mana per second.</p><p>Haunt's damage turns into Physical.</p> <p class=\"subtle\">Unlocked at level <em>57</em>.</p>",
    e: "<p>Release two spirits with every cast.</p> <p class=\"subtle\">Unlocked at level <em>23</em>.</p>",
    elements: {
      a: "fir",
      b: "col",
      c: "psn",
      d: "phy",
      e: "col",
      x: "col",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/witchdoctor_haunt.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">50</span> Mana</p><p>Haunt an enemy with a spirit, dealing <span class=\"d3-color-green\">4000%</span> weapon damage as Cold over <span class=\"d3-color-green\">12</span> seconds. If the enemy dies, the spirit will haunt another nearby enemy.</p><p><span class=\"d3-color-yellow\">An enemy can only be affected by one Haunt at a time.</span></p> <p class=\"special\">Secondary</p> <p class=\"subtle\">Unlocked at level <em>12</em>.</p> </div> </div>",
  },
  hex: {
    a: "<p>Summon a giant toad that pulls in enemies, briefly swallows them whole, then spits them back out with a layer of goo that deals <span class=\"d3-color-green\">750%</span> weapon damage as Poison over <span class=\"d3-color-green\">5</span> seconds, Slows them, and increases their damage taken by <span class=\"d3-color-green\">25%</span>.</p> <p class=\"subtle\">Unlocked at level <em>43</em>.</p>",
    b: "<p>Transform into an angry chicken for up to <span class=\"d3-color-green\">2</span> seconds that can explode for <span class=\"d3-color-green\">1350%</span> weapon damage as Poison to all enemies within <span class=\"d3-color-green\">12</span> yards.</p> <p class=\"subtle\">Unlocked at level <em>36</em>.</p>",
    c: "<p>Hexed enemies explode when killed, dealing <span class=\"d3-color-green\">500%</span> weapon damage as Fire to all enemies within <span class=\"d3-color-green\">8</span> yards.</p> <p class=\"subtle\">Unlocked at level <em>58</em>.</p>",
    d: "<p>The Fetish Shaman will periodically heal allies for <span class=\"d3-color-green\">32185</span> Life.</p> <p class=\"subtle\">Unlocked at level <em>26</em>.</p>",
    e: "<p>Increases the magnitude of the hex to <span class=\"d3-color-green\">30%</span> additional damage.</p> <p class=\"subtle\">Unlocked at level <em>31</em>.</p>",
    elements: {
      a: "psn",
      b: "psn",
      c: "fir",
      d: "col",
      e: "psn",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/witchdoctor_hex.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">15</span> seconds</p><p>Summon a Fetish Shaman for <span class=\"d3-color-green\">12</span> seconds that will hex groups of enemies into chickens. Hexed enemies are unable to perform offensive actions and take <span class=\"d3-color-green\">15%</span> additional damage.</p> <p class=\"special\">Defensive</p> <p class=\"subtle\">Unlocked at level <em>22</em>.</p> </div> </div>",
  },
  horrify: {
    a: "<p>Gain <span class=\"d3-color-green\">50%</span> additional Armor for <span class=\"d3-color-green\">8</span> seconds after casting Horrify.</p> <p class=\"subtle\">Unlocked at level <em>44</em>.</p>",
    b: "<p>Increase the radius of Horrify to <span class=\"d3-color-green\">24</span> yards. </p> <p class=\"subtle\">Unlocked at level <em>34</em>.</p>",
    c: "<p>Enemies are no longer Immobilized and will instead run in Fear for <span class=\"d3-color-green\">5</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>14</em>.</p>",
    d: "<p>Gain <span class=\"d3-color-green\">55</span> Mana for every horrified enemy.</p> <p class=\"subtle\">Unlocked at level <em>56</em>.</p>",
    e: "<p>Increase movement speed by <span class=\"d3-color-green\">20%</span> for <span class=\"d3-color-green\">4</span> seconds after casting Horrify.</p> <p class=\"subtle\">Unlocked at level <em>21</em>.</p>",
    elements: {
      a: "phy",
      b: "phy",
      c: "phy",
      d: "phy",
      e: "phy",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/witchdoctor_horrify.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">10</span> seconds</p><p>Don a spectral mask that horrifies all enemies within <span class=\"d3-color-green\">18</span> yards, causing them to tremor in Fear and be Immobilized for <span class=\"d3-color-green\">3</span> seconds.</p> <p class=\"special\">Defensive</p> <p class=\"subtle\">Unlocked at level <em>8</em>.</p> </div> </div>",
  },
  locustswarm: {
    a: "<p>Engulf the enemy with burning locusts that deal <span class=\"d3-color-green\">1480%</span> weapon damage as Fire over <span class=\"d3-color-green\">8</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>59</em>.</p>",
    b: "<p>Locust Swarm has a <span class=\"d3-color-green\">100%</span> chance to jump to two additional enemies instead of one. </p> <p class=\"subtle\">Unlocked at level <em>27</em>.</p>",
    c: "<p>Enemies affected deal <span class=\"d3-color-green\">25%</span> reduced damage.</p> <p class=\"subtle\">Unlocked at level <em>37</em>.</p>",
    d: "<p>Gain <span class=\"d3-color-green\">25</span> Mana a second while the first enemy hit by a Locust Swarm cast is still affected by that swarm. </p> <p class=\"subtle\">Unlocked at level <em>33</em>.</p>",
    e: "<p>Enemies killed while affected by Locust Swarm leave behind a cloud of locusts that deal <span class=\"d3-color-green\">750%</span> weapon damage as Poison over <span class=\"d3-color-green\">3</span> seconds to enemies who stand in the area.</p> <p class=\"subtle\">Unlocked at level <em>42</em>.</p>",
    elements: {
      a: "fir",
      b: "psn",
      c: "phy",
      d: "col",
      e: "psn",
      x: "psn",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/witchdoctor_locust_swarm.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">300</span> Mana</p><p>Unleash a plague of locusts that swarms an enemy, dealing <span class=\"d3-color-green\">1040%</span> weapon damage as Poison over <span class=\"d3-color-green\">8</span> seconds.</p><p>The locusts will jump to additional nearby enemies.</p> <p class=\"special\">Secondary</p> <p class=\"subtle\">Unlocked at level <em>21</em>.</p> </div> </div>",
  },
  massconfusion: {
    a: "<p>All enemies in the area of Mass Confusion take <span class=\"d3-color-green\">30%</span> additional damage for <span class=\"d3-color-green\">12</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>46</em>.</p>",
    b: "<p>Up to <span class=\"d3-color-green\">10</span> enemies who are not Confused become Stunned for <span class=\"d3-color-green\">3</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>43</em>.</p>",
    c: "<p>Amid the confusion, a giant spirit rampages through enemies, dealing <span class=\"d3-color-green\">400%</span> weapon damage per second as Physical to enemies it passes through.</p> <p class=\"subtle\">Unlocked at level <em>54</em>.</p>",
    d: "<p>Reduce the cooldown of Mass Confusion to <span class=\"d3-color-green\">30</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>26</em>.</p>",
    e: "<p>Enemies killed while Confused have a <span class=\"d3-color-green\">100%</span> chance to spawn a Zombie Dog.</p> <p class=\"subtle\">Unlocked at level <em>34</em>.</p>",
    elements: {
      a: "phy",
      b: "phy",
      c: "phy",
      d: "phy",
      e: "phy",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/witchdoctor_massconfusion.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">60</span> seconds</p><p>Incite paranoia in enemies, confusing them and causing some to be <span class=\"d3-color-green\">Charmed</span> and fight for you for <span class=\"d3-color-green\">12</span> seconds.</p> <p class=\"special\">Terror</p> <p class=\"subtle\">Unlocked at level <em>22</em>.</p> </div> </div>",
  },
  piranhas: {
    a: "<p>A giant bogadile emerges from the pool of water, <span class=\"d3-color-green\">Stuns</span>, and bites a monster dealing <span class=\"d3-color-green\">1100%</span> weapon damage as Physical.</p> <p class=\"subtle\">Unlocked at level <em>62</em>.</p>",
    b: "<p>Turn the piranhas into zombie piranhas.  The piranhas will leap out from the pool savagely at nearby enemies</p> <p class=\"subtle\">Unlocked at level <em>63</em>.</p>",
    c: "<p>The pool of piranhas becomes a tornado of piranhas that lasts <span class=\"d3-color-green\">4</span> seconds.  Nearby enemies are periodically sucked into the tornado.</p><p>Increases the cooldown to <span class=\"d3-color-green\">16</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>65</em>.</p>",
    d: "<p>Turn each cast into a wave of piranhas that crash forward dealing <span class=\"d3-color-green\">475%</span> weapon damage and causing all enemies affected to take <span class=\"d3-color-green\">15%</span> increased damage for <span class=\"d3-color-green\">8</span> seconds. </p> <p class=\"subtle\">Unlocked at level <em>67</em>.</p>",
    e: "<p>Changes the damage dealt to <span class=\"d3-color-green\">400%</span> weapon damage as Cold over <span class=\"d3-color-green\">8</span> seconds, chilling enemies for the entire duration.</p> <p class=\"subtle\">Unlocked at level <em>69</em>.</p>",
    elements: {
      a: "phy",
      b: "psn",
      c: "psn",
      d: "psn",
      e: "col",
      x: "psn",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/witchdoctor_piranhas.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">250</span> Mana<br/><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">8</span> seconds</p><p>Summons a pool of deadly piranhas that deals <span class=\"d3-color-green\">400%</span> weapon damage as Poison over <span class=\"d3-color-green\">8</span> seconds.  Affected enemies will also take <span class=\"d3-color-green\">15%</span> increased damage.</p> <p class=\"special\">Decay</p> <p class=\"subtle\">Unlocked at level <em>61</em>.</p> </div> </div>",
  },
  plagueoftoads: {
    a: "<p>Mutate to fire bullfrogs that explode for <span class=\"d3-color-green\">245%</span> weapon damage as Fire.</p> <p class=\"subtle\">Unlocked at level <em>17</em>.</p>",
    b: "<p>Cause toads to rain from the sky that deal <span class=\"d3-color-green\">182%</span> weapon damage as Poison to enemies in the area over <span class=\"d3-color-green\">2</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>35</em>.</p>",
    c: "<p>Mutate to frogs that pierce through enemies for <span class=\"d3-color-green\">130%</span> weapon damage as Physical.</p> <p class=\"subtle\">Unlocked at level <em>24</em>.</p>",
    d: "<p>Gain <span class=\"d3-color-green\">9</span> Mana every time a toad hits an enemy.</p><p>Plague of Toads' damage turns into Cold.</p> <p class=\"subtle\">Unlocked at level <em>54</em>.</p>",
    e: "<p>Mutate to yellow toads that deal <span class=\"d3-color-green\">190%</span> weapon damage as Poison and have a <span class=\"d3-color-green\">15%</span> chance to Confuse affected enemies for <span class=\"d3-color-green\">4</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>51</em>.</p>",
    elements: {
      a: "fir",
      b: "psn",
      c: "phy",
      d: "col",
      e: "psn",
      x: "psn",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/witchdoctor_plagueoftoads.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">This is a Signature spell. Signature spells are free to cast.</span></p><p>Release a handful of toads that deal <span class=\"d3-color-green\">190%</span> weapon damage as Poison to enemies they come in contact with.</p> <p class=\"special\">Primary</p> <p class=\"subtle\">Unlocked at level <em>11</em>.</p> </div> </div>",
  },
  poisondart: {
    a: "<p>Ignite the dart, dealing <span class=\"d3-color-green\">565%</span> weapon damage as Fire over <span class=\"d3-color-green\">4</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>43</em>.</p>",
    b: "<p>Shoot <span class=\"d3-color-green\">3</span> Poison Darts that deal <span class=\"d3-color-green\">110%</span> weapon damage as Poison each.</p> <p class=\"subtle\">Unlocked at level <em>6</em>.</p>",
    c: "<p>Shoot a Cold dart that will Slow the enemy by <span class=\"d3-color-green\">60%</span> for <span class=\"d3-color-green\">2</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>13</em>.</p>",
    d: "<p>Gain <span class=\"d3-color-green\">50</span> Mana every time a Poison Dart hits an enemy. Converts the damage type to Physical.</p> <p class=\"subtle\">Unlocked at level <em>25</em>.</p>",
    e: "<p>Transform your Poison Dart into a snake that has a <span class=\"d3-color-green\">35%</span> chance to Stun the enemy for <span class=\"d3-color-green\">1.5</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>52</em>.</p>",
    elements: {
      a: "fir",
      b: "psn",
      c: "col",
      d: "phy",
      e: "psn",
      x: "psn",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/witchdoctor_poisondart.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">This is a Signature spell. Signature spells are free to cast.</span></p><p>Shoot a deadly Poison Dart that deals <span class=\"d3-color-green\">185%</span> weapon damage as Poison and an additional <span class=\"d3-color-green\">40%</span> weapon damage as Poison over <span class=\"d3-color-green\">2</span> seconds.</p> <p class=\"special\">Primary</p> <p class=\"subtle\">Unlocked at level <em>1</em>.</p> </div> </div>",
  },
  sacrifice: {
    a: "<p>Gain <span class=\"d3-color-green\">20%</span> increased damage done for <span class=\"d3-color-green\">5</span> seconds after using Sacrifice.</p> <p class=\"subtle\">Unlocked at level <em>51</em>.</p>",
    b: "<p>Command all of your Zombie Dogs to charge the target at the same time, each dealing <span class=\"d3-color-green\">1300%</span> weapon damage as Physical.</p> <p class=\"subtle\">Unlocked at level <em>41</em>.</p>",
    c: "<p>Ichor erupts from the corpse of the Zombie Dog and Stuns enemies for <span class=\"d3-color-green\">3</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>18</em>.</p>",
    d: "<p>Gain <span class=\"d3-color-green\">280</span> Mana for each Zombie Dog you sacrifice.</p> <p class=\"subtle\">Unlocked at level <em>36</em>.</p>",
    e: "<p>Each Zombie Dog you sacrifice has a <span class=\"d3-color-green\">35%</span> chance to resurrect as a new Zombie Dog.</p> <p class=\"subtle\">Unlocked at level <em>24</em>.</p>",
    elements: {
      a: "phy",
      b: "phy",
      c: "phy",
      d: "phy",
      e: "phy",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/witchdoctor_sacrifice.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>Banish one of your active Zombie Dogs causing it to explode, dealing <span class=\"d3-color-green\">1090%</span> of your weapon damage as Physical to all enemies within <span class=\"d3-color-green\">12</span> yards.</p> <p class=\"special\">Terror</p> <p class=\"subtle\">Unlocked at level <em>13</em>.</p> </div> </div>",
  },
  soulharvest: {
    a: "<p>Gain <span class=\"d3-color-green\">32185</span> Life for every harvested enemy.</p> <p class=\"subtle\">Unlocked at level <em>21</em>.</p>",
    b: "<p>Gain <span class=\"d3-color-green\">5%</span> increased movement speed for each enemy harvested.</p> <p class=\"subtle\">Unlocked at level <em>39</em>.</p>",
    c: "<p>Increase your Armor by <span class=\"d3-color-green\">10%</span> per harvested enemy and reduce their movement speed by <span class=\"d3-color-green\">80%</span> for <span class=\"d3-color-green\">5</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>32</em>.</p>",
    d: "<p>Gain mana and increase maximum Mana by <span class=\"d3-color-green\">5%</span> for each enemy harvested.</p> <p class=\"subtle\">Unlocked at level <em>15</em>.</p>",
    e: "<p>Harvested enemies also take <span class=\"d3-color-green\">640%</span> weapon damage as Physical.</p> <p class=\"subtle\">Unlocked at level <em>49</em>.</p>",
    elements: {
      a: "phy",
      b: "fir",
      c: "col",
      d: "psn",
      e: "phy",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/witchdoctor_soulharvest.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">12</span> seconds</p><p>Feed on the life force of enemies within <span class=\"d3-color-green\">18</span> yards. Gain <span class=\"d3-color-green\">3%</span> Intelligence for <span class=\"d3-color-green\">30</span> seconds for each affected enemy. This effect stacks up to <span class=\"d3-color-green\">5</span> times.</p> <p class=\"special\">Terror</p> <p class=\"subtle\">Unlocked at level <em>9</em>.</p> </div> </div>",
  },
  spiritbarrage: {
    a: "<p>Gain <span class=\"d3-color-green\">6437</span> Life each time Spirit Barrage hits.</p> <p class=\"subtle\">Unlocked at level <em>44</em>.</p>",
    b: "<p>An additional <span class=\"d3-color-green\">3</span> spirits seek out other enemies and deal <span class=\"d3-color-green\">65%</span> weapon damage as Fire.</p> <p class=\"subtle\">Unlocked at level <em>32</em>.</p>",
    c: "<p>Summon a spectre that deals <span class=\"d3-color-green\">675%</span> weapon damage as Cold over <span class=\"d3-color-green\">5</span> seconds to all enemies within <span class=\"d3-color-green\">10</span> yards.</p><p>You can have a maximum of <span class=\"d3-color-green\">3</span> Phantasms out at one time.</p> <p class=\"subtle\">Unlocked at level <em>37</em>.</p>",
    d: "<p>Gain <span class=\"d3-color-green\">12</span> Mana each time Spirit Barrage hits.</p> <p class=\"subtle\">Unlocked at level <em>23</em>.</p>",
    e: "<p>Summon a spectre that hovers over you, unleashing spirit bolts at nearby enemies for <span class=\"d3-color-green\">6000%</span> weapon damage as Cold over <span class=\"d3-color-green\">20</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>59</em>.</p>",
    elements: {
      a: "col",
      b: "fir",
      c: "col",
      d: "col",
      e: "col",
      x: "col",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/witchdoctor_spiritbarrage.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">100</span> Mana</p><p>Bombard an enemy with <span class=\"d3-color-green\">4</span> spirit bolts that deal a total of <span class=\"d3-color-green\">600%</span> weapon damage as Cold.</p> <p class=\"special\">Decay</p> <p class=\"subtle\">Unlocked at level <em>17</em>.</p> </div> </div>",
  },
  spiritwalk: {
    a: "<p>Increase your movement speed by an additional <span class=\"d3-color-green\">100%</span> while in the spirit realm.</p> <p class=\"subtle\">Unlocked at level <em>47</em>.</p>",
    b: "<p>Increase the duration of Spirit Walk to <span class=\"d3-color-green\">3</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>23</em>.</p>",
    c: "<p>When Spirit Walk ends, your physical body erupts for <span class=\"d3-color-green\">750%</span> weapon damage as Fire to all enemies within <span class=\"d3-color-green\">10</span> yards.</p> <p class=\"subtle\">Unlocked at level <em>38</em>.</p>",
    d: "<p>Gain <span class=\"d3-color-green\">20%</span> of your maximum Mana when you activate Spirit Walk.</p> <p class=\"subtle\">Unlocked at level <em>29</em>.</p>",
    e: "<p>Gain <span class=\"d3-color-green\">15%</span> of your maximum Life when you activate Spirit Walk.</p> <p class=\"subtle\">Unlocked at level <em>53</em>.</p>",
    elements: {
      a: "phy",
      b: "phy",
      c: "fir",
      d: "phy",
      e: "phy",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/witchdoctor_spiritwalk.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">10</span> seconds</p><p>Leave your physical body and enter the spirit realm for <span class=\"d3-color-green\">2</span> seconds. While in the spirit realm, your movement is unhindered.</p><p><span class=\"d3-color-yellow\">This ability does not start its cooldown until after its effects expire.</span></p> <p class=\"special\">Defensive</p> <p class=\"subtle\">Unlocked at level <em>16</em>.</p> </div> </div>",
  },
  summonzombiedogs: {
    a: "<p>Your Zombie Dogs burst into flames, burning nearby enemies for <span class=\"d3-color-green\">80%</span> of your weapon damage as Fire every second.</p> <p class=\"subtle\">Unlocked at level <em>40</em>.</p>",
    b: "<p>Your Zombie Dogs absorb <span class=\"d3-color-green\">10%</span> of all damage done to you.</p> <p class=\"subtle\">Unlocked at level <em>28</em>.</p>",
    c: "<p>Your Zombie Dogs gain an infectious bite that deals <span class=\"d3-color-green\">120%</span> of your weapon damage as Poison over <span class=\"d3-color-green\">3</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>12</em>.</p>",
    d: "<p>Enemies who hit or are hit by your Zombie Dogs are <span class=\"d3-color-green\">Chilled</span> for <span class=\"d3-color-green\">3</span> seconds and take <span class=\"d3-color-green\">15%</span> increased damage from all sources.</p> <p class=\"subtle\">Unlocked at level <em>19</em>.</p>",
    e: "<p>Your Zombie Dogs heal you for <span class=\"d3-color-green\">100%</span> of your Life On Hit with every attack.</p> <p class=\"subtle\">Unlocked at level <em>54</em>.</p>",
    elements: {
      a: "fir",
      b: "phy",
      c: "psn",
      d: "col",
      e: "phy",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/witchdoctor_summonzombiedog.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">45</span> seconds</p><p>Summon <span class=\"d3-color-green\">3</span> Zombie Dogs from the depths to fight by your side. Each dog deals <span class=\"d3-color-green\">120%</span> of your weapon damage as Physical per hit.</p> <p class=\"special\">Defensive</p> <p class=\"subtle\">Unlocked at level <em>4</em>.</p> </div> </div>",
  },
  wallofdeath: {
    a: "<p>Raise a circle of zombies from the ground that traps and attacks nearby enemies for <span class=\"d3-color-green\">1250%</span> weapon damage as Physical over <span class=\"d3-color-green\">5</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>41</em>.</p>",
    b: "<p>Summon a deadly ring for <span class=\"d3-color-green\">5</span> seconds that poisons nearby enemies for <span class=\"d3-color-green\">1200%</span> weapon damage as Poison over <span class=\"d3-color-green\">8</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>32</em>.</p>",
    c: "<p>Summon a circle of spirits for <span class=\"d3-color-green\">6</span> seconds that deals <span class=\"d3-color-green\">1200%</span> weapon damage as Cold, Chills nearby enemies by <span class=\"d3-color-green\">60%</span>, and reduces their damage dealt by <span class=\"d3-color-green\">25%</span> for <span class=\"d3-color-green\">3</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>60</em>.</p>",
    d: "<p>Increase the width of the wall to <span class=\"d3-color-green\">50</span> yards. All enemies in front of you are knocked back behind the wall.</p> <p class=\"subtle\">Unlocked at level <em>35</em>.</p>",
    e: "<p>Raise a wall of flame <span class=\"d3-color-green\">40</span> yards wide for <span class=\"d3-color-green\">8</span> seconds that burns enemies who walk through, causing them to take <span class=\"d3-color-green\">1100%</span> weapon damage as Fire over <span class=\"d3-color-green\">4</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>49</em>.</p>",
    elements: {
      a: "phy",
      b: "psn",
      c: "col",
      d: "phy",
      e: "fir",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/witchdoctor_wallofzombies.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">8</span> seconds</p><p>Raise a wall of zombies <span class=\"d3-color-green\">28</span> yards wide from the ground that blocks enemies and attacks them for <span class=\"d3-color-green\">1200%</span> weapon damage as Physical over <span class=\"d3-color-green\">6</span> seconds.</p> <p class=\"special\">Decay</p> <p class=\"subtle\">Unlocked at level <em>28</em>.</p> </div> </div>",
  },
  zombiecharger: {
    a: "<p>Summon zombie bears that stampede towards your enemy. Each bear deals <span class=\"d3-color-green\">520%</span> weapon damage as Poison to enemies in the area.</p> <p class=\"subtle\">Unlocked at level <em>54</em>.</p>",
    b: "<p>Zombie winter bears crawl out of the ground and run in all directions, dealing <span class=\"d3-color-green\">280%</span> weapon damage as Cold to nearby enemies.</p> <p class=\"subtle\">Unlocked at level <em>33</em>.</p>",
    c: "<p>Summon a tower of zombies that falls over, dealing <span class=\"d3-color-green\">880%</span> weapon damage as Physical to any enemies it hits.</p> <p class=\"subtle\">Unlocked at level <em>21</em>.</p>",
    d: "<p>If the Zombie Charger kills any enemies, it will reanimate and charge nearby enemies for <span class=\"d3-color-green\">480%</span> weapon damage as Poison. This effect can repeat up to <span class=\"d3-color-green\">2</span> times.</p> <p class=\"subtle\">Unlocked at level <em>27</em>.</p>",
    e: "<p>Summon an explosive Zombie Dog that streaks toward the enemy before exploding, dealing <span class=\"d3-color-green\">680%</span> weapon damage as Fire to all enemies within <span class=\"d3-color-green\">12</span> yards.</p> <p class=\"subtle\">Unlocked at level <em>42</em>.</p>",
    elements: {
      a: "psn",
      b: "col",
      c: "phy",
      d: "psn",
      e: "fir",
      x: "psn",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/witchdoctor_zombiecharger.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">150</span> Mana</p><p>Call forth a reckless, suicidal zombie that deals <span class=\"d3-color-green\">560%</span> weapon damage as Poison to all enemies in its path before decomposing.</p> <p class=\"special\">Decay</p> <p class=\"subtle\">Unlocked at level <em>14</em>.</p> </div> </div>",
  },
};
DiabloCalc.passivetips.witchdoctor = {
  badmedicine: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/witchdoctor_passive_badmedicine.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>When you deal Poison damage to an enemy, its damage is reduced by <span class=\"d3-color-green\">25%</span> for <span class=\"d3-color-green\">5</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>20</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"Their mastery of paralytic agents is astounding. The jungle, they say, provides ample demonstration of its wonders.\" —Abner Lockridge</div> </div>",
  bloodritual: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/witchdoctor_passive_bloodritual.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-green\">20%</span> of Mana costs are paid with Life. In addition, you regenerate <span class=\"d3-color-green\">1%</span> of your maximum Life per second.</p> <p class=\"subtle\">Unlocked at level <em>20</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"To give of one's self... Is there any greater gift?\" —Final words spoken at the Ritual of Blood</div> </div>",
  circleoflife: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/witchdoctor_passive_circleoflife.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>When an enemy dies within <span class=\"d3-color-green\">20</span> yards, there is a <span class=\"d3-color-green\">15%</span> chance that a Zombie Dog will automatically emerge.</p><p>The range of this effect is increased by your gold pickup radius.</p> <p class=\"subtle\">Unlocked at level <em>10</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"The heads hanging in the village had their eyes sewn shut with thick thread. Whatever wicked magic held the frightful hound-beasts together was considerably stronger.\" —Abner Lockridge</div> </div>",
  confidenceritual: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/x1_witchdoctor_passive_confidenceritual.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>You deal <span class=\"d3-color-green\">25%</span> additional damage to enemies within <span class=\"d3-color-green\">20</span> yards.</p> <p class=\"subtle\">Unlocked at level <em>60</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">Take your enemies into your confidence. Bring them close, so that they may share the fruits of your efforts.</div> </div>",
  creepingdeath: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/witchdoctor_passive_creepingdeath.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>Your Haunt, Locust Swarm and the damage amplification from Piranhas last almost forever. </p> <p class=\"subtle\">Unlocked at level <em>64</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">There are some terrors that cannot be outrun. Bit by bit, second by second, they consume you.</div> </div>",
  fetishsycophants: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/witchdoctor_passive_fetishsycophants.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>When you hit enemies with your spells, you have up to a <span class=\"d3-color-green\">15%</span> chance to summon a dagger-wielding Fetish to fight by your side for <span class=\"d3-color-green\">60</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>30</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">The denizens of the Unformed Land are mischievous and drawn to power, always seeking to intrude upon our world, but too fickle to stay for long.</div> </div>",
  fierceloyalty: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/witchdoctor_passive_fierceloyalty.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>While you have a Gargantuan, Zombie Dog, or Fetish summoned, your movement speed is increased by <span class=\"d3-color-green\">15%</span>.</p><p>This bonus is increased to <span class=\"d3-color-green\">30%</span> while a Gargantuan, Zombie Dog, or Fetish is not in combat.</p><p>Additionally, you may have <span class=\"d3-color-green\">1</span> additional Zombie Dog summoned at one time.</p> <p class=\"subtle\">Unlocked at level <em>45</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">Establish dominance. They will obey.</div> </div>",
  graveinjustice: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/witchdoctor_passive_graveinjustice.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>Gain <span class=\"d3-color-green\">1%</span> of your maximum Life and Mana and reduce the cooldown of all of your skills by <span class=\"d3-color-green\">1</span> second when an enemy dies within <span class=\"d3-color-green\">20</span> yards.</p><p>The range is extended by items that increase your gold pickup radius.</p> <p class=\"subtle\">Unlocked at level <em>50</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">Only a fool tries to cheat death. The wise offer a fair trade.</div> </div>",
  gruesomefeast: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/witchdoctor_passive_gruesomefeast.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>When you are healed by a health globe, gain <span class=\"d3-color-green\">10%</span> of your maximum Mana and <span class=\"d3-color-green\">10%</span> Intelligence for <span class=\"d3-color-green\">15</span> seconds. The Intelligence bonus stacks up to <span class=\"d3-color-green\">5</span> times.</p> <p class=\"subtle\">Unlocked at level <em>16</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"We are all connected in life and in death. Partake of the spirits of the dead and flourish like the jungle that grows wild after the fire.\" —Shadewalker Zunimassa</div> </div>",
  junglefortitude: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/witchdoctor_passive_junglefortitude.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>Reduce all damage taken by you and your pets by <span class=\"d3-color-green\">15%</span>.</p> <p class=\"subtle\">Unlocked at level <em>10</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">To be one with the jungle is to take what you need and endure what you must.</div> </div>",
  midnightfeast: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/witchdoctor_passive_midnightfeast.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>The damage of your Zombie Dogs and Gargantuan is increased by <span class=\"d3-color-green\">50%</span>.</p><p>Additionally, you may have <span class=\"d3-color-green\">1</span> additional Zombie Dog summoned at one time.</p> <p class=\"subtle\">Unlocked at level <em>68</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">In the deepest hour of night, they emerge for the hunt.</div> </div>",
  piercetheveil: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/witchdoctor_passive_piercetheveil.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>All of your damage is increased by <span class=\"d3-color-green\">20%</span>, but your Mana costs are increased by <span class=\"d3-color-green\">30%</span>.</p> <p class=\"subtle\">Unlocked at level <em>27</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"The spirits take their toll. Best to be ready to pay.\" —Shadewalker Zunimassa</div> </div>",
  rushofessence: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/witchdoctor_passive_rushofessence.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>Spirit spells return <span class=\"d3-color-green\">100</span> Mana over <span class=\"d3-color-green\">10</span> seconds.</p><p>Spirit spells are:<br/><span class=\"tooltip-icon-bullet\"></span> Haunt<br/><span class=\"tooltip-icon-bullet\"></span> Horrify<br/><span class=\"tooltip-icon-bullet\"></span> Mass Confusion<br/><span class=\"tooltip-icon-bullet\"></span> Soul Harvest<br/><span class=\"tooltip-icon-bullet\"></span> Spirit Barrage<br/><span class=\"tooltip-icon-bullet\"></span> Spirit Walk</p> <p class=\"subtle\">Unlocked at level <em>36</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">All spirits must move onward if they wish to return to their origins. There is no going back.</div> </div>",
  spiritualattunement: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/witchdoctor_passive_spiritualattunement.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>Maximum Mana is increased by <span class=\"d3-color-green\">10%</span>. Regenerate <span class=\"d3-color-green\">2%</span> of your maximum Mana per second.</p><p>Mana fuels your offensive and defensive skills.</p> <p class=\"subtle\">Unlocked at level <em>13</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"The pool is deep and still, cool and silent. Now a fountain, now a whirlpool. Drink and be renewed.\" —Runic carvings on the Shallow Stone</div> </div>",
  spiritvessel: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/witchdoctor_passive_spiritvessel.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>When you receive fatal damage, you automatically enter the spirit realm for <span class=\"d3-color-green\">2</span> seconds and heal to <span class=\"d3-color-green\">50%</span> of your maximum Life. </p><p>This effect may occur once every <span class=\"d3-color-green\">60</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>30</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">Everyone dies. Sometimes we must return to finish what we started.</div> </div>",
  swamplandattunement: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/witchdoctor_passive_physicalattunement.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>You and your pets gain <span class=\"d3-color-green\">120</span> Physical, Poison, Fire, and Cold Resistance for every enemy within <span class=\"d3-color-green\">20</span> yards.</p><p>The range of this effect is increased by your gold pickup radius.</p> <p class=\"subtle\">Unlocked at level <em>66</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">Know your enemies. Know their strength. Make it your own.</div> </div>",
  tribalrites: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/witchdoctor_passive_tribalrites.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>Reduce the cooldowns of the following skills by <span class=\"d3-color-green\">25%</span>:<br/><span class=\"tooltip-icon-bullet\"></span> Hex<br/><span class=\"tooltip-icon-bullet\"></span> Gargantuan<br/><span class=\"tooltip-icon-bullet\"></span> Fetish Army<br/><span class=\"tooltip-icon-bullet\"></span> Summon Zombie Dogs<br/><span class=\"tooltip-icon-bullet\"></span> Big Bad Voodoo<br/><span class=\"tooltip-icon-bullet\"></span> Mass Confusion</p> <p class=\"subtle\">Unlocked at level <em>55</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"Befriend those who come from the Unformed Land, and they will befriend you.\" —Zuwadza of the Tribe of the Five Hills</div> </div>",
  visionquest: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/witchdoctor_passive_visionquest.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>When you deal damage with Corpse Spiders, Firebomb, Plague of Toads, or Poison Dart, your Mana regeneration is increased by <span class=\"d3-color-green\">40%</span> for <span class=\"d3-color-green\">5</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>40</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"You sense but do not see. Walk beside yourself in the Unformed Land. Walk until you find yourself again, or wander lost forever.\" —Chant of Ordeal</div> </div>",
  zombiehandler: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/witchdoctor_passive_zombiehandler.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>Your Life, and that of your Zombie Dogs and Gargantuan are increased by <span class=\"d3-color-green\">20%</span>.</p><p>Additionally, you may have <span class=\"d3-color-green\">1</span> additional Zombie Dog summoned at one time.</p> <p class=\"subtle\">Unlocked at level <em>24</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">The dead are willing minions. Death to them is not unknown, therefore need not be feared.</div> </div>",
};
