if (!DiabloCalc.skilltips) DiabloCalc.skilltips = {};
if (!DiabloCalc.passivetips) DiabloCalc.passivetips = {};
DiabloCalc.skilltips.wizard = {
  arcaneorb: {
    a: "<p>Increase the speed of the orb and its damage to <span class=\"d3-color-green\">700%</span> weapon damage as Arcane, but reduce the area of effect to <span class=\"d3-color-green\">8</span> yards.</p> <p class=\"subtle\">Unlocked at level <em>11</em>.</p>",
    b: "<p>Lob an electrified orb over enemies that zaps them for <span class=\"d3-color-green\">349%</span> weapon damage as Lightning and increases the damage of the next Lightning spell you cast by <span class=\"d3-color-green\">2%</span> for every enemy hit.</p> <p class=\"subtle\">Unlocked at level <em>32</em>.</p>",
    c: "<p>Create <span class=\"d3-color-green\">4</span> Arcane Orbs that orbit you, exploding for <span class=\"d3-color-green\">265%</span> weapon damage as Arcane when enemies get close. </p> <p class=\"subtle\">Unlocked at level <em>20</em>.</p>",
    d: "<p>Launch a burning orb that deals <span class=\"d3-color-green\">221%</span> weapon damage as Fire. The orb leaves behind a wall of Fire that deals <span class=\"d3-color-green\">734%</span> weapon damage as Fire over <span class=\"d3-color-green\">5</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>45</em>.</p>",
    e: "<p>Create an orb of frozen death that shreds an area with ice bolts, dealing <span class=\"d3-color-green\">393%</span> weapon damage as Cold.</p> <p class=\"subtle\">Unlocked at level <em>55</em>.</p>",
    elements: {
      a: "arc",
      b: "lit",
      c: "arc",
      d: "fir",
      e: "col",
      x: "arc",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/wizard_arcaneorb.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">30</span> Arcane Power</p><p>Hurl an orb of pure energy that explodes on contact, dealing <span class=\"d3-color-green\">435%</span> weapon damage as Arcane to all enemies within <span class=\"d3-color-green\">15</span> yards.</p> <p class=\"special\">Secondary</p> <p class=\"subtle\">Unlocked at level <em>5</em>.</p> </div> </div>",
  },
  arcanetorrent: {
    a: "<p>You take <span class=\"d3-color-green\">15%</span> less damage from attacks while channeling. Every second you channel increases this amount by <span class=\"d3-color-green\">5%</span>, up to a maximum total of <span class=\"d3-color-green\">25%</span> damage reduction.</p><p>Arcane Torrent's damage turns into Fire.</p> <p class=\"subtle\">Unlocked at level <em>18</em>.</p>",
    b: "<p>Enemies hit by Arcane Torrent have a <span class=\"d3-color-green\">12.5%</span> chance to fire a new missile at a nearby enemy dealing <span class=\"d3-color-green\">582%</span> weapon damage as Arcane.</p> <p class=\"subtle\">Unlocked at level <em>57</em>.</p>",
    c: "<p>Lay Arcane mines that arm after <span class=\"d3-color-green\">2</span> seconds. These mines explode when an enemy approaches, dealing <span class=\"d3-color-green\">825%</span> weapon damage as Arcane. Enemies caught in the explosion have their movement and attack speeds reduced by <span class=\"d3-color-green\">60%</span> for <span class=\"d3-color-green\">3</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>34</em>.</p>",
    d: "<p>Each missile explodes into <span class=\"d3-color-green\">2</span> piercing bolts of electricity that each deal <span class=\"d3-color-green\">150%</span> weapon damage as Lightning.</p> <p class=\"subtle\">Unlocked at level <em>49</em>.</p>",
    e: "<p>Unleash a torrent of power beyond your control. You no longer direct where the projectiles go, but their damage is greatly increased to <span class=\"d3-color-green\">1215%</span> weapon damage as Arcane.</p><p>Arcane Torrent damage is increased by <span class=\"d3-color-green\">640%</span> weapon damage every second, up to a maximum total of <span class=\"d3-color-green\">2495%</span> weapon damage as Arcane.</p> <p class=\"subtle\">Unlocked at level <em>25</em>.</p>",
    elements: {
      a: "fir",
      b: "arc",
      c: "arc",
      d: "lit",
      e: "arc",
      x: "arc",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/wizard_arcanetorrent.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">16</span> Arcane Power</p><p>Hurl a barrage of arcane projectiles that deal <span class=\"d3-color-green\">400%</span> weapon damage as Arcane to all enemies near the impact location.</p><p>Arcane Torrent damage is increased by <span class=\"d3-color-green\">305%</span> weapon damage every second, up to a maximum total of <span class=\"d3-color-green\">1010%</span> weapon damage as Arcane.</p> <p class=\"special\">Secondary</p> <p class=\"subtle\">Unlocked at level <em>12</em>.</p> </div> </div>",
  },
  archon: {
    a: "<p>Increase the damage of all Archon abilities by <span class=\"d3-color-green\">50%</span>.</p> <p class=\"subtle\">Unlocked at level <em>60</em>.</p>",
    b: "<p>Archon form can cast a <span class=\"d3-color-green\">Slow Time</span> that follows you and your Arcane Blast and Arcane Strike abilities Freeze enemies for <span class=\"d3-color-green\">1</span> second.</p><p>Archon abilities deal <span class=\"d3-color-green\">Cold</span> damage instead of Arcane.</p> <p class=\"subtle\">Unlocked at level <em>52</em>.</p>",
    c: "<p>Archon form can cast <span class=\"d3-color-green\">Teleport</span> with a <span class=\"d3-color-green\">2</span> second cooldown.</p> <p class=\"subtle\">Unlocked at level <em>40</em>.</p>",
    d: "<p>Decrease the cooldown of Archon to <span class=\"d3-color-green\">100</span> seconds.</p><p>Archon abilities deal <span class=\"d3-color-green\">Lightning</span> damage instead of Arcane.</p> <p class=\"subtle\">Unlocked at level <em>46</em>.</p>",
    e: "<p>An explosion erupts around you when you transform, dealing <span class=\"d3-color-green\">3680%</span> weapon damage as Fire to all enemies within <span class=\"d3-color-green\">15</span> yards.</p><p>Archon abilities deal <span class=\"d3-color-green\">Fire</span> damage instead of Arcane.</p> <p class=\"subtle\">Unlocked at level <em>36</em>.</p>",
    elements: {
      a: "arc",
      b: "col",
      c: "arc",
      d: "lit",
      e: "fir",
      x: "arc",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/wizard_archon.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">120</span> seconds</p><p>Transform into a being of pure arcane energy for <span class=\"d3-color-green\">20</span> seconds. While in Archon form, your normal abilities are replaced by powerful Archon abilities, your damage is increased by <span class=\"d3-color-green\">30%</span>, and your Armor and resistances are increased by <span class=\"d3-color-green\">150%</span>.</p><p>Each enemy killed while in Archon form increases your damage by <span class=\"d3-color-green\">6%</span> for the remaining duration of Archon.</p> <p class=\"special\">Mastery</p> <p class=\"subtle\">Unlocked at level <em>30</em>.</p> </div> </div>",
  },
  blackhole: {
    a: "<p>Increases the Black Hole radius to <span class=\"d3-color-green\">20</span> yards and damage to <span class=\"d3-color-green\">1290%</span> weapon damage as Lightning over <span class=\"d3-color-green\">2</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>62</em>.</p>",
    b: "<p>The Black Hole also absorbs enemy projectiles and objects from Elite monster affixes within <span class=\"d3-color-green\">15</span> yards.</p> <p class=\"subtle\">Unlocked at level <em>65</em>.</p>",
    c: "<p>Conjure a Black Hole at the target location that draws enemies to it and deals <span class=\"d3-color-green\">700%</span> weapon damage as Fire over <span class=\"d3-color-green\">2</span> seconds to all enemies within <span class=\"d3-color-green\">15</span> yards.</p><p>After the Black Hole disappears, an explosion occurs that deals <span class=\"d3-color-green\">725%</span> weapon damage as Fire to enemies within <span class=\"d3-color-green\">15</span> yards.</p> <p class=\"subtle\">Unlocked at level <em>67</em>.</p>",
    d: "<p>Enemies hit by Black Hole deal <span class=\"d3-color-green\">10%</span> reduced damage for <span class=\"d3-color-green\">5</span> seconds. Each enemy hit by Black Hole grants you <span class=\"d3-color-green\">3%</span> increased damage for <span class=\"d3-color-green\">5</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>69</em>.</p>",
    e: "<p>Each enemy hit increases the damage of your Cold spells by <span class=\"d3-color-green\">3%</span> for <span class=\"d3-color-green\">10</span> seconds.</p><p>Black Hole's damage turns into Cold.</p> <p class=\"subtle\">Unlocked at level <em>63</em>.</p>",
    elements: {
      a: "lit",
      b: "arc",
      c: "fir",
      d: "arc",
      e: "col",
      x: "arc",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/x1_wizard_wormhole.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">20</span> Arcane Power<br/><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">12</span> seconds</p><p>Conjure a Black Hole at the target location that draws enemies to it and deals <span class=\"d3-color-green\">700%</span> weapon damage as Arcane over <span class=\"d3-color-green\">2</span> seconds to all enemies within <span class=\"d3-color-green\">15</span> yards.</p> <p class=\"special\">Mastery</p> <p class=\"subtle\">Unlocked at level <em>61</em>.</p> </div> </div>",
  },
  blizzard: {
    a: "<p>Increase the duration and damage of Blizzard to deal <span class=\"d3-color-green\">1810%</span> weapon damage as Cold over <span class=\"d3-color-green\">8</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>60</em>.</p>",
    b: "<p>Increase the area of effect of Blizzard to a <span class=\"d3-color-green\">30</span> yard radius.</p><p>Blizzard's damage turns into Fire.</p> <p class=\"subtle\">Unlocked at level <em>54</em>.</p>",
    c: "<p>Enemies affected by Blizzard take <span class=\"d3-color-green\">15%</span> increased damage from Lightning.</p> <p class=\"subtle\">Unlocked at level <em>35</em>.</p>",
    d: "<p>Reduce the casting cost of Blizzard to <span class=\"d3-color-green\">10</span> Arcane Power.</p> <p class=\"subtle\">Unlocked at level <em>47</em>.</p>",
    e: "<p>Enemies caught in the Blizzard have a <span class=\"d3-color-green\">100%</span> chance to be Frozen for <span class=\"d3-color-green\">2.5</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>42</em>.</p>",
    elements: {
      a: "col",
      b: "fir",
      c: "lit",
      d: "col",
      e: "col",
      x: "col",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/wizard_blizzard.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">40</span> Arcane Power</p><p>Call down shards of ice that deal <span class=\"d3-color-green\">1075%</span> weapon damage as Cold over <span class=\"d3-color-green\">6</span> seconds to enemies in a <span class=\"d3-color-green\">12</span> yard radius. Multiple casts in the same area from the same caster do not stack.</p> <p class=\"special\">Force</p> <p class=\"subtle\">Unlocked at level <em>27</em>.</p> </div> </div>",
  },
  diamondskin: {
    a: "<p>Increases your movement speed by <span class=\"d3-color-green\">30%</span> while Diamond Skin is active.</p> <p class=\"subtle\">Unlocked at level <em>32</em>.</p>",
    b: "<p>Increase the duration of Diamond Skin to <span class=\"d3-color-green\">6</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>44</em>.</p>",
    c: "<p>Increase the maximum amount of damage absorbed to <span class=\"d3-color-green\">80%</span> of your Life.</p> <p class=\"subtle\">Unlocked at level <em>14</em>.</p>",
    d: "<p>Reduce the Arcane Power cost of all skills by <span class=\"d3-color-green\">9</span> while Diamond Skin is active.</p> <p class=\"subtle\">Unlocked at level <em>20</em>.</p>",
    e: "<p>When Diamond Skin fades, diamond shards explode in all directions dealing <span class=\"d3-color-green\">863%</span> weapon damage as Arcane to nearby enemies.</p> <p class=\"subtle\">Unlocked at level <em>56</em>.</p>",
    elements: {
      a: "arc",
      b: "arc",
      c: "arc",
      d: "arc",
      e: "arc",
      x: "arc",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/wizard_diamondskin.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">15</span> seconds</p><p>Transform your skin to diamond for <span class=\"d3-color-green\">3</span> seconds, absorbing up to <span class=\"d3-color-green\">40%</span> of your Life in damage from incoming attacks.</p> <p class=\"special\">Defensive</p> <p class=\"subtle\">Unlocked at level <em>8</em>.</p> </div> </div>",
  },
  disintegrate: {
    a: "<p>Enemies hit by Disintegrate take <span class=\"d3-color-green\">15%</span> increased damage from Arcane for <span class=\"d3-color-green\">4</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>59</em>.</p>",
    b: "<p>Increase the width of the beam allowing it to hit more enemies.</p><p>Disintegrate's damage turns into Fire.</p> <p class=\"subtle\">Unlocked at level <em>26</em>.</p>",
    c: "<p>The beam fractures into a short-ranged cone that deals <span class=\"d3-color-green\">435%</span> weapon damage as Arcane.</p><p>Disintegrate damage is increased by <span class=\"d3-color-green\">340%</span> weapon damage every second, up to a maximum total of <span class=\"d3-color-green\">1115%</span> weapon damage as Arcane.</p> <p class=\"subtle\">Unlocked at level <em>39</em>.</p>",
    d: "<p>While channeling the beam you become charged with energy and discharge at nearby enemies dealing <span class=\"d3-color-green\">115%</span> weapon damage as Arcane.</p> <p class=\"subtle\">Unlocked at level <em>48</em>.</p>",
    e: "<p>Enemies killed by the beam have a <span class=\"d3-color-green\">35%</span> chance to explode causing <span class=\"d3-color-green\">750%</span> weapon damage as Arcane to all enemies within <span class=\"d3-color-green\">8</span> yards.</p> <p class=\"subtle\">Unlocked at level <em>30</em>.</p>",
    elements: {
      a: "arc",
      b: "fir",
      c: "arc",
      d: "arc",
      e: "arc",
      x: "arc",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/wizard_disintegrate.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">18</span> Arcane Power</p><p>Channel a beam of pure energy, dealing <span class=\"d3-color-green\">390%</span> weapon damage as Arcane.</p><p>Disintegrate damage is increased by <span class=\"d3-color-green\">250%</span> weapon damage every second, up to a maximum total of <span class=\"d3-color-green\">890%</span> weapon damage as Arcane.</p> <p class=\"special\">Secondary</p> <p class=\"subtle\">Unlocked at level <em>21</em>.</p> </div> </div>",
  },
  electrocute: {
    a: "<p>Create streaks of lightning that pierce through enemies for <span class=\"d3-color-green\">140%</span> weapon damage as Lightning.</p> <p class=\"subtle\">Unlocked at level <em>36</em>.</p>",
    b: "<p>Increase the maximum number of enemies that can be electrocuted to <span class=\"d3-color-green\">10</span>.</p> <p class=\"subtle\">Unlocked at level <em>22</em>.</p>",
    c: "<p>Blast a cone of lightning that deals <span class=\"d3-color-green\">310%</span> weapon damage as Lightning to all affected enemies.</p> <p class=\"subtle\">Unlocked at level <em>59</em>.</p>",
    d: "<p>Gain <span class=\"d3-color-green\">1</span> Arcane Power for each enemy hit.</p> <p class=\"subtle\">Unlocked at level <em>44</em>.</p>",
    e: "<p>Critical Hits release <span class=\"d3-color-green\">4</span> charged bolts in random directions, dealing <span class=\"d3-color-green\">44%</span> weapon damage as Fire to any enemies hit.</p> <p class=\"subtle\">Unlocked at level <em>29</em>.</p>",
    elements: {
      a: "lit",
      b: "lit",
      c: "lit",
      d: "lit",
      e: "fir",
      x: "lit",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/wizard_electrocute.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">This is a Signature spell. Signature spells are free to cast.</span></p><p>Lightning arcs from your fingertips, dealing <span class=\"d3-color-green\">138%</span> weapon damage as Lightning. The lightning can jump, hitting up to <span class=\"d3-color-green\">2</span> additional enemies.</p> <p class=\"special\">Primary</p> <p class=\"subtle\">Unlocked at level <em>15</em>.</p> </div> </div>",
  },
  energyarmor: {
    a: "<p>Energy Armor also increases your resistance to all damage types <span class=\"d3-color-green\">25%</span>.</p> <p class=\"subtle\">Unlocked at level <em>60</em>.</p>",
    b: "<p>Rather than decreasing your maximum Arcane Power, Energy Armor increases it by <span class=\"d3-color-green\">20</span>.</p> <p class=\"subtle\">Unlocked at level <em>48</em>.</p>",
    c: "<p>Incoming attacks that would deal more than <span class=\"d3-color-green\">35%</span> of your maximum Life are reduced to deal <span class=\"d3-color-green\">35%</span> of your maximum Life instead.</p><p>The amount absorbed cannot exceed <span class=\"d3-color-green\">100%</span> of your maximum Life.</p> <p class=\"subtle\">Unlocked at level <em>54</em>.</p>",
    d: "<p>You have a chance to gain <span class=\"d3-color-green\">4</span> Arcane Power when you are hit by a ranged or melee attack.</p> <p class=\"subtle\">Unlocked at level <em>32</em>.</p>",
    e: "<p>Energy Armor also increases your Critical Hit Chance by <span class=\"d3-color-green\">5%</span>.</p> <p class=\"subtle\">Unlocked at level <em>41</em>.</p>",
    elements: {
      a: "arc",
      b: "arc",
      c: "arc",
      d: "arc",
      e: "arc",
      x: "arc",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/wizard_energyarmor.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">25</span> Arcane Power</p><p>Focus your energies, increasing your Armor by <span class=\"d3-color-green\">35%</span> but decreasing your maximum Arcane Power by <span class=\"d3-color-green\">20</span>. Lasts <span class=\"d3-color-green\">10</span> minutes.</p><p><span class=\"d3-color-yellow\">Only one Armor may be active at a time.</span></p> <p class=\"special\">Conjuration</p> <p class=\"subtle\">Unlocked at level <em>28</em>.</p> </div> </div>",
  },
  energytwister: {
    a: "<p>Enemies hit by Energy Twister take <span class=\"d3-color-green\">15%</span> increased damage from Fire for <span class=\"d3-color-green\">4</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>24</em>.</p>",
    b: "<p>When two Energy Twisters collide, they merge into a tornado with increased area of effect that causes <span class=\"d3-color-green\">3200%</span> weapon damage as Arcane over <span class=\"d3-color-green\">6</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>36</em>.</p>",
    c: "<p>Each cast of Energy Twister grants you a Lightning Charge. You can store up to <span class=\"d3-color-green\">3</span> Lightning Charges at a time. Casting a Signature spell releases all Lightning Charges as a bolt of Lightning that deals <span class=\"d3-color-green\">196%</span> weapon damage as Lightning per Lightning Charge.</p><p>Energy Twister's damage turns into Lightning.</p><p>The following skills are Signature spells:<br/><span class=\"tooltip-icon-bullet\"></span> Magic Missile<br/><span class=\"tooltip-icon-bullet\"></span> Shock Pulse<br/><span class=\"tooltip-icon-bullet\"></span> Spectral Blade<br/><span class=\"tooltip-icon-bullet\"></span> Electrocute</p> <p class=\"subtle\">Unlocked at level <em>52</em>.</p>",
    d: "<p>Reduce the casting cost of Energy Twister to <span class=\"d3-color-green\">25</span> Arcane Power.</p><p>Energy Twister's damage turns into Cold.</p> <p class=\"subtle\">Unlocked at level <em>19</em>.</p>",
    e: "<p>Energy Twister no longer travels but spins in place, dealing <span class=\"d3-color-green\">835%</span> weapon damage as Arcane over <span class=\"d3-color-green\">6</span> seconds to everything caught in it.</p> <p class=\"subtle\">Unlocked at level <em>41</em>.</p>",
    elements: {
      a: "fir",
      b: "arc",
      c: "lit",
      d: "col",
      e: "arc",
      x: "arc",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/wizard_energytwister.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">35</span> Arcane Power</p><p>Unleash a twister of pure energy that deals <span class=\"d3-color-green\">1525%</span> weapon damage as Arcane over <span class=\"d3-color-green\">6</span> seconds to everything in its path.</p> <p class=\"special\">Force</p> <p class=\"subtle\">Unlocked at level <em>13</em>.</p> </div> </div>",
  },
  explosiveblast: {
    a: "<p>Immediately release the energy of Explosive Blast for <span class=\"d3-color-green\">909%</span> weapon damage as Fire.</p> <p class=\"subtle\">Unlocked at level <em>39</em>.</p>",
    b: "<p>Release an enormous Explosive Blast that deals <span class=\"d3-color-green\">990%</span> weapon damage as Cold to all enemies within <span class=\"d3-color-green\">18</span> yards.</p> <p class=\"subtle\">Unlocked at level <em>50</em>.</p>",
    c: "<p>Reduce the cooldown of Explosive Blast to <span class=\"d3-color-green\">3</span> seconds.</p><p>Explosive Blast's damage turns into Lightning.</p> <p class=\"subtle\">Unlocked at level <em>29</em>.</p>",
    d: "<p>Increases the damage of Explosive Blast to <span class=\"d3-color-green\">1485%</span>.</p> <p class=\"subtle\">Unlocked at level <em>24</em>.</p>",
    e: "<p>Instead of a single explosion, release a chain of <span class=\"d3-color-green\">3</span> consecutive explosions, each dealing <span class=\"d3-color-green\">520%</span> weapon damage as Fire.</p> <p class=\"subtle\">Unlocked at level <em>56</em>.</p>",
    elements: {
      a: "fir",
      b: "col",
      c: "lit",
      d: "arc",
      e: "fir",
      x: "arc",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/wizard_explosiveblast.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">20</span> Arcane Power<br/><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">6</span> seconds</p><p>Gather an infusion of energy around you that explodes after <span class=\"d3-color-green\">1.5</span> seconds for <span class=\"d3-color-green\">945%</span> weapon damage as Arcane to all enemies within <span class=\"d3-color-green\">12</span> yards.</p> <p class=\"special\">Mastery</p> <p class=\"subtle\">Unlocked at level <em>19</em>.</p> </div> </div>",
  },
  familiar: {
    a: "<p>Summon a fiery Familiar that grants you <span class=\"d3-color-green\">10%</span> increased damage.</p> <p class=\"subtle\">Unlocked at level <em>30</em>.</p>",
    b: "<p>The Familiar's projectiles explode on impact, dealing <span class=\"d3-color-green\">240%</span> weapon damage as Arcane to all enemies within <span class=\"d3-color-green\">6</span> yards.</p> <p class=\"subtle\">Unlocked at level <em>57</em>.</p>",
    c: "<p>The Familiar's projectiles have a <span class=\"d3-color-green\">35%</span> chance to Freeze the enemy for <span class=\"d3-color-green\">1</span> second.</p> <p class=\"subtle\">Unlocked at level <em>40</em>.</p>",
    d: "<p>While the Familiar is active, you regenerate <span class=\"d3-color-green\">4.5</span> Arcane Power every second.</p> <p class=\"subtle\">Unlocked at level <em>50</em>.</p>",
    e: "<p>Summon a protective Familiar. When you are below <span class=\"d3-color-green\">50%</span> Life the Familiar will absorb damage from <span class=\"d3-color-green\">1</span> attack every <span class=\"d3-color-green\">6</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>44</em>.</p>",
    elements: {
      a: "fir",
      b: "arc",
      c: "col",
      d: "arc",
      e: "arc",
      x: "arc",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/wizard_familiar.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">20</span> Arcane Power</p><p>Summon a Familiar that attacks your enemies for <span class=\"d3-color-green\">240%</span> weapon damage as Arcane. This companion cannot be targeted or damaged by enemies. Lasts <span class=\"d3-color-green\">10</span> minutes.</p> <p class=\"special\">Conjuration</p> <p class=\"subtle\">Unlocked at level <em>22</em>.</p> </div> </div>",
  },
  frostnova: {
    a: "<p>Enemies take <span class=\"d3-color-green\">33%</span> more damage while frozen or chilled by Frost Nova.</p> <p class=\"subtle\">Unlocked at level <em>51</em>.</p>",
    b: "<p>A frozen enemy that is killed has a <span class=\"d3-color-green\">100%</span> chance of releasing another Frost Nova.</p> <p class=\"subtle\">Unlocked at level <em>12</em>.</p>",
    c: "<p>Frost Nova no longer freezes enemies, but instead leaves behind a mist of frost that deals <span class=\"d3-color-green\">915%</span> weapon damage as Cold over <span class=\"d3-color-green\">8</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>28</em>.</p>",
    d: "<p>Reduce the cooldown to <span class=\"d3-color-green\">7.5</span> seconds and increase the Freeze duration to <span class=\"d3-color-green\">3</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>18</em>.</p>",
    e: "<p>Gain a <span class=\"d3-color-green\">10%</span> bonus to Critical Hit Chance for <span class=\"d3-color-green\">11</span> seconds if Frost Nova hits <span class=\"d3-color-green\">5</span> or more enemies.</p> <p class=\"subtle\">Unlocked at level <em>41</em>.</p>",
    elements: {
      a: "col",
      b: "col",
      c: "col",
      d: "col",
      e: "col",
      x: "col",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/wizard_frostnova.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">11</span> seconds</p><p>Blast nearby enemies with an explosion of ice and freeze them for <span class=\"d3-color-green\">2</span> seconds.</p> <p class=\"special\">Defensive</p> <p class=\"subtle\">Unlocked at level <em>4</em>.</p> </div> </div>",
  },
  hydra: {
    a: "<p>Summon a Frost Hydra that breathes a short range cone of frost, causing <span class=\"d3-color-green\">255%</span> weapon damage as Cold to all enemies in the cone.</p> <p class=\"subtle\">Unlocked at level <em>46</em>.</p>",
    b: "<p>Summon a Lightning Hydra that electrocutes enemies for <span class=\"d3-color-green\">255%</span> weapon damage as Lightning.</p> <p class=\"subtle\">Unlocked at level <em>33</em>.</p>",
    c: "<p>Summon a Blazing Hydra that spits bolts of Fire that burn enemies near the point of impact, dealing <span class=\"d3-color-green\">155%</span> weapon damage as Fire over <span class=\"d3-color-green\">3</span> seconds. Burn damage can stack multiple times on the same enemy.</p> <p class=\"subtle\">Unlocked at level <em>38</em>.</p>",
    d: "<p>Summon a Mammoth Hydra that breathes a river of flame at nearby enemies, dealing <span class=\"d3-color-green\">330%</span> weapon damage per second as Fire to enemies caught on the burning ground.</p> <p class=\"subtle\">Unlocked at level <em>56</em>.</p>",
    e: "<p>Summon an Arcane Hydra that spits Arcane Orbs that explode on impact, dealing <span class=\"d3-color-green\">205%</span> weapon damage as Arcane to enemies near the explosion.</p> <p class=\"subtle\">Unlocked at level <em>26</em>.</p>",
    elements: {
      a: "col",
      b: "lit",
      c: "fir",
      d: "fir",
      e: "arc",
      x: "fir",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/wizard_hydra.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">15</span> Arcane Power</p><p>Summon a multi-headed Hydra for <span class=\"d3-color-green\">15</span> seconds that attacks enemies with bolts of fire dealing <span class=\"d3-color-green\">165%</span> weapon damage as Fire.</p><p><span class=\"d3-color-yellow\">Only one Hydra may be active at a time.</span></p> <p class=\"special\">Force</p> <p class=\"subtle\">Unlocked at level <em>21</em>.</p> </div> </div>",
  },
  icearmor: {
    a: "<p>Melee attackers also take <span class=\"d3-color-green\">189%</span> weapon damage as Cold.</p> <p class=\"subtle\">Unlocked at level <em>42</em>.</p>",
    b: "<p>Lower the temperature of the air around you. Nearby enemies are chilled, slowing their movement speed by <span class=\"d3-color-green\">80%</span>.</p> <p class=\"subtle\">Unlocked at level <em>21</em>.</p>",
    c: "<p>A whirling storm of ice builds around you, dealing <span class=\"d3-color-green\">80%</span> weapon damage as Cold every second.</p> <p class=\"subtle\">Unlocked at level <em>53</em>.</p>",
    d: "<p>When you are struck by a melee attack, your Armor is increased by <span class=\"d3-color-green\">20%</span> for <span class=\"d3-color-green\">30</span> seconds. This effect stacks up to <span class=\"d3-color-green\">3</span> times.</p> <p class=\"subtle\">Unlocked at level <em>31</em>.</p>",
    e: "<p>Melee attacks have a <span class=\"d3-color-green\">40%</span> chance to create a Frost Nova centered on the attacker, dealing <span class=\"d3-color-green\">75%</span> weapon damage as Cold.</p> <p class=\"subtle\">Unlocked at level <em>49</em>.</p>",
    elements: {
      a: "col",
      b: "col",
      c: "col",
      d: "col",
      e: "col",
      x: "col",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/wizard_icearmor.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">25</span> Arcane Power</p><p>Surround yourself in a barrier of ice that reduces damage from melee attacks by <span class=\"d3-color-green\">12%</span>. Melee attackers are either Chilled or Frozen for <span class=\"d3-color-green\">3</span> seconds. Lasts <span class=\"d3-color-green\">10</span> minutes.</p><p><span class=\"d3-color-yellow\">Only one Armor may be active at a time.</span></p> <p class=\"special\">Conjuration</p> <p class=\"subtle\">Unlocked at level <em>14</em>.</p> </div> </div>",
  },
  magicmissile: {
    a: "<p>Increase the damage of Magic Missile to <span class=\"d3-color-green\">325%</span> weapon damage as Arcane.</p> <p class=\"subtle\">Unlocked at level <em>6</em>.</p>",
    b: "<p>Fire <span class=\"d3-color-green\">3</span> missiles that each deal <span class=\"d3-color-green\">80%</span> weapon damage as Arcane.</p> <p class=\"subtle\">Unlocked at level <em>31</em>.</p>",
    c: "<p>The missile pierces through enemies and causes them to burn for <span class=\"d3-color-green\">130%</span> weapon damage as Fire over <span class=\"d3-color-green\">3</span> seconds.</p><p>Burn damage stacks up to <span class=\"d3-color-green\">3</span> times and any Fire damage taken from your other spells refresh all stacks to their maximum duration.</p> <p class=\"subtle\">Unlocked at level <em>52</em>.</p>",
    d: "<p>Cast out a shard of ice that explodes on impact, causing enemies within <span class=\"d3-color-green\">4.5</span> yards to take <span class=\"d3-color-green\">175%</span> weapon damage as Cold and be Frozen for <span class=\"d3-color-green\">1</span> second.</p><p>Enemies cannot be Frozen by Glacial Spike more than once every <span class=\"d3-color-green\">5</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>13</em>.</p>",
    e: "<p>Missiles track the nearest enemy. Missile damage is increased to <span class=\"d3-color-green\">285%</span> weapon damage as Arcane.</p> <p class=\"subtle\">Unlocked at level <em>42</em>.</p>",
    elements: {
      a: "arc",
      b: "arc",
      c: "fir",
      d: "col",
      e: "arc",
      x: "arc",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/wizard_magicmissile.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">This is a Signature spell. Signature spells are free to cast.</span></p><p>Launch a missile of magic energy, dealing <span class=\"d3-color-green\">230%</span> weapon damage as Arcane.</p> <p class=\"special\">Primary</p> <p class=\"subtle\">Unlocked at level <em>1</em>.</p> </div> </div>",
  },
  magicweapon: {
    a: "<p>Attacks have a chance to burn enemies, dealing <span class=\"d3-color-green\">300%</span> weapon damage as Fire over <span class=\"d3-color-green\">3</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>46</em>.</p>",
    b: "<p>Attacks have a chance to cause lightning to arc to <span class=\"d3-color-green\">3</span> nearby enemies, dealing <span class=\"d3-color-green\">61%</span> weapon damage as Lightning.</p> <p class=\"subtle\">Unlocked at level <em>27</em>.</p>",
    c: "<p>Increase the damage bonus of Magic Weapon to <span class=\"d3-color-green\">20%</span> damage.</p> <p class=\"subtle\">Unlocked at level <em>35</em>.</p>",
    d: "<p>Enemies hit by your attacks restore up to <span class=\"d3-color-green\">3</span> Arcane Power.</p> <p class=\"subtle\">Unlocked at level <em>38</em>.</p>",
    e: "<p>When you perform an attack, gain a protective shield for <span class=\"d3-color-green\">3</span> seconds that absorbs <span class=\"d3-color-green\">4%</span> of your Life in damage.</p> <p class=\"subtle\">Unlocked at level <em>55</em>.</p>",
    elements: {
      a: "fir",
      b: "lit",
      c: "arc",
      d: "arc",
      e: "arc",
      x: "arc",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/wizard_magicweapon.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">25</span> Arcane Power</p><p>Imbue your weapon with magical energy, granting it <span class=\"d3-color-green\">10%</span> increased damage. Lasts <span class=\"d3-color-green\">10</span> minutes.</p> <p>Requires <span class=\"value\">Weapon</span></p> <p class=\"special\">Conjuration</p> <p class=\"subtle\">Unlocked at level <em>20</em>.</p> </div> </div>",
  },
  meteor: {
    a: "<p>Greatly increases the size and increases the damage of the Meteor impact to <span class=\"d3-color-green\">1648%</span> weapon damage as Fire and the molten fire to <span class=\"d3-color-green\">625%</span> weapon damage as Fire over <span class=\"d3-color-green\">3</span> seconds.</p><p>Adds a <span class=\"d3-color-green\">15</span> second cooldown.</p> <p class=\"subtle\">Unlocked at level <em>58</em>.</p>",
    b: "<p>Unleash a volley of <span class=\"d3-color-green\">7</span> small Meteors that each strike for <span class=\"d3-color-green\">277%</span> weapon damage as Fire.</p> <p class=\"subtle\">Unlocked at level <em>48</em>.</p>",
    c: "<p>Summon a Comet that deals <span class=\"d3-color-green\">740%</span> weapon damage as Cold and freezes chilled enemies for <span class=\"d3-color-green\">1</span> second upon impact.</p><p>The impact site is covered in an icy mist that deals <span class=\"d3-color-green\">235%</span> weapon damage as Cold over <span class=\"d3-color-green\">3</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>43</em>.</p>",
    d: "<p>Expend all remaining Arcane Power. Each point of extra Arcane Power spent increases the impact damage of Meteor by <span class=\"d3-color-green\">20%</span> weapon damage as Arcane.</p> <p class=\"subtle\">Unlocked at level <em>34</em>.</p>",
    e: "<p>Removes the delay before Meteor comes crashing down.</p><p>Meteor's damage turns into Lightning.</p> <p class=\"subtle\">Unlocked at level <em>29</em>.</p>",
    elements: {
      a: "fir",
      b: "fir",
      c: "col",
      d: "arc",
      e: "lit",
      x: "fir",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/wizard_meteor.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">40</span> Arcane Power</p><p>Summon an immense Meteor that plummets from the sky, crashing into enemies for <span class=\"d3-color-green\">740%</span> weapon damage as Fire. The ground it hits is scorched with molten fire that deals <span class=\"d3-color-green\">235%</span> weapon damage as Fire over <span class=\"d3-color-green\">3</span> seconds.</p> <p class=\"special\">Force</p> <p class=\"subtle\">Unlocked at level <em>25</em>.</p> </div> </div>",
  },
  mirrorimage: {
    a: "<p>Spells cast by your Mirror Images will deal <span class=\"d3-color-green\">20%</span> of the damage of your own spells.</p> <p class=\"subtle\">Unlocked at level <em>58</em>.</p>",
    b: "<p>Summon <span class=\"d3-color-green\">4</span> Mirror Images that taunt nearby enemies for <span class=\"d3-color-green\">1</span> second and each have <span class=\"d3-color-green\">50%</span> of your Life.</p> <p class=\"subtle\">Unlocked at level <em>37</em>.</p>",
    c: "<p>Increase the Life of your Mirror Images to <span class=\"d3-color-green\">200%</span> of your own.</p> <p class=\"subtle\">Unlocked at level <em>31</em>.</p>",
    d: "<p>Increase the duration of your Mirror Images to <span class=\"d3-color-green\">10</span> seconds and their Life to <span class=\"d3-color-green\">100%</span> of your Life.</p> <p class=\"subtle\">Unlocked at level <em>51</em>.</p>",
    e: "<p>When a Mirror Image is destroyed, it explodes, dealing <span class=\"d3-color-green\">309%</span> weapon damage as Arcane with a <span class=\"d3-color-green\">50%</span> chance to Stun for <span class=\"d3-color-green\">2</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>45</em>.</p>",
    elements: {
      a: "arc",
      b: "arc",
      c: "arc",
      d: "arc",
      e: "arc",
      x: "arc",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/wizard_mirrorimage.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">15</span> seconds</p><p>Summon <span class=\"d3-color-green\">2</span> illusionary duplicates of yourself that taunt nearby enemies for <span class=\"d3-color-green\">1</span> second, last for <span class=\"d3-color-green\">7</span> seconds and have <span class=\"d3-color-green\">50%</span> of your Life.</p><p>Spells cast by your Mirror Images will deal <span class=\"d3-color-green\">10%</span> of the damage of your own spells.</p> <p class=\"special\">Mastery</p> <p class=\"subtle\">Unlocked at level <em>25</em>.</p> </div> </div>",
  },
  rayoffrost: {
    a: "<p>Enemies hit by Ray of Frost take <span class=\"d3-color-green\">15%</span> increased damage from Cold for <span class=\"d3-color-green\">4</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>53</em>.</p>",
    b: "<p>Create a swirling storm around you that grows up to a <span class=\"d3-color-green\">22</span> yard radius, dealing <span class=\"d3-color-green\">300%</span> weapon damage as Cold to all enemies caught within it.</p><p>Ray of Frost damage is increased by <span class=\"d3-color-green\">220%</span> weapon damage every second, up to a maximum total of <span class=\"d3-color-green\">740%</span> weapon damage as Cold.</p> <p class=\"subtle\">Unlocked at level <em>38</em>.</p>",
    c: "<p>Ray of Frost has a <span class=\"d3-color-green\">10%</span> chance to Freeze enemies for <span class=\"d3-color-green\">1</span> second and increases the Slow amount to <span class=\"d3-color-green\">80%</span> for <span class=\"d3-color-green\">3</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>15</em>.</p>",
    d: "<p>Reduce channeling cost to <span class=\"d3-color-green\">11</span> Arcane Power.</p> <p class=\"subtle\">Unlocked at level <em>7</em>.</p>",
    e: "<p>Enemies killed by Ray of Frost leave behind a patch of ice that deals <span class=\"d3-color-green\">1625%</span> weapon damage as Cold to enemies moving through it over <span class=\"d3-color-green\">3</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>28</em>.</p>",
    elements: {
      a: "col",
      b: "col",
      c: "col",
      d: "col",
      e: "col",
      x: "col",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/wizard_rayoffrost.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">16</span> Arcane Power</p><p>Project a beam of frozen ice that blasts enemies within <span class=\"d3-color-green\">5</span> yards of the first enemy hit for <span class=\"d3-color-green\">430%</span> weapon damage as Cold and Slows their movement by <span class=\"d3-color-green\">60%</span> for <span class=\"d3-color-green\">3</span> seconds.</p><p>Ray of Frost damage is increased by <span class=\"d3-color-green\">405%</span> weapon damage every second, up to a maximum total of <span class=\"d3-color-green\">1240%</span> weapon damage as Cold.</p> <p class=\"special\">Secondary</p> <p class=\"subtle\">Unlocked at level <em>2</em>.</p> </div> </div>",
  },
  shockpulse: {
    a: "<p>Cast <span class=\"d3-color-green\">3</span> bolts of fire that each deal <span class=\"d3-color-green\">274%</span> weapon damage as Fire.</p> <p class=\"subtle\">Unlocked at level <em>18</em>.</p>",
    b: "<p>Conjure a being of lightning that drifts forward, electrocuting nearby enemies for <span class=\"d3-color-green\">165%</span> weapon damage as Lightning.</p> <p class=\"subtle\">Unlocked at level <em>54</em>.</p>",
    c: "<p>Merge the bolts in a a single giant orb that oscillates forward dealing <span class=\"d3-color-green\">214%</span> weapon damage as Lightning to everything it hits.</p> <p class=\"subtle\">Unlocked at level <em>33</em>.</p>",
    d: "<p>Gain <span class=\"d3-color-green\">2</span> Arcane Power for each enemy hit.</p><p>Shock Pulse's damage turns into Arcane.</p> <p class=\"subtle\">Unlocked at level <em>47</em>.</p>",
    e: "<p>Slain enemies explode, dealing <span class=\"d3-color-green\">184%</span> weapon damage as Cold to every enemy within <span class=\"d3-color-green\">10</span> yards.</p><p>Shock Pulse's damage turns into Cold.</p> <p class=\"subtle\">Unlocked at level <em>9</em>.</p>",
    elements: {
      a: "fir",
      b: "lit",
      c: "lit",
      d: "arc",
      e: "col",
      x: "lit",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/wizard_shockpulse.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">This is a Signature spell. Signature spells are free to cast.</span></p><p>Release a medium range pulse of <span class=\"d3-color-green\">3</span> unpredictable charges of electricity that deal <span class=\"d3-color-green\">194%</span> weapon damage as Lightning.</p> <p class=\"special\">Primary</p> <p class=\"subtle\">Unlocked at level <em>3</em>.</p> </div> </div>",
  },
  slowtime: {
    a: "<p>Enemies caught in the bubble of warped time take <span class=\"d3-color-green\">15%</span> more damage.</p> <p class=\"subtle\">Unlocked at level <em>39</em>.</p>",
    b: "<p>Enemies that enter or leave the Slow Time area are stunned for <span class=\"d3-color-green\">5</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>47</em>.</p>",
    c: "<p>Increase the potency of the movement speed reduction to <span class=\"d3-color-green\">80%</span> and reduces the cooldown to <span class=\"d3-color-green\">12</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>23</em>.</p>",
    d: "<p>Enemies caught by Slow Time deal <span class=\"d3-color-green\">25%</span> less damage.</p> <p class=\"subtle\">Unlocked at level <em>29</em>.</p>",
    e: "<p>Time is sped up for any allies standing in the area, increasing their attack speed by <span class=\"d3-color-green\">10%</span>.</p> <p class=\"subtle\">Unlocked at level <em>53</em>.</p>",
    elements: {
      a: "arc",
      b: "arc",
      c: "arc",
      d: "arc",
      e: "arc",
      x: "arc",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/wizard_slowtime.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">15</span> seconds</p><p>Invoke a bubble of warped time and space at your target location up to <span class=\"d3-color-green\">60</span> yards away for <span class=\"d3-color-green\">15</span> seconds, reducing enemy attack speed by <span class=\"d3-color-green\">20%</span> and movement speed by <span class=\"d3-color-green\">60%</span>. This bubble also slows the speed of enemy projectiles by <span class=\"d3-color-green\">90%</span>.</p> <p class=\"special\">Defensive</p> <p class=\"subtle\">Unlocked at level <em>16</em>.</p> </div> </div>",
  },
  spectralblade: {
    a: "<p>Each enemy hit increases the damage of your Fire spells by <span class=\"d3-color-green\">1%</span>, up to a maximum of <span class=\"d3-color-green\">30%</span>, for <span class=\"d3-color-green\">5</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>19</em>.</p>",
    b: "<p>Extend the reach of Spectral Blade to <span class=\"d3-color-green\">20</span> yards and increase its damage to <span class=\"d3-color-green\">231%</span> weapon damage as Lightning.</p> <p class=\"subtle\">Unlocked at level <em>35</em>.</p>",
    c: "<p>Chilled enemies have a <span class=\"d3-color-green\">5%</span> chance to be Frozen and Frozen enemies have a <span class=\"d3-color-green\">5%</span> increased chance to be critically hit by Spectral Blade.</p> <p class=\"subtle\">Unlocked at level <em>57</em>.</p>",
    d: "<p>Gain <span class=\"d3-color-green\">2</span> Arcane Power for each enemy hit.</p> <p class=\"subtle\">Unlocked at level <em>24</em>.</p>",
    e: "<p>With each cast, gain a protective shield for <span class=\"d3-color-green\">3</span> seconds that absorbs <span class=\"d3-color-green\">4%</span> of your Life in damage.</p> <p class=\"subtle\">Unlocked at level <em>51</em>.</p>",
    elements: {
      a: "fir",
      b: "lit",
      c: "col",
      d: "arc",
      e: "arc",
      x: "arc",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/wizard_spectralblade.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">This is a Signature spell. Signature spells are free to cast.</span></p><p>Summon a spectral blade that strikes all enemies up to <span class=\"d3-color-green\">15</span> yards in front of you for <span class=\"d3-color-green\">168%</span> weapon damage as Arcane.</p> <p class=\"special\">Primary</p> <p class=\"subtle\">Unlocked at level <em>11</em>.</p> </div> </div>",
  },
  stormarmor: {
    a: "<p>Increase the damage of the shock to <span class=\"d3-color-green\">315%</span> weapon damage as Lightning. </p> <p class=\"subtle\">Unlocked at level <em>37</em>.</p>",
    b: "<p>Increase your movement speed by <span class=\"d3-color-green\">25%</span> for <span class=\"d3-color-green\">3</span> seconds when you are hit by melee or ranged attacks.</p> <p class=\"subtle\">Unlocked at level <em>43</em>.</p>",
    c: "<p>Ranged and melee attackers are shocked for <span class=\"d3-color-green\">189%</span> weapon damage as Lightning.</p> <p class=\"subtle\">Unlocked at level <em>23</em>.</p>",
    d: "<p>Reduce the Arcane Power cost of all skills by <span class=\"d3-color-green\">3</span> while Storm Armor is active.</p> <p class=\"subtle\">Unlocked at level <em>33</em>.</p>",
    e: "<p>Critical Hits have a chance to electrocute a nearby enemy for <span class=\"d3-color-green\">425%</span> weapon damage as Lightning.</p> <p class=\"subtle\">Unlocked at level <em>58</em>.</p>",
    elements: {
      a: "lit",
      b: "lit",
      c: "lit",
      d: "lit",
      e: "lit",
      x: "lit",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/wizard_stormarmor.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">25</span> Arcane Power</p><p>Bathe yourself in electrical energy, periodically shocking a nearby enemy for <span class=\"d3-color-green\">175%</span> weapon damage as Lightning. Lasts <span class=\"d3-color-green\">10</span> minutes.</p><p><span class=\"d3-color-yellow\">Only one Armor may be active at a time.</span></p> <p class=\"special\">Conjuration</p> <p class=\"subtle\">Unlocked at level <em>17</em>.</p> </div> </div>",
  },
  teleport: {
    a: "<p>Cast a short range Wave of Force upon arrival, dealing <span class=\"d3-color-green\">175%</span> weapon damage as Arcane to all nearby enemies and stunning them for <span class=\"d3-color-green\">1</span> second.</p> <p class=\"subtle\">Unlocked at level <em>59</em>.</p>",
    b: "<p>Summon <span class=\"d3-color-green\">2</span> decoys for <span class=\"d3-color-green\">6</span> seconds after teleporting.</p> <p class=\"subtle\">Unlocked at level <em>43</em>.</p>",
    c: "<p>For <span class=\"d3-color-green\">5</span> seconds after you Teleport, you will take <span class=\"d3-color-green\">25%</span> less damage.</p> <p class=\"subtle\">Unlocked at level <em>26</em>.</p>",
    d: "<p>Casting Teleport again within <span class=\"d3-color-green\">5</span> seconds will instantly return you to your original location and set the remaining cooldown to <span class=\"d3-color-green\">1</span> second.</p> <p class=\"subtle\">Unlocked at level <em>37</em>.</p>",
    e: "<p>After casting Teleport, you have <span class=\"d3-color-green\">3</span> seconds to Teleport <span class=\"d3-color-green\">1</span> additional time.</p> <p class=\"subtle\">Unlocked at level <em>31</em>.</p>",
    elements: {
      a: "arc",
      b: "arc",
      c: "arc",
      d: "arc",
      e: "arc",
      x: "arc",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/wizard_teleport.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">11</span> seconds</p><p>Teleport through the ether to the selected location up to <span class=\"d3-color-green\">50</span> yards away.</p> <p class=\"special\">Defensive</p> <p class=\"subtle\">Unlocked at level <em>22</em>.</p> </div> </div>",
  },
  waveofforce: {
    a: "<p>Wave of Force repels projectiles back toward their shooter, knocks back nearby enemies and Slows them by <span class=\"d3-color-green\">60%</span> for <span class=\"d3-color-green\">3</span> seconds.</p><p>Wave of Force gains a <span class=\"d3-color-green\">5</span> second cooldown.</p> <p class=\"subtle\">Unlocked at level <em>15</em>.</p>",
    b: "<p>Each enemy hit restores <span class=\"d3-color-green\">1</span> Arcane Power.</p><p>Wave of Force's damage turns into Lightning.</p> <p class=\"subtle\">Unlocked at level <em>39</em>.</p>",
    c: "<p>Increase the damage to <span class=\"d3-color-green\">475%</span> weapon damage as Fire.</p> <p class=\"subtle\">Unlocked at level <em>49</em>.</p>",
    d: "<p>Each enemy hit increases the damage of your next Arcane spell by <span class=\"d3-color-green\">4%</span>.</p> <p class=\"subtle\">Unlocked at level <em>32</em>.</p>",
    e: "<p>Enemies hit deal <span class=\"d3-color-green\">20%</span> reduced damage for <span class=\"d3-color-green\">4</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>22</em>.</p>",
    elements: {
      a: "arc",
      b: "lit",
      c: "fir",
      d: "arc",
      e: "arc",
      x: "arc",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/wizard_waveofforce.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">25</span> Arcane Power</p><p>Discharge a wave of pure energy that deals <span class=\"d3-color-green\">390%</span> weapon damage as Arcane to nearby enemies.</p> <p class=\"special\">Force</p> <p class=\"subtle\">Unlocked at level <em>9</em>.</p> </div> </div>",
  },
};
DiabloCalc.passivetips.wizard = {
  arcanedynamo: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/wizard_passive_arcanedynamo.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>When you cast a Signature spell, you gain a Flash of Insight. After <span class=\"d3-color-green\">5</span> Flashes of Insight, your next non-Signature spell deals <span class=\"d3-color-green\">60%</span> additional damage. </p><p>The following skills are Signature spells:<br/><span class=\"tooltip-icon-bullet\"></span> Magic Missile<br/><span class=\"tooltip-icon-bullet\"></span> Shock Pulse<br/><span class=\"tooltip-icon-bullet\"></span> Spectral Blade<br/><span class=\"tooltip-icon-bullet\"></span> Electrocute</p> <p class=\"subtle\">Unlocked at level <em>55</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">Dare not to invoke the wrath of a Wizard. You are nothing more than a loose coalescence of dust before their ire, easily scattered at a whim.</div> </div>",
  astralpresence: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/wizard_passive_astralpresence.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>Increase your maximum Arcane Power by <span class=\"d3-color-green\">20</span> and Arcane Power regeneration by <span class=\"d3-color-green\">2.5</span> per second.</p> <p class=\"subtle\">Unlocked at level <em>24</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"Feel the power in the veil that surrounds us—a thunder cloud ready to burst... a volcano about to erupt. Harness it, and you will be invincible.\" —Adria</div> </div>",
  audacity: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/x1_wizard_passive_audacity.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>You deal <span class=\"d3-color-green\">30%</span> additional damage to enemies within <span class=\"d3-color-green\">15</span> yards.</p> <p class=\"subtle\">Unlocked at level <em>66</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"Those who dare approach you do so at their own peril.\" —Valthek, High Councilor of the Vizjerei</div> </div>",
  blur: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/wizard_passive_blur.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>Decrease damage taken by <span class=\"d3-color-green\">17%</span>.</p> <p class=\"subtle\">Unlocked at level <em>10</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">Truly powerful Wizards have been known to turn their magic inward, transmuting the very composition of their own bodies for boundless energy and catlike reflexes.</div> </div>",
  coldblooded: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/wizard_passive_coldblooded.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>Enemies chilled or frozen by you take <span class=\"d3-color-green\">10%</span> more damage from all sources for the duration of the chill or Freeze.</p> <p class=\"subtle\">Unlocked at level <em>30</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"Feel your blood run cold as the water of the Frozen Sea, and know that I can shatter you with a touch.\" —The Ice Queen's Tale</div> </div>",
  conflagration: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/wizard_passive_conflagration.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>Fire damage dealt to enemies applies a burning effect, increasing their chance to be critically hit by <span class=\"d3-color-green\">6%</span> for <span class=\"d3-color-green\">3</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>34</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"The red hot armor seared their flesh and boiled their blood as they tried desperately to pry it from smoldering bodies. We finished the defenseless creatures as an act of mercy.\" —Tales of Caldeum, Volume XII</div> </div>",
  dominance: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/x1_wizard_passive_arcaneaegis.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>Killing an enemy grants a shield that absorbs <span class=\"d3-color-green\">2%</span> of your Life in damage for <span class=\"d3-color-green\">3</span> seconds. This effect can stack up to <span class=\"d3-color-green\">10</span> times.</p><p>Refreshing Dominance will set the shield to its maximum possible potency and each stack will increase its total duration by <span class=\"d3-color-green\">0.5</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>50</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"Why waste your own energy? Using your enemy's to protect yourself strengthens you while it weakens him. What could be more perfect?\" —Ennead Sage Resko</div> </div>",
  elementalexposure: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/x1_wizard_passive_elementalexposure.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>Damaging enemies with Arcane, Cold, Fire or Lightning will cause them to take <span class=\"d3-color-green\">5%</span> more damage from all sources for <span class=\"d3-color-green\">5</span> seconds. Each different damage type applies a stack, stacking up to <span class=\"d3-color-green\">4</span> times.</p><p>Elemental damage from your weapon contributes to Elemental Exposure.</p> <p class=\"subtle\">Unlocked at level <em>68</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">Adding insult to injury may be entertaining, but adding increased injury is a more effective tactic.</div> </div>",
  evocation: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/wizard_passive_evocation.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>Reduce all cooldowns by <span class=\"d3-color-green\">20%</span>.</p> <p class=\"subtle\">Unlocked at level <em>13</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">So long have you focused on twisting reality to your will that time itself seeks to appease you.</div> </div>",
  galvanizingward: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/wizard_passive_galvanizingward.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>As long as you have not taken damage in the last <span class=\"d3-color-green\">5</span> seconds you gain a protective shield that absorbs the next <span class=\"d3-color-green\">60%</span> of your Life in damage.</p> <p class=\"subtle\">Unlocked at level <em>40</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"Power begets power. The excess energy from one spell is absorbed by the other, and so the effect is sustained.\" —Excerpt from Grand Master Clavaught's Lecture on Synergistic Effects in Esoteric Arcane Spheres</div> </div>",
  glasscannon: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/wizard_passive_glasscannon.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>Increase all damage done by <span class=\"d3-color-green\">15%</span>, but decrease Armor and resistances by <span class=\"d3-color-green\">10%</span>.</p> <p class=\"subtle\">Unlocked at level <em>16</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"How will I survive? I don't intend to get hit in the first place. If you even touch me, it's because I allowed it.\" —Maloth, renegade wizard</div> </div>",
  illusionist: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/wizard_passive_illusionist.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>When you take more than <span class=\"d3-color-green\">15%</span> of your maximum Life in damage within <span class=\"d3-color-green\">1</span> second, the cooldowns on Mirror Image, Slow Time, and Teleport are reset.</p><p>When you use Mirror Image, Slow Time, or Teleport, your movement speed is increased by <span class=\"d3-color-green\">30%</span> for <span class=\"d3-color-green\">3</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>27</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"To be where you are not is the wisest of strategies.\" —Grand Archmage Ralhys</div> </div>",
  paralysis: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/wizard_passive_paralysis.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>Lightning spells have a <span class=\"d3-color-green\">15%</span> chance to Stun all targets hit for <span class=\"d3-color-green\">1.5</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>37</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"Some people are shocked by my mastery of magic.\" —Larra Stormlash</div> </div>",
  powerhungry: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/wizard_passive_powerhungry.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>Being healed by a health globe causes the next Arcane Power Spender you cast to be cast for free.</p><p>You can have up to <span class=\"d3-color-green\">10</span> charges of Power Hungry.</p> <p class=\"subtle\">Unlocked at level <em>10</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"It just doesn't sit right with me. Some of the things these so-called wizards do... They border on necromancy. Or worse! It's just not proper magic.\" —Venerable Sorcerer Fob Dunar</div> </div>",
  prodigy: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/wizard_passive_prodigy.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>When you cast a Signature spell, you gain <span class=\"d3-color-green\">5</span> Arcane Power.</p><p>The following skills are Signature spells:<br/><span class=\"tooltip-icon-bullet\"></span> Magic Missile<br/><span class=\"tooltip-icon-bullet\"></span> Shock Pulse<br/><span class=\"tooltip-icon-bullet\"></span> Spectral Blade<br/><span class=\"tooltip-icon-bullet\"></span> Electrocute</p> <p class=\"subtle\">Unlocked at level <em>20</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"Heavy steel armor may turn aside a blade, but let's see how well it works against lightning!\" —Larra Stormlash's infamous faux pas at the Royal Westmarch Joust</div> </div>",
  temporalflux: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/wizard_passive_temporalflux.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>Enemies that take Arcane damage are slowed by <span class=\"d3-color-green\">80%</span> for <span class=\"d3-color-green\">2</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>45</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"The energies of time and arcane power are jealous consorts. If you caress the one, you neglect the other at great risk.\" —Ennead Sage Resko</div> </div>",
  unstableanomaly: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/wizard_passive_unstableanomaly.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>When you receive fatal damage, you instead gain a shield equal to <span class=\"d3-color-green\">400%</span> of your maximum Life for <span class=\"d3-color-green\">5</span> seconds and release a shockwave that knocks enemies back and Stuns them for <span class=\"d3-color-green\">3</span> seconds. </p><p>This effect may occur once every <span class=\"d3-color-green\">60</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>60</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"It takes perfect concentration for a Wizard to dance on the edge of infinity. Never be the one to break that concentration.\" —One-Eye Whipple</div> </div>",
  unwaveringwill: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/x1_wizard_passive_unwaveringwill.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>Standing still for <span class=\"d3-color-green\">1.5</span> seconds increases the following attributes:</p><p><span class=\"tooltip-icon-bullet\"></span> Armor: <span class=\"d3-color-green\">20%</span><br/><span class=\"tooltip-icon-bullet\"></span> All Resistances: <span class=\"d3-color-green\">20%</span><br/><span class=\"tooltip-icon-bullet\"></span> Damage: <span class=\"d3-color-green\">10%</span></p> <p class=\"subtle\">Unlocked at level <em>64</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"At times the greatest strategy is to withdraw into yourself, to experience the clarity of mind in the moments before launching your attack.\" —Archmage Skye</div> </div>",
};
