if (!DiabloCalc.skilltips) DiabloCalc.skilltips = {};
if (!DiabloCalc.passivetips) DiabloCalc.passivetips = {};
DiabloCalc.skilltips.barbarian = {
  ancientspear: {
    a: "<p>Add a chain to the spear to drag all enemies hit back to you and Slow them by <span class=\"d3-color-green\">60%</span> for <span class=\"d3-color-green\">1</span> second.</p> <p class=\"subtle\">Unlocked at level <em>34</em>.</p>",
    b: "<p>Expend all remaining Fury to deal <span class=\"d3-color-green\">20%</span> weapon damage for every point of Fury expended to enemies within <span class=\"d3-color-green\">9</span> yards of the impact location.</p> <p class=\"subtle\">Unlocked at level <em>48</em>.</p>",
    c: "<p>Increase the damage to <span class=\"d3-color-green\">640%</span> weapon damage as Fire.</p> <p class=\"subtle\">Unlocked at level <em>42</em>.</p>",
    d: "<p>Enemies hit are knocked back <span class=\"d3-color-green\">5</span> yards.</p> <p class=\"subtle\">Unlocked at level <em>29</em>.</p>",
    e: "<p>Add a chain to the spear to throw all enemies hit behind you and Slow them by <span class=\"d3-color-green\">60%</span> for <span class=\"d3-color-green\">1</span> second.</p> <p class=\"subtle\">Unlocked at level <em>59</em>.</p>",
    elements: {
      a: "phy",
      b: "phy",
      c: "fir",
      d: "phy",
      e: "phy",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/x1_barbarian_ancientspear.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">25</span> Fury</p><p>Throw a spear that pierces enemies and deals <span class=\"d3-color-green\">500%</span> weapon damage.</p> <p class=\"special\">Secondary</p> <p class=\"subtle\">Unlocked at level <em>26</em>.</p> </div> </div>",
  },
  avalanche: {
    a: "<p>Giant blocks of ice hit enemies for <span class=\"d3-color-green\">2400%</span> weapon damage as Cold and <span class=\"d3-color-green\">Freeze</span> them.</p> <p class=\"subtle\">Unlocked at level <em>69</em>.</p>",
    b: "<p>Cave-in from both sides pushes enemies together, dealing <span class=\"d3-color-green\">2800%</span> weapon damage as Cold and Slowing them by <span class=\"d3-color-green\">60%</span> for <span class=\"d3-color-green\">3</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>65</em>.</p>",
    c: "<p>Chunks of molten lava are randomly launched at nearby enemies, dealing <span class=\"d3-color-green\">6600%</span> weapon damage as Fire over <span class=\"d3-color-green\">5</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>62</em>.</p>",
    d: "<p>Cooldown is reduced by <span class=\"d3-color-green\">1</span> second for every <span class=\"d3-color-green\">15</span> Fury spent.</p> <p class=\"subtle\">Unlocked at level <em>63</em>.</p>",
    e: "<p>Store up to <span class=\"d3-color-green\">3</span> charges of Avalanche.</p> <p class=\"subtle\">Unlocked at level <em>67</em>.</p>",
    elements: {
      a: "col",
      b: "col",
      c: "fir",
      d: "phy",
      e: "phy",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/x1_barbarian_avalanche_v2.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">30</span> seconds</p><p>Cause a massive avalanche of rocks to fall on an area dealing <span class=\"d3-color-green\">2400%</span> weapon damage to all enemies caught in its path.</p><p><span class=\"d3-color-yellow\">Cooldown is reduced by <span class=\"d3-color-green\">1</span> second for every <span class=\"d3-color-green\">25</span> Fury you spend.</span></p> <p class=\"special\">Might</p> <p class=\"subtle\">Unlocked at level <em>61</em>.</p> </div> </div>",
  },
  bash: {
    a: "<p>The enemy has a <span class=\"d3-color-green\">10%</span> increased chance to be Critically Hit for <span class=\"d3-color-green\">3</span> seconds.</p><p>Bash's damage turns into Lightning.</p> <p class=\"subtle\">Unlocked at level <em>13</em>.</p>",
    b: "<p>Increase your damage by <span class=\"d3-color-green\">4%</span> for <span class=\"d3-color-green\">5</span> seconds after using Bash. This effect stacks up to <span class=\"d3-color-green\">3</span> times.</p> <p class=\"subtle\">Unlocked at level <em>26</em>.</p>",
    c: "<p>Each hit <span class=\"d3-color-green\">Freezes</span> the enemy for <span class=\"d3-color-green\">1.5</span> seconds.</p><p>Enemies can be frozen by Bash once every <span class=\"d3-color-green\">5</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>6</em>.</p>",
    d: "<p>Increase Fury generated to <span class=\"d3-color-green\">9</span>.</p><p>Bash's damage turns into Fire.</p> <p class=\"subtle\">Unlocked at level <em>44</em>.</p>",
    e: "<p>Each hit causes a shockwave that deals <span class=\"d3-color-green\">100%</span> weapon damage as Fire to enemies in a <span class=\"d3-color-green\">26</span> yard line behind the primary enemy.</p> <p class=\"subtle\">Unlocked at level <em>52</em>.</p>",
    elements: {
      a: "lit",
      b: "phy",
      c: "col",
      d: "fir",
      e: "fir",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/barbarian_bash.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Generate:</span> <span class=\"d3-color-green\">6</span> Fury per attack</p><p>Brutally smash an enemy for <span class=\"d3-color-green\">320%</span> weapon damage.</p> <p class=\"special\">Primary</p> <p class=\"subtle\">Unlocked at level <em>1</em>.</p> </div> </div>",
  },
  battlerage: {
    a: "<p>Increase damage bonus to <span class=\"d3-color-green\">15%</span>.</p> <p class=\"subtle\">Unlocked at level <em>26</em>.</p>",
    b: "<p>Increase movement speed by <span class=\"d3-color-green\">15%</span>.</p> <p class=\"subtle\">Unlocked at level <em>31</em>.</p>",
    c: "<p>Critical Hits heal you and your pets for up to <span class=\"d3-color-green\">21457</span> Life.</p> <p class=\"subtle\">Unlocked at level <em>38</em>.</p>",
    d: "<p>Gain <span class=\"d3-color-green\">1%</span> Critical Hit Chance for each enemy within <span class=\"d3-color-green\">10</span> yards while under the effects of Battle Rage.</p> <p class=\"subtle\">Unlocked at level <em>46</em>.</p>",
    e: "<p>Critical Hits cause an explosion of blood dealing <span class=\"d3-color-green\">20%</span> of the damage done to all other nearby enemies.</p> <p class=\"subtle\">Unlocked at level <em>54</em>.</p>",
    elements: {
      a: "phy",
      b: "phy",
      c: "phy",
      d: "phy",
      e: "phy",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/barbarian_battlerage.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">20</span> Fury</p><p>Enter a rage which increases your damage by <span class=\"d3-color-green\">10%</span> and Critical Hit Chance by <span class=\"d3-color-green\">3%</span>. Lasts <span class=\"d3-color-green\">120</span> seconds.</p> <p class=\"special\">Tactics</p> <p class=\"subtle\">Unlocked at level <em>22</em>.</p> </div> </div>",
  },
  calloftheancients: {
    a: "<p>Each point of Fury you spend heals you and your Ancients for <span class=\"d3-color-green\">966</span> Life.</p> <p class=\"subtle\">Unlocked at level <em>45</em>.</p>",
    b: "<p>The Ancients deal <span class=\"d3-color-green\">540%</span> weapon damage as Fire with each attack.</p> <p class=\"subtle\">Unlocked at level <em>31</em>.</p>",
    c: "<p>Gain <span class=\"d3-color-green\">4</span> Fury every time an Ancient deals damage.</p> <p class=\"subtle\">Unlocked at level <em>51</em>.</p>",
    d: "<p>Enemies hit by the Ancients are <span class=\"d3-color-green\">Chilled</span> for <span class=\"d3-color-green\">2</span> seconds and have <span class=\"d3-color-green\">10%</span> increased chance to be Critically Hit.</p><p>The Ancients' damage turns into Cold.</p> <p class=\"subtle\">Unlocked at level <em>37</em>.</p>",
    e: "<p><span class=\"d3-color-green\">50%</span> of all damage dealt to you is instead divided evenly between the Ancients.</p><p>The Ancients' damage turns into Lightning.</p> <p class=\"subtle\">Unlocked at level <em>58</em>.</p>",
    elements: {
      a: "phy",
      b: "fir",
      c: "phy",
      d: "col",
      e: "lit",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/barbarian_calloftheancients.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">120</span> seconds</p><p>Summon the ancient Barbarians Talic, Korlic, and Madawc to fight alongside you for <span class=\"d3-color-green\">20</span> seconds. Each deals <span class=\"d3-color-green\">270%</span> weapon damage per swing in addition to bonus abilities.</p><p><span class=\"tooltip-icon-bullet\"></span> Talic wields a sword and shield and uses Whirlwind and Leap Attack.<br/><span class=\"tooltip-icon-bullet\"></span> Korlic wields a massive polearm and uses Cleave and Furious Charge.<br/><span class=\"tooltip-icon-bullet\"></span> Madawc dual-wields axes and uses Weapon Throw and Seismic Slam.</p> <p class=\"special\">Rage</p> <p class=\"subtle\">Unlocked at level <em>25</em>.</p> </div> </div>",
  },
  cleave: {
    a: "<p>Swing at all enemies around you and increase damage to <span class=\"d3-color-green\">235%</span> weapon damage as Lightning.</p> <p class=\"subtle\">Unlocked at level <em>47</em>.</p>",
    b: "<p>Enemies cleaved are <span class=\"d3-color-green\">Chilled</span> and take <span class=\"d3-color-green\">10%</span> increased damage from all sources for <span class=\"d3-color-green\">3</span> seconds.</p><p>Cleave's damage turns into Cold.</p> <p class=\"subtle\">Unlocked at level <em>55</em>.</p>",
    c: "<p>On Critical Hits, knock enemies up into the air and deal <span class=\"d3-color-green\">80%</span> weapon damage to enemies where they land.</p> <p class=\"subtle\">Unlocked at level <em>30</em>.</p>",
    d: "<p>Generate <span class=\"d3-color-green\">1</span> additional Fury per enemy hit.</p><p>Cleave's damage turns into Fire.</p> <p class=\"subtle\">Unlocked at level <em>18</em>.</p>",
    e: "<p>Enemies slain by Cleave explode, causing <span class=\"d3-color-green\">160%</span> weapon damage as Fire to all other enemies within <span class=\"d3-color-green\">8</span> yards.</p> <p class=\"subtle\">Unlocked at level <em>9</em>.</p>",
    elements: {
      a: "lit",
      b: "col",
      c: "phy",
      d: "fir",
      e: "fir",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/barbarian_cleave.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Generate:</span> <span class=\"d3-color-green\">6</span> Fury per attack</p><p>Swing your weapon in a wide arc to deal <span class=\"d3-color-green\">200%</span> weapon damage to all enemies caught in the swing.</p> <p class=\"special\">Primary</p> <p class=\"subtle\">Unlocked at level <em>3</em>.</p> </div> </div>",
  },
  earthquake: {
    a: "<p>Increase Earthquake's damage to <span class=\"d3-color-green\">6000%</span> weapon damage as Fire.</p> <p class=\"subtle\">Unlocked at level <em>50</em>.</p>",
    b: "<p><span class=\"d3-color-green\">20</span> secondary tremors follow your movement and deal <span class=\"d3-color-green\">300%</span> weapon damage as Fire each.</p> <p class=\"subtle\">Unlocked at level <em>24</em>.</p>",
    c: "<p>Create an icy patch, causing Earthquake to <span class=\"d3-color-green\">Freeze</span> all enemies hit and deal Cold damage.</p> <p class=\"subtle\">Unlocked at level <em>29</em>.</p>",
    d: "<p>Remove the Fury cost and reduce the cooldown to <span class=\"d3-color-green\">30</span> seconds.</p><p>Earthquake's damage turns into Lightning.</p> <p class=\"subtle\">Unlocked at level <em>39</em>.</p>",
    e: "<p>All enemies within <span class=\"d3-color-green\">24</span> yards are pulled in towards you.</p><p>Earthquake's damage turns into Physical.</p> <p class=\"subtle\">Unlocked at level <em>56</em>.</p>",
    elements: {
      a: "fir",
      b: "fir",
      c: "col",
      d: "lit",
      e: "phy",
      x: "fir",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/barbarian_earthquake.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">25</span> Fury<br/><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">60</span> seconds</p><p>Shake the ground violently, dealing <span class=\"d3-color-green\">4800%</span> weapon damage as Fire over <span class=\"d3-color-green\">8</span> seconds to all enemies within <span class=\"d3-color-green\">18</span> yards.</p> <p class=\"special\">Rage</p> <p class=\"subtle\">Unlocked at level <em>19</em>.</p> </div> </div>",
  },
  frenzy: {
    a: "<p>Each Frenzy effect also increases your damage by <span class=\"d3-color-green\">2.5%</span>.</p><p>Frenzy's damage turns into Fire.</p> <p class=\"subtle\">Unlocked at level <em>59</em>.</p>",
    b: "<p>Each strike has a <span class=\"d3-color-green\">25%</span> chance to throw a piercing axe at a nearby enemy that deals <span class=\"d3-color-green\">300%</span> weapon damage as Cold to all enemies in its path.</p><p>Frenzy's damage turns into Cold.</p> <p class=\"subtle\">Unlocked at level <em>17</em>.</p>",
    c: "<p>Gain <span class=\"d3-color-green\">5%</span> movement speed for each stack of Frenzy.</p> <p class=\"subtle\">Unlocked at level <em>34</em>.</p>",
    d: "<p>Each hit has a <span class=\"d3-color-green\">30%</span> chance to call down a bolt of lightning from above, stunning the enemy for <span class=\"d3-color-green\">1.5</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>51</em>.</p>",
    e: "<p>Increase Fury generated to <span class=\"d3-color-green\">6</span>.</p><p>Frenzy's damage turns into Cold.</p> <p class=\"subtle\">Unlocked at level <em>22</em>.</p>",
    elements: {
      a: "fir",
      b: "col",
      c: "phy",
      d: "lit",
      e: "col",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/barbarian_frenzy.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Generate:</span> <span class=\"d3-color-green\">4</span> Fury per attack</p><p>Swing for <span class=\"d3-color-green\">220%</span> weapon damage. Frenzy's attack speed increases by <span class=\"d3-color-green\">15%</span> for <span class=\"d3-color-green\">4</span> seconds with each swing. This effect stacks up to <span class=\"d3-color-green\">5</span> times.</p> <p class=\"special\">Primary</p> <p class=\"subtle\">Unlocked at level <em>11</em>.</p> </div> </div>",
  },
  furiouscharge: {
    a: "<p>Increase the damage to <span class=\"d3-color-green\">1050%</span> weapon damage as Fire.</p> <p class=\"subtle\">Unlocked at level <em>27</em>.</p>",
    b: "<p>Store up to <span class=\"d3-color-green\">3</span> charges of Furious Charge.</p><p>Furious Charge's damage turns into Lightning.</p> <p class=\"subtle\">Unlocked at level <em>56</em>.</p>",
    c: "<p>All enemies hit are <span class=\"d3-color-green\">Frozen</span> for <span class=\"d3-color-green\">2.5</span> seconds.</p><p>Furious Charge's damage turns into Cold.</p> <p class=\"subtle\">Unlocked at level <em>47</em>.</p>",
    d: "<p>Generate <span class=\"d3-color-green\">10</span> additional Fury for each enemy hit while charging.</p> <p class=\"subtle\">Unlocked at level <em>38</em>.</p>",
    e: "<p>Recharge time is reduced by <span class=\"d3-color-green\">2</span> seconds for every enemy hit. This effect can reduce the recharge time by up to <span class=\"d3-color-green\">10</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>33</em>.</p>",
    elements: {
      a: "fir",
      b: "lit",
      c: "col",
      d: "phy",
      e: "phy",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/barbarian_furiouscharge.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">1</span> Charge<br/><span class=\"d3-color-gold\">Generate:</span> <span class=\"d3-color-green\">15</span> Fury</p><p>Rush forward knocking back and dealing <span class=\"d3-color-green\">600%</span> weapon damage to enemies along your path.</p><p><span class=\"d3-color-yellow\">You gain a charge every <span class=\"d3-color-green\">10</span> seconds and can have up to <span class=\"d3-color-green\">1</span> charge stored at a time.</span></p> <p class=\"special\">Might</p> <p class=\"subtle\">Unlocked at level <em>21</em>.</p> </div> </div>",
  },
  groundstomp: {
    a: "<p>Enemies in the area also take <span class=\"d3-color-green\">575%</span> weapon damage as Fire.</p> <p class=\"subtle\">Unlocked at level <em>28</em>.</p>",
    b: "<p>Increase the area of effect to <span class=\"d3-color-green\">24</span> yards. Enemies are pulled closer before the strike lands.</p> <p class=\"subtle\">Unlocked at level <em>18</em>.</p>",
    c: "<p>Enemies hit have a <span class=\"d3-color-green\">10%</span> chance to drop a health globe.</p> <p class=\"subtle\">Unlocked at level <em>54</em>.</p>",
    d: "<p>Increase Fury generated to <span class=\"d3-color-green\">30</span>.</p> <p class=\"subtle\">Unlocked at level <em>40</em>.</p>",
    e: "<p>Reduce the cooldown of Ground Stomp to <span class=\"d3-color-green\">8</span> seconds.</p><p>Enemies in the area have their movement speed slowed by <span class=\"d3-color-green\">80%</span> for <span class=\"d3-color-green\">8</span> seconds after they recover from being stunned.</p> <p class=\"subtle\">Unlocked at level <em>12</em>.</p>",
    elements: {
      a: "fir",
      b: "phy",
      c: "phy",
      d: "phy",
      e: "col",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/barbarian_groundstomp.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Generate:</span> <span class=\"d3-color-green\">15</span> Fury<br/><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">12</span> seconds</p><p>Smash the ground, stunning all enemies within <span class=\"d3-color-green\">14</span> yards for <span class=\"d3-color-green\">4</span> seconds.</p> <p class=\"special\">Defensive</p> <p class=\"subtle\">Unlocked at level <em>4</em>.</p> </div> </div>",
  },
  hammeroftheancients: {
    a: "<p>Smash for <span class=\"d3-color-green\">640%</span> weapon damage as Fire.</p> <p class=\"subtle\">Unlocked at level <em>15</em>.</p>",
    b: "<p>Create a shockwave that deals <span class=\"d3-color-green\">505%</span> weapon damage to all enemies within <span class=\"d3-color-green\">22</span> yards in front of you.</p> <p class=\"subtle\">Unlocked at level <em>7</em>.</p>",
    c: "<p>Each hit creates a tremor at the point of impact for <span class=\"d3-color-green\">2</span> seconds that <span class=\"d3-color-green\">Chills</span> enemies by <span class=\"d3-color-green\">80%</span>.</p><p>Hammer of the Ancients's damage turns into Cold.</p> <p class=\"subtle\">Unlocked at level <em>27</em>.</p>",
    d: "<p>Critical Hits heal you for <span class=\"d3-color-green\">3%</span> of your maximum Life.</p> <p class=\"subtle\">Unlocked at level <em>53</em>.</p>",
    e: "<p>When you kill an enemy with Hammer of the Ancients, other enemies within <span class=\"d3-color-green\">10</span> yards are Stunned for <span class=\"d3-color-green\">2</span> seconds.</p><p>Hammer of the Ancients turns into Lightning damage.</p> <p class=\"subtle\">Unlocked at level <em>39</em>.</p>",
    elements: {
      a: "fir",
      b: "phy",
      c: "col",
      d: "phy",
      e: "lit",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/barbarian_hammeroftheancients.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">20</span> Fury</p><p>Call forth a massive hammer to smash enemies directly in front of you for <span class=\"d3-color-green\">535%</span> weapon damage. Hammer of the Ancients has a <span class=\"d3-color-green\">1%</span> increased Critical Hit Chance for every <span class=\"d3-color-green\">5</span> Fury that you have.</p> <p class=\"special\">Secondary</p> <p class=\"subtle\">Unlocked at level <em>2</em>.</p> </div> </div>",
  },
  ignorepain: {
    a: "<p>Instantly heal for <span class=\"d3-color-green\">35%</span> of maximum Life when activating Ignore Pain.</p> <p class=\"subtle\">Unlocked at level <em>58</em>.</p>",
    b: "<p>Increase duration to <span class=\"d3-color-green\">7</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>31</em>.</p>",
    c: "<p>Allies within <span class=\"d3-color-green\">50</span> yards also gain <span class=\"d3-color-green\">25%</span> damage reduction and <span class=\"d3-color-green\">Immunity</span> to control-impairing effects for <span class=\"d3-color-green\">5</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>43</em>.</p>",
    d: "<p>While Ignore Pain is active, gain <span class=\"d3-color-green\">40%</span> increased movement speed and knock enemies away as you run.</p> <p class=\"subtle\">Unlocked at level <em>26</em>.</p>",
    e: "<p>While Ignore Pain is active, gain <span class=\"d3-color-green\">5364</span> Life per Fury spent.</p> <p class=\"subtle\">Unlocked at level <em>36</em>.</p>",
    elements: {
      a: "phy",
      b: "phy",
      c: "phy",
      d: "phy",
      e: "phy",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/barbarian_ignorepain.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">30</span> seconds</p><p>Reduce all damage taken by <span class=\"d3-color-green\">50%</span> and gain <span class=\"d3-color-green\">Immunity</span> to all control-impairing effects for <span class=\"d3-color-green\">5</span> seconds.</p> <p class=\"special\">Defensive</p> <p class=\"subtle\">Unlocked at level <em>22</em>.</p> </div> </div>",
  },
  leap: {
    a: "<p>Shockwaves burst forth from the ground increasing the radius of effect to <span class=\"d3-color-green\">16</span> yards and pulling affected enemies towards you.</p> <p class=\"subtle\">Unlocked at level <em>44</em>.</p>",
    b: "<p>Increase the damage of Leap to <span class=\"d3-color-green\">450%</span> and send enemies hurtling away from where you land.</p> <p class=\"subtle\">Unlocked at level <em>32</em>.</p>",
    c: "<p>You leap with such great force that enemies within <span class=\"d3-color-green\">10</span> yards of the takeoff point take <span class=\"d3-color-green\">180%</span> weapon damage and are also slowed by <span class=\"d3-color-green\">60%</span> for <span class=\"d3-color-green\">3</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>21</em>.</p>",
    d: "<p>Gain <span class=\"d3-color-green\">150%</span> additional Armor for <span class=\"d3-color-green\">4</span> seconds after landing.</p> <p class=\"subtle\">Unlocked at level <em>14</em>.</p>",
    e: "<p>Land with such force that enemies have a <span class=\"d3-color-green\">100%</span> chance to be stunned for <span class=\"d3-color-green\">3</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>60</em>.</p>",
    elements: {
      a: "phy",
      b: "phy",
      c: "phy",
      d: "phy",
      e: "phy",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/barbarian_leap.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Generate:</span> <span class=\"d3-color-green\">15</span> Fury<br/><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">10</span> seconds</p><p>Leap into the air, dealing <span class=\"d3-color-green\">180%</span> weapon damage to all enemies within <span class=\"d3-color-green\">10</span> yards of your destination and slowing their movement speed by <span class=\"d3-color-green\">60%</span> for <span class=\"d3-color-green\">3</span> seconds.</p> <p class=\"special\">Defensive</p> <p class=\"subtle\">Unlocked at level <em>8</em>.</p> </div> </div>",
  },
  overpower: {
    a: "<p>Your Critical Hit Chance is increased by <span class=\"d3-color-green\">8%</span> for <span class=\"d3-color-green\">5</span> seconds.</p><p>Overpower's damage turns into Lightning.</p> <p class=\"subtle\">Unlocked at level <em>23</em>.</p>",
    b: "<p>Throw up to <span class=\"d3-color-green\">3</span> axes at nearby enemies that each deal <span class=\"d3-color-green\">380%</span> weapon damage.</p> <p class=\"subtle\">Unlocked at level <em>15</em>.</p>",
    c: "<p>Increase damage to <span class=\"d3-color-green\">760%</span> weapon damage as Fire.</p> <p class=\"subtle\">Unlocked at level <em>49</em>.</p>",
    d: "<p>Generate <span class=\"d3-color-green\">5</span> Fury for each enemy hit by Overpower.</p> <p class=\"subtle\">Unlocked at level <em>39</em>.</p>",
    e: "<p>Redirect <span class=\"d3-color-green\">35%</span> of incoming melee damage back to the attacker for <span class=\"d3-color-green\">5</span> seconds after Overpower is activated.</p> <p class=\"subtle\">Unlocked at level <em>32</em>.</p>",
    elements: {
      a: "lit",
      b: "phy",
      c: "fir",
      d: "phy",
      e: "col",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/barbarian_overpower.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">12</span> seconds</p><p>Deal <span class=\"d3-color-green\">380%</span> weapon damage to all enemies within <span class=\"d3-color-green\">9</span> yards.</p><p><span class=\"d3-color-yellow\">Critical Hits have a chance to reduce the cooldown of Overpower by <span class=\"d3-color-green\">1</span> second.</span></p> <p class=\"special\">Might</p> <p class=\"subtle\">Unlocked at level <em>9</em>.</p> </div> </div>",
  },
  rend: {
    a: "<p>Increase damage to <span class=\"d3-color-green\">1350%</span> weapon damage as Lightning over <span class=\"d3-color-green\">5</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>33</em>.</p>",
    b: "<p>Increase the range of Rend to hit all enemies within <span class=\"d3-color-green\">18</span> yards.</p><p>Rend's damage turns into Fire.</p> <p class=\"subtle\">Unlocked at level <em>11</em>.</p>",
    c: "<p>Affected enemies are <span class=\"d3-color-green\">Chilled</span> and take <span class=\"d3-color-green\">10%</span> increased damage from all sources.</p><p>Rend's damage turns into Cold.</p> <p class=\"subtle\">Unlocked at level <em>45</em>.</p>",
    d: "<p>Heal for <span class=\"d3-color-green\">0.5%</span> of your maximum Life per second for each affected enemy.</p> <p class=\"subtle\">Unlocked at level <em>19</em>.</p>",
    e: "<p>Enemies killed while bleeding cause all enemies within <span class=\"d3-color-green\">10</span> yards to begin bleeding for <span class=\"d3-color-green\">1100%</span> weapon damage as Physical over <span class=\"d3-color-green\">5</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>56</em>.</p>",
    elements: {
      a: "lit",
      b: "fir",
      c: "col",
      d: "phy",
      e: "phy",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/barbarian_rend.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">20</span> Fury</p><p>A sweeping strike causes all enemies within <span class=\"d3-color-green\">12</span> yards to Bleed for <span class=\"d3-color-green\">1100%</span> weapon damage as Physical over <span class=\"d3-color-green\">5</span> seconds.</p> <p class=\"special\">Secondary</p> <p class=\"subtle\">Unlocked at level <em>5</em>.</p> </div> </div>",
  },
  revenge: {
    a: "<p>Increase damage to <span class=\"d3-color-green\">700%</span> weapon damage as Fire.</p> <p class=\"subtle\">Unlocked at level <em>36</em>.</p>",
    b: "<p>Increase the maximum number of charges to <span class=\"d3-color-green\">3</span>.</p> <p class=\"subtle\">Unlocked at level <em>52</em>.</p>",
    c: "<p>Knockback enemies <span class=\"d3-color-green\">24</span> yards when using Revenge.</p><p>Revenge's damage turns into Lightning.</p> <p class=\"subtle\">Unlocked at level <em>41</em>.</p>",
    d: "<p>Increase healing to <span class=\"d3-color-green\">6%</span> of maximum Life for each enemy hit.</p> <p class=\"subtle\">Unlocked at level <em>19</em>.</p>",
    e: "<p>Increase your Critical Hit Chance by <span class=\"d3-color-green\">8%</span> for <span class=\"d3-color-green\">6</span> seconds after using Revenge.</p><p>Revenge's damage turns into Cold.</p> <p class=\"subtle\">Unlocked at level <em>25</em>.</p>",
    elements: {
      a: "fir",
      b: "phy",
      c: "lit",
      d: "phy",
      e: "col",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/barbarian_revenge.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost: </span><span class=\"d3-color-green\">1</span> charge</p><p>Deal <span class=\"d3-color-green\">300%</span> weapon damage to all nearby enemies. You heal <span class=\"d3-color-green\">4%</span> of your maximum Life for each enemy hit.</p><p><span class=\"d3-color-yellow\">Revenge has a </span><span class=\"d3-color-green\">15%</span> <span class=\"d3-color-yellow\">chance to gain a charge each time you are hit. Maximum <span class=\"d3-color-green\">2</span> charges.</span></p> <p class=\"special\">Might</p> <p class=\"subtle\">Unlocked at level <em>13</em>.</p> </div> </div>",
  },
  seismicslam: {
    a: "<p>Increase damage to <span class=\"d3-color-green\">735%</span> weapon damage as Fire and knocks all enemies hit up into the air.</p> <p class=\"subtle\">Unlocked at level <em>25</em>.</p>",
    b: "<p>The ground continues to shudder after the initial strike, damaging enemies in the area for <span class=\"d3-color-green\">230%</span> weapon damage as Physical over <span class=\"d3-color-green\">2</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>35</em>.</p>",
    c: "<p>Reduce the cost to <span class=\"d3-color-green\">22</span> Fury.</p><p>Seismic Slam's damage turns into Lightning.</p> <p class=\"subtle\">Unlocked at level <em>18</em>.</p>",
    d: "<p>Gain <span class=\"d3-color-green\">1%</span> of your maximum Life for every enemy hit.</p> <p class=\"subtle\">Unlocked at level <em>48</em>.</p>",
    e: "<p>Create a sheet of frost that deals <span class=\"d3-color-green\">755%</span> weapon damage as Cold and <span class=\"d3-color-green\">Chills</span> enemies by <span class=\"d3-color-green\">60%</span> for <span class=\"d3-color-green\">1</span> second.</p> <p class=\"subtle\">Unlocked at level <em>57</em>.</p>",
    elements: {
      a: "fir",
      b: "phy",
      c: "lit",
      d: "phy",
      e: "col",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/barbarian_seismicslam.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">30</span> Fury</p><p>Slam the ground and cause a wave of destruction that deals <span class=\"d3-color-green\">620%</span> weapon damage to enemies up to <span class=\"d3-color-green\">50</span> yards in front of you.</p> <p class=\"special\">Secondary</p> <p class=\"subtle\">Unlocked at level <em>12</em>.</p> </div> </div>",
  },
  sprint: {
    a: "<p>Increase the movement speed bonus to <span class=\"d3-color-green\">40%</span> for <span class=\"d3-color-green\">4</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>38</em>.</p>",
    b: "<p>Increase Dodge Chance by <span class=\"d3-color-green\">12%</span> while sprinting.</p> <p class=\"subtle\">Unlocked at level <em>23</em>.</p>",
    c: "<p>Tornadoes rage in your wake, each dealing <span class=\"d3-color-green\">60%</span> weapon damage as Physical for <span class=\"d3-color-green\">3</span> seconds to nearby enemies.</p> <p class=\"subtle\">Unlocked at level <em>29</em>.</p>",
    d: "<p>Increase movement speed of allies within <span class=\"d3-color-green\">50</span> yards by <span class=\"d3-color-green\">20%</span> for <span class=\"d3-color-green\">3</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>53</em>.</p>",
    e: "<p>Slams through enemies, knocking them back and dealing <span class=\"d3-color-green\">25%</span> weapon damage.</p> <p class=\"subtle\">Unlocked at level <em>46</em>.</p>",
    elements: {
      a: "phy",
      b: "phy",
      c: "phy",
      d: "phy",
      e: "phy",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/barbarian_sprint.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">20</span> Fury</p><p>Increase movement speed by <span class=\"d3-color-green\">30%</span> for <span class=\"d3-color-green\">3</span> seconds.</p> <p class=\"special\">Defensive</p> <p class=\"subtle\">Unlocked at level <em>16</em>.</p> </div> </div>",
  },
  threateningshout: {
    a: "<p>Affected enemies are also taunted to attack you for <span class=\"d3-color-green\">4</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>43</em>.</p>",
    b: "<p>Affected enemies also have their movement speed reduced by <span class=\"d3-color-green\">60%</span>.</p> <p class=\"subtle\">Unlocked at level <em>23</em>.</p>",
    c: "<p>Enemies are badly shaken and have a <span class=\"d3-color-green\">15%</span> chance to drop health globes.</p> <p class=\"subtle\">Unlocked at level <em>37</em>.</p>",
    d: "<p>Enemies instead take <span class=\"d3-color-green\">25%</span> increased damage for <span class=\"d3-color-green\">6</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>28</em>.</p>",
    e: "<p>Enemies are severely demoralized. Each enemy has a <span class=\"d3-color-green\">100%</span> chance to flee in Fear for <span class=\"d3-color-green\">3</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>57</em>.</p>",
    elements: {
      a: "phy",
      b: "phy",
      c: "phy",
      d: "phy",
      e: "phy",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/barbarian_threateningshout.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Generate:</span> <span class=\"d3-color-green\">15</span> Fury<br/><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">10</span> seconds</p><p>Shout with great ferocity, reducing damage done by enemies within <span class=\"d3-color-green\">25</span> yards by <span class=\"d3-color-green\">20%</span> for <span class=\"d3-color-green\">15</span> seconds.</p> <p class=\"special\">Tactics</p> <p class=\"subtle\">Unlocked at level <em>14</em>.</p> </div> </div>",
  },
  warcry: {
    a: "<p>For the first <span class=\"d3-color-green\">5</span> seconds, gain an additional <span class=\"d3-color-green\">60%</span> increased Armor.</p> <p class=\"subtle\">Unlocked at level <em>32</em>.</p>",
    b: "<p>Increase Dodge Chance by <span class=\"d3-color-green\">30%</span> while affected by War Cry.</p> <p class=\"subtle\">Unlocked at level <em>49</em>.</p>",
    c: "<p>Increase resistance to all elements by <span class=\"d3-color-green\">20%</span> while affected by War Cry.</p> <p class=\"subtle\">Unlocked at level <em>60</em>.</p>",
    d: "<p>Increase Fury generated to <span class=\"d3-color-green\">50</span>.</p> <p class=\"subtle\">Unlocked at level <em>35</em>.</p>",
    e: "<p>Increase maximum Life by <span class=\"d3-color-green\">10%</span> and Life regeneration by <span class=\"d3-color-green\">13411</span> per second while affected by War Cry.</p> <p class=\"subtle\">Unlocked at level <em>41</em>.</p>",
    elements: {
      a: "phy",
      b: "phy",
      c: "phy",
      d: "phy",
      e: "phy",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/x1_barbarian_warcry_v2.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Generate:</span> <span class=\"d3-color-green\">20</span> Fury<br/><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">20</span> seconds</p><p>Unleash a rallying cry to increase Armor for you and all allies within <span class=\"d3-color-green\">100</span> yards by <span class=\"d3-color-green\">20%</span> for <span class=\"d3-color-green\">120</span> seconds.</p> <p class=\"special\">Tactics</p> <p class=\"subtle\">Unlocked at level <em>28</em>.</p> </div> </div>",
  },
  weaponthrow: {
    a: "<p>Increase thrown weapon damage to <span class=\"d3-color-green\">400%</span> weapon damage as Lightning.</p> <p class=\"subtle\">Unlocked at level <em>21</em>.</p>",
    b: "<p>The weapon ricochets to <span class=\"d3-color-green\">3</span> enemies within <span class=\"d3-color-green\">20</span> yards of each other.</p><p>Weapon Throw's damage turns into Fire.</p> <p class=\"subtle\">Unlocked at level <em>25</em>.</p>",
    c: "<p>Hurl a hammer with a <span class=\"d3-color-green\">40%</span> chance to Stun the enemy for <span class=\"d3-color-green\">1</span> second.</p> <p class=\"subtle\">Unlocked at level <em>33</em>.</p>",
    d: "<p>Increase Fury generated to <span class=\"d3-color-green\">9</span>.</p><p>Weapon Throw's damage turns into Fire.</p> <p class=\"subtle\">Unlocked at level <em>54</em>.</p>",
    e: "<p>Aim for the head, gaining a <span class=\"d3-color-green\">15%</span> chance of causing your enemy to be Confused and attack other enemies for <span class=\"d3-color-green\">3</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>42</em>.</p>",
    elements: {
      a: "lit",
      b: "fir",
      c: "phy",
      d: "fir",
      e: "phy",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/x1_barbarian_weaponthrow.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Generate:</span> <span class=\"d3-color-green\">6</span> Fury per attack</p><p>Hurl a throwing weapon at an enemy dealing <span class=\"d3-color-green\">275%</span> weapon damage.</p> <p class=\"special\">Primary</p> <p class=\"subtle\">Unlocked at level <em>17</em>.</p> </div> </div>",
  },
  whirlwind: {
    a: "<p>Turns Whirlwind into a torrent of magma that deals <span class=\"d3-color-green\">400%</span> weapon damage as Fire.</p> <p class=\"subtle\">Unlocked at level <em>59</em>.</p>",
    b: "<p>Generate harsh tornadoes that deal <span class=\"d3-color-green\">120%</span> weapon damage to enemies in their path.</p> <p class=\"subtle\">Unlocked at level <em>24</em>.</p>",
    c: "<p>Pull enemies from up to <span class=\"d3-color-green\">35</span> yards away towards you while whirlwinding.</p><p>Whirlwind's damage turns into Cold.</p> <p class=\"subtle\">Unlocked at level <em>29</em>.</p>",
    d: "<p>Gain <span class=\"d3-color-green\">1</span> Fury for every enemy struck.</p><p>Whirlwind's damage turns into Lightning.</p> <p class=\"subtle\">Unlocked at level <em>44</em>.</p>",
    e: "<p>Critical Hits restore <span class=\"d3-color-green\">1%</span> of your maximum Life.</p> <p class=\"subtle\">Unlocked at level <em>37</em>.</p>",
    elements: {
      a: "fir",
      b: "phy",
      c: "col",
      d: "lit",
      e: "phy",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/barbarian_whirlwind.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">10</span> Fury</p><p>Deliver multiple attacks to everything in your path for <span class=\"d3-color-green\">340%</span> weapon damage.</p><p>While whirlwinding, you move at <span class=\"d3-color-green\">100%</span> movement speed.</p> <p class=\"special\">Secondary</p> <p class=\"subtle\">Unlocked at level <em>20</em>.</p> </div> </div>",
  },
  wrathoftheberserker: {
    a: "<p>While active, gain <span class=\"d3-color-green\">50%</span> increased damage.</p> <p class=\"subtle\">Unlocked at level <em>40</em>.</p>",
    b: "<p>Activating Wrath of the Berserker deals <span class=\"d3-color-green\">3400%</span> weapon damage as Fire to all enemies within <span class=\"d3-color-green\">15</span> yards.</p> <p class=\"subtle\">Unlocked at level <em>36</em>.</p>",
    c: "<p>Reduce all damage taken by <span class=\"d3-color-green\">50%</span>.</p> <p class=\"subtle\">Unlocked at level <em>52</em>.</p>",
    d: "<p>While active, gain <span class=\"d3-color-green\">5364</span> Life per Fury spent.</p> <p class=\"subtle\">Unlocked at level <em>60</em>.</p>",
    e: "<p>While active, Critical Hits have a chance to cause an eruption of blood dealing <span class=\"d3-color-green\">300%</span> weapon damage to enemies within <span class=\"d3-color-green\">15</span> yards.</p> <p class=\"subtle\">Unlocked at level <em>46</em>.</p>",
    elements: {
      a: "phy",
      b: "fir",
      c: "phy",
      d: "phy",
      e: "phy",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/barbarian_wrathoftheberserker.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">120</span> seconds</p><p>Enter a berserker rage which raises several attributes for <span class=\"d3-color-green\">20</span> seconds.</p><p><span class=\"tooltip-icon-bullet\"></span> Critical Hit Chance: <span class=\"d3-color-green\">10%</span><br/><span class=\"tooltip-icon-bullet\"></span> Attack Speed: <span class=\"d3-color-green\">25%</span><br/><span class=\"tooltip-icon-bullet\"></span> Dodge Chance: <span class=\"d3-color-green\">20%</span><br/><span class=\"tooltip-icon-bullet\"></span> Movement Speed: <span class=\"d3-color-green\">20%</span></p> <p class=\"special\">Rage</p> <p class=\"subtle\">Unlocked at level <em>30</em>.</p> </div> </div>",
  },
};
DiabloCalc.passivetips.barbarian = {
  animosity: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/barbarian_passive_animosity.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>Increase all Fury generation by <span class=\"d3-color-green\">10%</span>.<br/>Increase maximum Fury by <span class=\"d3-color-green\">20</span>.</p><p>Fury is used to fuel your most powerful attacks.</p> <p class=\"subtle\">Unlocked at level <em>27</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"While most orders teach the merits of calming the seas of the soul, the guardians of Arreat have embraced the raging inner storm.\" —Chronicler Arlavoc</div> </div>",
  berserkerrage: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/barbarian_passive_berserkerrage.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>You deal <span class=\"d3-color-green\">25%</span> additional damage while near maximum Fury.</p> <p class=\"subtle\">Unlocked at level <em>20</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"You wouldn't like me when I'm angry.\" —Bannar the Berserker</div> </div>",
  bloodthirst: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/barbarian_passive_bloodthirst.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>Each point of Fury spent heals you for <span class=\"d3-color-green\">966</span> Life.</p><p>Heal amount is increased by <span class=\"d3-color-green\">1%</span> of your Health Globe Healing Bonus.</p> <p class=\"subtle\">Unlocked at level <em>24</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"Compassion is weakness. To press the advantage when an opponent calls for mercy is the way of true power.\" —Halaberd the Conqueror</div> </div>",
  boonofbulkathos: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/barbarian_passive_boonofbulkathos.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>Reduce the cooldowns of your:<br/><span class=\"tooltip-icon-bullet\"></span> Earthquake by <span class=\"d3-color-green\">15</span> seconds.<br/><span class=\"tooltip-icon-bullet\"></span> Call of the Ancients by <span class=\"d3-color-green\">30</span> seconds.<br/><span class=\"tooltip-icon-bullet\"></span> Wrath of the Berserker by <span class=\"d3-color-green\">30</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>60</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">The aid of the Immortal King shall come to those who have earned it.</div> </div>",
  brawler: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/barbarian_passive_brawler.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>As long as there are <span class=\"d3-color-green\">3</span> enemies within <span class=\"d3-color-green\">12</span> yards, all of your damage is increased by <span class=\"d3-color-green\">20%</span>.</p> <p class=\"subtle\">Unlocked at level <em>45</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"I have two blades, one for each of you.\" —Blademaster Kharne</div> </div>",
  earthenmight: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/x1_barbarian_passive_earthenmight.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>Gain <span class=\"d3-color-green\">30</span> Fury when Avalanche or Earthquake is triggered.</p> <p class=\"subtle\">Unlocked at level <em>64</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"My capital has become the cell in which I await my execution. The ground roars beneath me, announcing the presence of the wild men, as they rend and tear the foundations of the world and laugh. Oh, woe is me that I ever confused their savage ways for weakness.\"—Loren, Panep of Samauren</div> </div>",
  inspiringpresence: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/barbarian_passive_inspiringpresence.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>The duration of your shouts is doubled. After using a shout you and all allies within <span class=\"d3-color-green\">100</span> yards regenerate <span class=\"d3-color-green\">3%</span> of maximum Life per second for <span class=\"d3-color-green\">120</span> seconds.</p><p>Your shouts are:<br/><span class=\"tooltip-icon-bullet\"></span> Battle Rage<br/><span class=\"tooltip-icon-bullet\"></span> Threatening Shout<br/><span class=\"tooltip-icon-bullet\"></span> War Cry</p> <p class=\"subtle\">Unlocked at level <em>20</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"The enemy poured through the gap until Warmaster Karja impaled three demons at once on our battle standard, tossing their corpses into the fray below as she roared a rallying call from high atop the battlements.\" —The Battle of the Starless Night</div> </div>",
  juggernaut: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/barbarian_passive_juggernaut.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>The duration of control-impairing effects on you are reduced by <span class=\"d3-color-green\">50%</span>. In addition, whenever a Stun, Freeze, Fear, or Immobilize is cast on you, you have a chance to recover <span class=\"d3-color-green\">20%</span> of your maximum Life.</p> <p class=\"subtle\">Unlocked at level <em>50</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"I swear to you, we put a dozen arrows into him and he just stood back up. These so-called barbarians, these madmen of the north—there is no stopping them.\" —Soldier of Bastion's Keep</div> </div>",
  nervesofsteel: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/barbarian_passive_nervesofsteel.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>Fatal damage instead reduces you to <span class=\"d3-color-green\">15%</span> Life. For <span class=\"d3-color-green\">3</span> seconds afterward, you take <span class=\"d3-color-green\">95%</span> reduced damage and are immune to all control-impairing effects.</p><p>This effect may occur once every <span class=\"d3-color-green\">60</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>13</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"The trials begin with childhood; skinning ferocious beasts, climbing windswept cliffs and carrying weapons heavy enough to make a southern soldier weep. Is it any wonder that they never give ground?\" —Sir Aric of Duncraig</div> </div>",
  noescape: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/barbarian_passive_noescape.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>Increase the damage of Weapon Throw, Seismic Slam, Ancient Spear, and Avalanche by <span class=\"d3-color-green\">30%</span> against enemies more than <span class=\"d3-color-green\">15</span> yards away from you.</p> <p class=\"subtle\">Unlocked at level <em>35</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"Run if you must, but you'll only die tired.\" —Ooron Goons</div> </div>",
  poundofflesh: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/barbarian_passive_poundofflesh.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>When you are healed by a health globe, gain <span class=\"d3-color-green\">2%</span> Life regeneration per second and <span class=\"d3-color-green\">4%</span> increased movement speed for <span class=\"d3-color-green\">15</span> seconds. This bonus stacks up to <span class=\"d3-color-green\">5</span> times.</p> <p class=\"subtle\">Unlocked at level <em>10</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"When the sky bleeds, the crops grow tall. When our enemies bleed, we grow strong.\" —Chant of the Harvest</div> </div>",
  rampage: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/x1_barbarian_passive_rampage.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>Increase Strength by <span class=\"d3-color-green\">1%</span> for <span class=\"d3-color-green\">8</span> seconds after killing or assisting in killing an enemy. This effect stacks up to <span class=\"d3-color-green\">25</span> times.</p> <p class=\"subtle\">Unlocked at level <em>68</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"The battle was never ending, sapping our minds and bodies to the point of exhaustion. But they thrived amidst the carnage, every killing blow renewing their bloodlust. They couldn't be stopped.\" —Sergeant Peshkov on the Siege of the Barbarians, 1123 Anno Kehjistani </div> </div>",
  relentless: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/barbarian_passive_relentless.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>While below <span class=\"d3-color-green\">35%</span> Life, all skills cost <span class=\"d3-color-green\">50%</span> less Fury, Life per Fury Spent is doubled, and all damage taken is reduced by <span class=\"d3-color-green\">50%</span>.</p> <p class=\"subtle\">Unlocked at level <em>40</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">No matter the odds, some warriors simply refuse to fall.</div> </div>",
  ruthless: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/barbarian_passive_ruthless.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>You deal <span class=\"d3-color-green\">40%</span> additional damage to enemies below <span class=\"d3-color-green\">30%</span> health.</p> <p class=\"subtle\">Unlocked at level <em>10</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">The clans each paint their warriors in their own unique way. Some celebrate the mountain, others honor the fire, but the Targos clan worships the purifying virtue of pain.</div> </div>",
  superstition: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/barbarian_passive_superstition.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>Reduce all non-Physical damage by <span class=\"d3-color-green\">20%</span>. When you take damage from a ranged or elemental attack, you have a chance to gain <span class=\"d3-color-green\">2</span> Fury.</p> <p class=\"subtle\">Unlocked at level <em>30</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"The sorcery of the west has brought us nothing but blight. Strength built these walls, and strength will hold them.\" —Gruchac Hammerhand</div> </div>",
  swordandboard: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/x1_barbarian_passive_swordandboard.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>While wielding a shield, reduce all damage taken by <span class=\"d3-color-green\">30%</span> and reduce Fury costs by <span class=\"d3-color-green\">20%</span>.</p> <p class=\"subtle\">Unlocked at level <em>66</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"Turning away the attack of an enemy saps their resolve as surely as landing a blow of your own.\" —Battlemaster Kal-Jor</div> </div>",
  toughasnails: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/barbarian_passive_toughasnails.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>Increase Armor by <span class=\"d3-color-green\">25%</span>.<br/>Increase Thorns by <span class=\"d3-color-green\">100%</span>.</p> <p class=\"subtle\">Unlocked at level <em>30</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">After a while the scars serve as their own layer of armor.</div> </div>",
  unforgiving: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/barbarian_passive_unforgiving.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>You no longer degenerate Fury. Instead, you generate <span class=\"d3-color-green\">2</span> Fury every <span class=\"d3-color-green\">1</span> second.</p> <p class=\"subtle\">Unlocked at level <em>55</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"It was as if he suddenly came to know every grievous injury endured by his ancestors, and he had selected that very moment to exact their collective revenge.\" —Chronicler Arlavoc</div> </div>",
  weaponsmaster: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/barbarian_passive_weaponsmaster.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>Gain a bonus based on the weapon type of your main hand weapon:<br/>Swords/Daggers: <span class=\"d3-color-green\">8%</span> increased damage<br/>Maces/Axes: <span class=\"d3-color-green\">5%</span> Critical Hit Chance<br/>Polearms/Spears: <span class=\"d3-color-green\">8%</span> attack speed<br/>Mighty Weapons: <span class=\"d3-color-green\">2</span> Fury per hit</p> <p class=\"subtle\">Unlocked at level <em>16</em>.</p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"My men ambushed the traveler in the woods, but it was we who were surprised. Such keen senses, swift motions, flawless strikes. We never stood a chance.\" —Redjack the Bandit</div> </div>",
};
