if (!DiabloCalc.skilltips) DiabloCalc.skilltips = {};
if (!DiabloCalc.passivetips) DiabloCalc.passivetips = {};
DiabloCalc.skilltips.monk = {
  blindingflash: {
    a: "<p>You deal <span class=\"d3-color-green\">29%</span> increased damage for <span class=\"d3-color-green\">3</span> seconds after using Blinding Flash.</p> <p class=\"subtle\">Unlocked at level <em>55</em></p>",
    b: "<p>Each enemy you Blind restores <span class=\"d3-color-green\">10</span> Spirit.</p> <p class=\"subtle\">Unlocked at level <em>28</em></p>",
    c: "<p>Blinded enemies are also slowed by <span class=\"d3-color-green\">80%</span> for <span class=\"d3-color-green\">5</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>19</em></p>",
    d: "<p>Increase the duration enemies are blinded to <span class=\"d3-color-green\">6</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>12</em></p>",
    e: "<p>Allies within the Blinding Flash have their Life regeneration increased by <span class=\"d3-color-green\">26821</span> for <span class=\"d3-color-green\">3</span> seconds. The heal amount is increased by <span class=\"d3-color-green\">90%</span> of your Life per Second.</p> <p class=\"subtle\">Unlocked at level <em>41</em></p>",
    elements: {
      a: "hol",
      b: "hol",
      c: "hol",
      d: "hol",
      e: "hol",
      x: "hol",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/monk_blindingflash.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">15</span> seconds</p><p>Create a flash of light that blinds all enemies within <span class=\"d3-color-green\">20</span> yards for <span class=\"d3-color-green\">3</span> seconds. Elite enemies recover faster, but suffer a <span class=\"d3-color-green\">30%</span> chance to miss with attacks.</p> <p class=\"special\">Defensive</p> <p class=\"subtle\">Unlocked at level <em>4</em></p> </div> </div>",
  },
  breathofheaven: {
    a: "<p>Breath of Heaven also sears enemies for <span class=\"d3-color-green\">505%</span> weapon damage as Holy. </p> <p class=\"subtle\">Unlocked at level <em>14</em></p>",
    b: "<p>Increase the healing power of Breath of Heaven to <span class=\"d3-color-green\">139469 - 182383</span> Life.</p><p>Heal amount is increased by <span class=\"d3-color-green\">30%</span> of your Health Globe Healing Bonus.</p> <p class=\"subtle\">Unlocked at level <em>21</em></p>",
    c: "<p>Breath of Heaven increases the damage of your attacks by <span class=\"d3-color-green\">10%</span> for <span class=\"d3-color-green\">9</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>32</em></p>",
    d: "<p>Gain <span class=\"d3-color-green\">14</span> additional Spirit from Spirit generating attacks for <span class=\"d3-color-green\">5</span> seconds after using Breath of Heaven.</p> <p class=\"subtle\">Unlocked at level <em>44</em></p>",
    e: "<p>Allies healed by Breath of Heaven have their movement speed increased by <span class=\"d3-color-green\">30%</span> for <span class=\"d3-color-green\">3</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>59</em></p>",
    elements: {
      a: "hol",
      b: "hol",
      c: "hol",
      d: "hol",
      e: "hol",
      x: "hol",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/monk_breathofheaven.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">15</span> seconds</p><p>A blast of divine energy heals you and all allies within <span class=\"d3-color-green\">12</span> yards for <span class=\"d3-color-green\">69735 - 91192</span> Life.</p><p>Heal amount is increased by <span class=\"d3-color-green\">30%</span> of your Health Globe Healing Bonus.</p> <p class=\"special\">Defensive</p> <p class=\"subtle\">Unlocked at level <em>8</em></p> </div> </div>",
  },
  cripplingwave: {
    a: "<p>Increase damage to <span class=\"d3-color-green\">255%</span> weapon damage as Fire.</p> <p class=\"subtle\">Unlocked at level <em>17</em></p>",
    b: "<p>Crippling Wave's third attack has its range increased to <span class=\"d3-color-green\">17</span> yards and Freezes enemies for <span class=\"d3-color-green\">1</span> second.</p><p>Crippling Wave's damage turns into Cold.</p> <p class=\"subtle\">Unlocked at level <em>51</em></p>",
    c: "<p>Enemies hit by Crippling Wave deal <span class=\"d3-color-green\">20%</span> less damage for <span class=\"d3-color-green\">3</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>26</em></p>",
    d: "<p>Each enemy hit generates <span class=\"d3-color-green\">2.5</span> additional Spirit.</p><p>Crippling Wave's damage turns into Holy.</p> <p class=\"subtle\">Unlocked at level <em>36</em></p>",
    e: "<p>Enemies hit by Crippling Wave take <span class=\"d3-color-green\">10%</span> additional damage from all attacks for <span class=\"d3-color-green\">3</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>57</em></p>",
    elements: {
      a: "fir",
      b: "col",
      c: "phy",
      d: "hol",
      e: "phy",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/monk_cripplingwave.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Generate:</span> <span class=\"d3-color-green\">12</span> Spirit per attack</p><p>Unleash a series of large sweeping attacks that deal <span class=\"d3-color-green\">155%</span> weapon damage as Physical to all enemies in front of you.</p><p>Every third hit also dazes enemies within <span class=\"d3-color-green\">11</span> yards, slowing their movement speed by <span class=\"d3-color-green\">30%</span> and attack speed by <span class=\"d3-color-green\">20%</span> for <span class=\"d3-color-green\">3</span> seconds.</p> <p class=\"special\">Primary</p> <p class=\"subtle\">Unlocked at level <em>11</em></p> </div> </div>",
  },
  cyclonestrike: {
    a: "<p>Blast enemies with an explosion that deals <span class=\"d3-color-green\">454%</span> weapon damage as Fire.</p> <p class=\"subtle\">Unlocked at level <em>34</em></p>",
    b: "<p>Increase the distance enemies will be pulled towards you to <span class=\"d3-color-green\">34</span> yards.</p> <p class=\"subtle\">Unlocked at level <em>25</em></p>",
    c: "<p>Cyclone Strike heals you and all allies within <span class=\"d3-color-green\">24</span> yards for <span class=\"d3-color-green\">31036</span> Life.</p><p>Heal amount is increased by <span class=\"d3-color-green\">17%</span> of your Health Globe Healing Bonus.</p> <p class=\"subtle\">Unlocked at level <em>55</em></p>",
    d: "<p>Reduce the Spirit cost of Cyclone Strike to <span class=\"d3-color-green\">26</span> Spirit.</p><p>Cyclone Strike's damage turns into Lightning.</p> <p class=\"subtle\">Unlocked at level <em>21</em></p>",
    e: "<p>Enemies are Frozen for <span class=\"d3-color-green\">1.5</span> seconds after being pulled in.</p><p>Cyclone Strike's damage turns into Cold.</p> <p class=\"subtle\">Unlocked at level <em>41</em></p>",
    elements: {
      a: "fir",
      b: "hol",
      c: "hol",
      d: "lit",
      e: "col",
      x: "hol",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/monk_cyclonestrike.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">50</span> Spirit</p><p>Pull up to <span class=\"d3-color-green\">16</span> enemies within <span class=\"d3-color-green\">24</span> yards towards you, followed by a furious blast of energy that deals <span class=\"d3-color-green\">261%</span> weapon damage as Holy. </p> <p class=\"special\">Focus</p> <p class=\"subtle\">Unlocked at level <em>14</em></p> </div> </div>",
  },
  dashingstrike: {
    a: "<p>The last enemy you dash through is obliterated with a barrage of strikes, taking an additional <span class=\"d3-color-green\">975%</span> weapon damage as Physical over <span class=\"d3-color-green\">2</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>49</em></p>",
    b: "<p>Gain <span class=\"d3-color-green\">20%</span> increased movement speed for <span class=\"d3-color-green\">4</span> seconds after using Dashing Strike.</p><p>Dashing Strike's damage turns into Holy.</p> <p class=\"subtle\">Unlocked at level <em>15</em></p>",
    c: "<p>Gain <span class=\"d3-color-green\">40%</span> increased chance to Dodge for <span class=\"d3-color-green\">4</span> seconds after using Dashing Strike.</p><p>Dashing Strike's damage turns into Cold.</p> <p class=\"subtle\">Unlocked at level <em>23</em></p>",
    d: "<p>Increases maximum charges to <span class=\"d3-color-green\">3</span>.</p><p>Dashing Strike's damage turns into Lightning.</p> <p class=\"subtle\">Unlocked at level <em>32</em></p>",
    e: "<p>Gain <span class=\"d3-color-green\">15%</span> increased attack speed for <span class=\"d3-color-green\">4</span> seconds after using Dashing Strike.</p><p>Dashing Strike's damage turns into Fire.</p> <p class=\"subtle\">Unlocked at level <em>39</em></p>",
    elements: {
      a: "phy",
      b: "hol",
      c: "col",
      d: "lit",
      e: "fir",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/x1_monk_dashingstrike.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">1</span> Charge</p><p>Quickly dash up to <span class=\"d3-color-green\">50</span> yards, striking enemies along the way for <span class=\"d3-color-green\">370%</span> weapon damage as Physical.</p><p><span class=\"d3-color-yellow\">You gain a charge every <span class=\"d3-color-green\">8</span> seconds and can have up to <span class=\"d3-color-green\">2</span> charges stored at a time.</span></p> <p class=\"special\">Techniques</p> <p class=\"subtle\">Unlocked at level <em>9</em></p> </div> </div>",
  },
  deadlyreach: {
    a: "<p>Every third hit also increases the damage of all your attacks by <span class=\"d3-color-green\">15%</span> for <span class=\"d3-color-green\">5</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>54</em></p>",
    b: "<p>Increases chance to knock enemies up into the air to <span class=\"d3-color-green\">100%</span> and the second and third hits gain increased area of effect.</p> <p class=\"subtle\">Unlocked at level <em>9</em></p>",
    c: "<p>Every third hit randomly damages enemies within <span class=\"d3-color-green\">25</span> yards for <span class=\"d3-color-green\">215%</span> weapon damage as Lightning.</p> <p class=\"subtle\">Unlocked at level <em>34</em></p>",
    d: "<p>Each enemy hit with the third hit reduces the Spirit cost of your next Spirit Spender by <span class=\"d3-color-green\">8%</span>.</p><p>Deadly Reach's damage turns into Cold.</p> <p class=\"subtle\">Unlocked at level <em>47</em></p>",
    e: "<p>Increase damage to <span class=\"d3-color-green\">260%</span> weapon damage as Fire.</p> <p class=\"subtle\">Unlocked at level <em>18</em></p>",
    elements: {
      a: "phy",
      b: "phy",
      c: "lit",
      d: "col",
      e: "fir",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/monk_deadlyreach.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Generate:</span> <span class=\"d3-color-green\">12</span> Spirit per attack</p><p>Project lines of pure force over a short distance for <span class=\"d3-color-green\">150%</span> weapon damage as Physical.</p><p>Every third hit has a <span class=\"d3-color-green\">50%</span> chance to knock enemies up into the air.</p> <p class=\"special\">Primary</p> <p class=\"subtle\">Unlocked at level <em>3</em></p> </div> </div>",
  },
  epiphany: {
    a: "<p>Infuse yourself with sand, reducing damage taken by <span class=\"d3-color-green\">50%</span>.</p> <p class=\"subtle\">Unlocked at level <em>62</em></p>",
    b: "<p>Imbue yourself with water, causing your abilities to heal yourself and allies within <span class=\"d3-color-green\">30</span> yards for <span class=\"d3-color-green\">40232</span> Life.</p><p>Heal amount is increased by <span class=\"d3-color-green\">25%</span> of your Health Globe Healing Bonus.</p> <p class=\"subtle\">Unlocked at level <em>65</em></p>",
    c: "<p>Increases the bonus Spirit regeneration from Epiphany to <span class=\"d3-color-green\">45</span>.</p> <p class=\"subtle\">Unlocked at level <em>67</em></p>",
    d: "<p>Engulf yourself in flames, causing your attacks to assault enemies for <span class=\"d3-color-green\">353%</span> weapon damage as Fire.</p> <p class=\"subtle\">Unlocked at level <em>69</em></p>",
    e: "<p>Charge yourself with Lightning, causing your next attack after moving <span class=\"d3-color-green\">10</span> yards to Stun enemies for <span class=\"d3-color-green\">1.5</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>63</em></p>",
    elements: {
      a: "phy",
      b: "col",
      c: "hol",
      d: "fir",
      e: "lit",
      x: "hol",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/x1_monk_epiphany.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">60</span> seconds</p><p>Have an Epiphany, increasing your Spirit Regeneration per Second by <span class=\"d3-color-green\">20</span> and enabling your melee attacks to instantly dash to your target for <span class=\"d3-color-green\">15</span> seconds.</p> <p class=\"special\">Focus</p> <p class=\"subtle\">Unlocked at level <em>61</em></p> </div> </div>",
  },
  explodingpalm: {
    a: "<p>Exploding Palm arcs up to <span class=\"d3-color-green\">15</span> yards to another target.</p><p>Exploding Palm's damage turns into Lightning.</p> <p class=\"subtle\">Unlocked at level <em>44</em></p>",
    b: "<p>Exploding Palm no longer causes the enemy to bleed, but if the enemy dies while affected by Exploding Palm, they explode for <span class=\"d3-color-green\">6305%</span> weapon damage as Cold.</p> <p class=\"subtle\">Unlocked at level <em>36</em></p>",
    c: "<p>Enemies hit take <span class=\"d3-color-green\">20%</span> additional damage for <span class=\"d3-color-green\">9</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>18</em></p>",
    d: "<p>If the enemy explodes after bleeding, gain <span class=\"d3-color-green\">15</span> Spirit for each enemy caught in the blast.</p><p>Exploding Palm's damage turns into Holy.</p> <p class=\"subtle\">Unlocked at level <em>25</em></p>",
    e: "<p>Instead of bleeding, the enemy will burn for <span class=\"d3-color-green\">1875%</span> weapon damage as Fire over <span class=\"d3-color-green\">9</span> seconds. If the enemy dies while burning, it explodes causing all nearby enemies to burn for <span class=\"d3-color-green\">3260%</span> weapon damage as Fire over <span class=\"d3-color-green\">3</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>51</em></p>",
    elements: {
      a: "lit",
      b: "col",
      c: "phy",
      d: "hol",
      e: "fir",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/monk_explodingpalm.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">40</span> Spirit</p><p>Cause an enemy to Bleed for <span class=\"d3-color-green\">1200%</span> weapon damage as Physical over <span class=\"d3-color-green\">9</span> seconds. If the enemy dies while bleeding, it explodes and deals <span class=\"d3-color-green\">2770%</span> weapon damage as Physical damage to all nearby enemies.</p> <p class=\"special\">Techniques</p> <p class=\"subtle\">Unlocked at level <em>13</em></p> </div> </div>",
  },
  fistsofthunder: {
    a: "<p>Release an electric shockwave with every punch that hits all enemies within <span class=\"d3-color-green\">6</span> yards of your primary enemy for <span class=\"d3-color-green\">120%</span> weapon damage as Lightning and causes knockback with every third hit.</p> <p class=\"subtle\">Unlocked at level <em>6</em></p>",
    b: "<p>Every third hit also releases arcs of holy power, dealing <span class=\"d3-color-green\">240%</span> weapon damage as Holy to up to <span class=\"d3-color-green\">3</span> additional enemies.</p> <p class=\"subtle\">Unlocked at level <em>52</em></p>",
    c: "<p>Fists of Thunder applies Static Charge to enemies hit for <span class=\"d3-color-green\">6</span> seconds. Each time an enemy with Static Charge gets hit, there is a chance that every other enemy with Static Charge within <span class=\"d3-color-green\">40</span> yards takes <span class=\"d3-color-green\">180%</span> weapon damage as Lightning.</p> <p class=\"subtle\">Unlocked at level <em>30</em></p>",
    d: "<p>Increase Spirit generated to <span class=\"d3-color-green\">20</span>.</p><p>Fists of Thunder's damage turns into Physical.</p> <p class=\"subtle\">Unlocked at level <em>42</em></p>",
    e: "<p>Every third hit Freezes enemies for <span class=\"d3-color-green\">2</span> seconds.</p><p>Fists of Thunder's damage turns into Cold.</p> <p class=\"subtle\">Unlocked at level <em>14</em></p>",
    elements: {
      a: "lit",
      b: "hol",
      c: "lit",
      d: "phy",
      e: "col",
      x: "lit",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/monk_fistsofthunder.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Generate:</span> <span class=\"d3-color-green\">14</span> Spirit per attack</p><p>Teleport to your target and unleash a series of extremely fast punches that deal <span class=\"d3-color-green\">200%</span> weapon damage as Lightning.</p><p>Every third hit deals <span class=\"d3-color-green\">400%</span> weapon damage as Lightning split between all enemies in front of you.</p> <p class=\"special\">Primary</p> <p class=\"subtle\">Unlocked at level <em>1</em></p> </div> </div>",
  },
  innersanctuary: {
    a: "<p>Dash to the target location, granting a shield that absorbs up to <span class=\"d3-color-green\">107284</span> damage for <span class=\"d3-color-green\">3</span> seconds to allies within <span class=\"d3-color-green\">11</span> yards and then creating Inner Sanctuary.</p><p>Absorb amount is increased by <span class=\"d3-color-green\">28%</span> of your Health Globe Healing Bonus.</p> <p class=\"subtle\">Unlocked at level <em>43</em></p>",
    b: "<p>Inner Sanctuary duration is increased to <span class=\"d3-color-green\">8</span> seconds and cannot be passed by enemies.</p> <p class=\"subtle\">Unlocked at level <em>26</em></p>",
    c: "<p>Allies inside Inner Sanctuary are also immune to control impairing effects.</p> <p class=\"subtle\">Unlocked at level <em>37</em></p>",
    d: "<p>Allies inside Inner Sanctuary are healed for <span class=\"d3-color-green\">35779</span> every second.</p><p>Heal amount is increased by <span class=\"d3-color-green\">30%</span> of your Life per Second.</p> <p class=\"subtle\">Unlocked at level <em>31</em></p>",
    e: "<p>Enemies inside Inner Sanctuary take <span class=\"d3-color-green\">30%</span> increased damage and have their movement speed reduced by <span class=\"d3-color-green\">80%</span>.</p> <p class=\"subtle\">Unlocked at level <em>58</em></p>",
    elements: {
      a: "hol",
      b: "hol",
      c: "hol",
      d: "hol",
      e: "hol",
      x: "hol",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/x1_monk_innersanctuary.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">20</span> seconds</p><p>Create a runic circle of protection on the ground for <span class=\"d3-color-green\">6</span> seconds that reduces all damage taken by <span class=\"d3-color-green\">55%</span> for all allies inside.</p> <p class=\"special\">Defensive</p> <p class=\"subtle\">Unlocked at level <em>22</em></p> </div> </div>",
  },
  lashingtailkick: {
    a: "<p>Release a torrent of fire that burns enemies within <span class=\"d3-color-green\">10</span> yards for <span class=\"d3-color-green\">755%</span> weapon damage as Fire and an additional <span class=\"d3-color-green\">230%</span> weapon damage as Fire over <span class=\"d3-color-green\">3</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>7</em></p>",
    b: "<p>Hurl a column of fire that burns through enemies, causing <span class=\"d3-color-green\">755%</span> weapon damage as Fire to each enemy it strikes.</p> <p class=\"subtle\">Unlocked at level <em>28</em></p>",
    c: "<p>Enemies are chilled at long range, Slowing them by <span class=\"d3-color-green\">80%</span> for <span class=\"d3-color-green\">3</span> seconds.</p><p>Lashing Tail Kick's damage turns into Cold.</p> <p class=\"subtle\">Unlocked at level <em>52</em></p>",
    d: "<p>Unleash a large roundhouse kick that deals <span class=\"d3-color-green\">825%</span> weapon damage as Physical to enemies within <span class=\"d3-color-green\">15</span> yards.</p> <p class=\"subtle\">Unlocked at level <em>15</em></p>",
    e: "<p>Enemies hit are stunned for <span class=\"d3-color-green\">2</span> seconds.</p><p>Lashing Tail Kick's damage turns into Lightning.</p> <p class=\"subtle\">Unlocked at level <em>38</em></p>",
    elements: {
      a: "fir",
      b: "fir",
      c: "col",
      d: "phy",
      e: "lit",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/monk_lashingtailkick.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">50</span> Spirit</p><p>Unleash a deadly roundhouse kick that deals <span class=\"d3-color-green\">755%</span> weapon damage as Physical.</p> <p class=\"special\">Secondary</p> <p class=\"subtle\">Unlocked at level <em>2</em></p> </div> </div>",
  },
  mantraofconviction: {
    a: "<p><span class=\"d3-color-gold\">Passive:</span> Increase the strength of Mantra of Conviction so that enemies take <span class=\"d3-color-green\">16%</span> increased damage.</p> <p class=\"subtle\">Unlocked at level <em>35</em></p>",
    b: "<p><span class=\"d3-color-gold\">Passive:</span> Enemies affected by Mantra of Conviction take <span class=\"d3-color-green\">38%</span> weapon damage per second as Holy.</p> <p class=\"subtle\">Unlocked at level <em>60</em></p>",
    c: "<p><span class=\"d3-color-gold\">Passive:</span> Mantra of Conviction also slows the movement speed of enemies by <span class=\"d3-color-green\">80%</span>.</p> <p class=\"subtle\">Unlocked at level <em>47</em></p>",
    d: "<p><span class=\"d3-color-gold\">Passive:</span> Killing an enemy that is affected by Mantra of Conviction grants you and your allies <span class=\"d3-color-green\">30%</span> increased movement speed for <span class=\"d3-color-green\">3</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>55</em></p>",
    e: "<p><span class=\"d3-color-gold\">Passive:</span> Enemies affected by Mantra of Conviction deal <span class=\"d3-color-green\">15%</span> less damage.</p> <p class=\"subtle\">Unlocked at level <em>44</em></p>",
    elements: {
      a: "phy",
      b: "hol",
      c: "phy",
      d: "phy",
      e: "phy",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/x1_monk_mantraofconviction_v2.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">50</span> Spirit</p><p><span class=\"d3-color-gold\">Active:</span> Damage bonus is increased to <span class=\"d3-color-green\">20%</span> for <span class=\"d3-color-green\">3</span> seconds.</p><p><span class=\"d3-color-gold\">Passive:</span> Enemies within <span class=\"d3-color-green\">30</span> yards of you take <span class=\"d3-color-green\">10%</span> increased damage.</p><p><span class=\"d3-color-yellow\">Only one Mantra may be active at a time.</span></p> <p class=\"special\">Mantras</p> <p class=\"subtle\">Unlocked at level <em>30</em></p> </div> </div>",
  },
  mantraofhealing: {
    a: "<p><span class=\"d3-color-gold\">Passive:</span> Increase the Life regeneration granted by Mantra of Healing to <span class=\"d3-color-green\">21457</span> Life per Second.</p><p>Heal amount is increased by <span class=\"d3-color-green\">30%</span> of your Life per Second.</p> <p class=\"subtle\">Unlocked at level <em>31</em></p>",
    b: "<p><span class=\"d3-color-gold\">Passive:</span> Mantra of Healing also heals <span class=\"d3-color-green\">3576</span> Life when hitting an enemy.</p><p>Heal amount is increased by <span class=\"d3-color-green\">20%</span> of your Life per Hit.</p> <p class=\"subtle\">Unlocked at level <em>42</em></p>",
    c: "<p><span class=\"d3-color-gold\">Passive:</span> Mantra of Healing also increases maximum Life by <span class=\"d3-color-green\">20%</span>. </p> <p class=\"subtle\">Unlocked at level <em>48</em></p>",
    d: "<p><span class=\"d3-color-gold\">Passive:</span> Mantra of Healing also regenerates <span class=\"d3-color-green\">3</span> Spirit per second.</p> <p class=\"subtle\">Unlocked at level <em>38</em></p>",
    e: "<p><span class=\"d3-color-gold\">Passive:</span> Mantra of Healing also reduces damage taken by <span class=\"d3-color-green\">30%</span> when below <span class=\"d3-color-green\">50%</span> Life.</p> <p class=\"subtle\">Unlocked at level <em>53</em></p>",
    elements: {
      a: "hol",
      b: "hol",
      c: "hol",
      d: "hol",
      e: "hol",
      x: "hol",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/x1_monk_mantraofhealing_v2.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">50</span> Spirit</p><p><span class=\"d3-color-gold\">Active:</span> Shroud you and your allies with a mystical shield that absorbs up to <span class=\"d3-color-green\">62064</span> damage for <span class=\"d3-color-green\">3</span> seconds. Absorb amount is increased by <span class=\"d3-color-green\">15%</span> of your Health Globe Healing Bonus.</p><p><span class=\"d3-color-gold\">Passive:</span> You and your allies within <span class=\"d3-color-green\">60</span> yards gain <span class=\"d3-color-green\">10728</span> increased Life regeneration. The heal amount is increased by <span class=\"d3-color-green\">30%</span> of your Life per Second.</p><p><span class=\"d3-color-yellow\">Only one Mantra may be active at a time.</span></p> <p class=\"special\">Mantras</p> <p class=\"subtle\">Unlocked at level <em>26</em></p> </div> </div>",
  },
  mantraofretribution: {
    a: "<p><span class=\"d3-color-gold\">Passive:</span> Increase the amount of damage inflicted by Mantra of Retribution to <span class=\"d3-color-green\">202%</span> weapon damage as Fire.</p> <p class=\"subtle\">Unlocked at level <em>28</em></p>",
    b: "<p><span class=\"d3-color-gold\">Passive:</span> Mantra of Retribution also increases attack speed by <span class=\"d3-color-green\">10%</span> for you and your allies.</p> <p class=\"subtle\">Unlocked at level <em>36</em></p>",
    c: "<p><span class=\"d3-color-gold\">Passive:</span> Enemies damaged by Mantra of Retribution have a <span class=\"d3-color-green\">20%</span> chance to be stunned for <span class=\"d3-color-green\">3</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>41</em></p>",
    d: "<p><span class=\"d3-color-gold\">Passive:</span> Mantra of Retribution has a chance to restore <span class=\"d3-color-green\">3</span> Spirit when dealing damage.</p> <p class=\"subtle\">Unlocked at level <em>56</em></p>",
    e: "<p><span class=\"d3-color-gold\">Passive:</span> Enemies damaged by Mantra of Retribution have a <span class=\"d3-color-green\">75%</span> chance to suffer a feedback blast, dealing <span class=\"d3-color-green\">101%</span> weapon damage as Holy to itself and nearby enemies.</p> <p class=\"subtle\">Unlocked at level <em>59</em></p>",
    elements: {
      a: "fir",
      b: "hol",
      c: "hol",
      d: "hol",
      e: "hol",
      x: "hol",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/x1_monk_mantraofretribution_v2.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">50</span> Spirit</p><p><span class=\"d3-color-gold\">Active:</span> Increase the amount of damage dealt to <span class=\"d3-color-green\">202%</span> for <span class=\"d3-color-green\">3</span> seconds.</p><p><span class=\"d3-color-gold\">Passive:</span> You and your allies within <span class=\"d3-color-green\">60</span> yards deal <span class=\"d3-color-green\">101%</span> of your weapon damage as Holy to attackers when blocking, dodging or getting hit.</p><p><span class=\"d3-color-yellow\">Only one Mantra may be active at a time.</span></p> <p class=\"special\">Mantras</p> <p class=\"subtle\">Unlocked at level <em>21</em></p> </div> </div>",
  },
  mantraofsalvation: {
    a: "<p><span class=\"d3-color-gold\">Passive:</span> Mantra of Salvation also increases Dodge Chance by <span class=\"d3-color-green\">35%</span>.</p> <p class=\"subtle\">Unlocked at level <em>58</em></p>",
    b: "<p><span class=\"d3-color-gold\">Passive:</span> Increases the resistance to all elements bonus to <span class=\"d3-color-green\">40%</span>.</p> <p class=\"subtle\">Unlocked at level <em>50</em></p>",
    c: "<p><span class=\"d3-color-gold\">Passive:</span> Mantra of Salvation also increases Armor by <span class=\"d3-color-green\">20%</span>.</p> <p class=\"subtle\">Unlocked at level <em>24</em></p>",
    d: "<p><span class=\"d3-color-gold\">Passive:</span> Mantra of Salvation also increases movement speed by <span class=\"d3-color-green\">10%</span>.</p> <p class=\"subtle\">Unlocked at level <em>40</em></p>",
    e: "<p><span class=\"d3-color-gold\">Passive:</span> Mantra of Salvation also protects you and your allies when reduced below <span class=\"d3-color-green\">25%</span> Life, granting a shield that reduces damage taken by <span class=\"d3-color-green\">80%</span> for <span class=\"d3-color-green\">3</span> seconds.</p><p>Each target may be protected by this effect once every <span class=\"d3-color-green\">90</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>33</em></p>",
    elements: {
      a: "phy",
      b: "phy",
      c: "phy",
      d: "phy",
      e: "phy",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/x1_monk_mantraofevasion_v2.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">50</span> Spirit</p><p><span class=\"d3-color-gold\">Active:</span> You and nearby allies gain an additional <span class=\"d3-color-green\">20%</span> increased resistance to all elements for <span class=\"d3-color-green\">3</span> seconds.</p><p><span class=\"d3-color-gold\">Passive:</span> You and your allies within <span class=\"d3-color-green\">60</span> yards gain <span class=\"d3-color-green\">20%</span> increased resistance to all elements.</p><p><span class=\"d3-color-yellow\">Only one Mantra may be active at a time.</span></p> <p class=\"special\">Mantras</p> <p class=\"subtle\">Unlocked at level <em>19</em></p> </div> </div>",
  },
  mystically: {
    a: "<p><span class=\"d3-color-gold\">Active:</span> Your mystic ally splits into <span class=\"d3-color-green\">10</span> allies that explode for <span class=\"d3-color-green\">290%</span> weapon damage as Fire.</p><p><span class=\"d3-color-gold\">Passive:</span> A mystic ally fights by your side that increases your damage by <span class=\"d3-color-green\">10%</span>.</p> <p class=\"subtle\">Unlocked at level <em>31</em></p>",
    b: "<p><span class=\"d3-color-gold\">Active:</span> Your mystic ally performs <span class=\"d3-color-green\">7</span> wave attacks in quick succession, each dealing <span class=\"d3-color-green\">625%</span> weapon damage as Cold and Freezing enemies for <span class=\"d3-color-green\">3</span> seconds.</p><p><span class=\"d3-color-gold\">Passive:</span> A mystic ally fights by your side that infuses your attacks to Slow enemies by <span class=\"d3-color-green\">60%</span> for <span class=\"d3-color-green\">3</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>27</em></p>",
    c: "<p><span class=\"d3-color-gold\">Active:</span> Your mystic ally turns into a boulder for <span class=\"d3-color-green\">8</span> seconds. The boulder deals <span class=\"d3-color-green\">380%</span> weapon damage as Physical every second and rolls toward nearby enemies, knocking them up.</p><p><span class=\"d3-color-gold\">Passive:</span> A mystic ally fights by your side that increases your Life by <span class=\"d3-color-green\">20%</span>.</p> <p class=\"subtle\">Unlocked at level <em>53</em></p>",
    d: "<p><span class=\"d3-color-gold\">Active:</span> You gain <span class=\"d3-color-green\">100</span> Spirit.</p><p><span class=\"d3-color-gold\">Passive:</span> A mystic ally fights by your side that increases your Spirit Regeneration by <span class=\"d3-color-green\">4</span>.</p> <p class=\"subtle\">Unlocked at level <em>39</em></p>",
    e: "<p><span class=\"d3-color-gold\">Active:</span> Your mystic ally sacrifices itself to heal you for <span class=\"d3-color-green\">100%</span> of your maximum Life. The cooldown on Mystic Ally is increased to <span class=\"d3-color-green\">50</span> seconds.</p><p><span class=\"d3-color-gold\">Passive:</span> A mystic ally fights by your side that increases your Life per Second by <span class=\"d3-color-green\">10728</span>. The heal amount is increased by <span class=\"d3-color-green\">30%</span> of your Life per Second.</p> <p class=\"subtle\">Unlocked at level <em>46</em></p>",
    elements: {
      a: "fir",
      b: "col",
      c: "phy",
      d: "phy",
      e: "phy",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/x1_monk_mystically_v2.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">30</span> seconds</p><p><span class=\"d3-color-gold\">Active:</span> Your mystic ally has its damage increased by <span class=\"d3-color-green\">50%</span> for <span class=\"d3-color-green\">10</span> seconds.</p><p><span class=\"d3-color-gold\">Passive:</span> A mystic ally fights by your side. The ally deals <span class=\"d3-color-green\">130%</span> of your weapon damage as Physical per swing. When the ally dies, it is reborn after <span class=\"d3-color-green\">5</span> seconds.</p> <p class=\"special\">Focus</p> <p class=\"subtle\">Unlocked at level <em>22</em></p> </div> </div>",
  },
  serenity: {
    a: "<p>When activated, Serenity heals you for <span class=\"d3-color-green\">93874 - 120695</span> Life.</p><p>Heal amount is increased by <span class=\"d3-color-green\">40%</span> of your Health Globe Healing Bonus.</p> <p class=\"subtle\">Unlocked at level <em>23</em></p>",
    b: "<p>While under the effects of Serenity, your movement is unhindered.</p> <p class=\"subtle\">Unlocked at level <em>54</em></p>",
    c: "<p>Increase the duration of Serenity to <span class=\"d3-color-green\">4</span> seconds. </p> <p class=\"subtle\">Unlocked at level <em>47</em></p>",
    d: "<p>Protect allies within <span class=\"d3-color-green\">45</span> yards with a shield that removes control impairing effects and redirects up to <span class=\"d3-color-green\">120158</span> damage to you for <span class=\"d3-color-green\">3</span> seconds.</p><p>Shield amount is increased by <span class=\"d3-color-green\">40%</span> of your Health Globe Healing Bonus.</p> <p class=\"subtle\">Unlocked at level <em>39</em></p>",
    e: "<p>While under the effects of Serenity, enemies within <span class=\"d3-color-green\">20</span> yards take <span class=\"d3-color-green\">438%</span> weapon damage as Physical every second.</p> <p class=\"subtle\">Unlocked at level <em>29</em></p>",
    elements: {
      a: "hol",
      b: "hol",
      c: "hol",
      d: "hol",
      e: "phy",
      x: "hol",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/monk_serenity.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">16</span> seconds</p><p>You are enveloped in a protective shield that absorbs all incoming damage for <span class=\"d3-color-green\">3</span> seconds and grants immunity to all control impairing effects.</p><p><span class=\"d3-color-yellow\">This ability does not start its cooldown until after its effects expire.</span></p> <p class=\"special\">Defensive</p> <p class=\"subtle\">Unlocked at level <em>16</em></p> </div> </div>",
  },
  sevensidedstrike: {
    a: "<p>Teleport to the enemy and increase damage dealt to <span class=\"d3-color-green\">8285%</span> weapon damage as Lightning over <span class=\"d3-color-green\">7</span> strikes.</p> <p class=\"subtle\">Unlocked at level <em>23</em></p>",
    b: "<p>Seven-Sided Strike causes enemies to burn for <span class=\"d3-color-green\">630%</span> weapon damage as Fire over <span class=\"d3-color-green\">3</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>29</em></p>",
    c: "<p>Removes the Spirit cost and enemies hit by Seven-Sided Strike are Frozen for <span class=\"d3-color-green\">7</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>37</em></p>",
    d: "<p>Reduce the cooldown to <span class=\"d3-color-green\">14</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>43</em></p>",
    e: "<p>Each strike explodes, dealing <span class=\"d3-color-green\">877%</span> weapon damage as Holy in a <span class=\"d3-color-green\">7</span> yard radius around the enemy.</p> <p class=\"subtle\">Unlocked at level <em>60</em></p>",
    elements: {
      a: "lit",
      b: "fir",
      c: "col",
      d: "phy",
      e: "hol",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/monk_sevensidedstrike.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">50</span> Spirit<br/><span class=\"d3-color-gold\">Cooldown:</span> <span class=\"d3-color-green\">30</span> seconds</p><p>Dash rapidly between nearby enemies, dealing <span class=\"d3-color-green\">5677%</span> weapon damage over <span class=\"d3-color-green\">7</span> strikes.</p> <p class=\"special\">Focus</p> <p class=\"subtle\">Unlocked at level <em>17</em></p> </div> </div>",
  },
  sweepingwind: {
    a: "<p>Intensify the vortex, increasing the damage per stack to <span class=\"d3-color-green\">145%</span> weapon damage. This increases the damage with <span class=\"d3-color-green\">3</span> stacks to <span class=\"d3-color-green\">435%</span> weapon damage.</p> <p class=\"subtle\">Unlocked at level <em>33</em></p>",
    b: "<p>Increase the radius of the vortex to <span class=\"d3-color-green\">14</span> yards.</p><p>Sweeping Wind's damage turns into Fire.</p> <p class=\"subtle\">Unlocked at level <em>38</em></p>",
    c: "<p>While your vortex is at <span class=\"d3-color-green\">3</span> or more stacks, Critical Hits have a chance to spawn a lightning tornado that periodically electrocutes nearby enemies for <span class=\"d3-color-green\">95%</span> weapon damage as Lightning. Each spawned lightning tornado lasts <span class=\"d3-color-green\">3</span> seconds.</p><p>Sweeping Wind's damage turns into Lightning.</p> <p class=\"subtle\">Unlocked at level <em>56</em></p>",
    d: "<p>As long as your vortex is at <span class=\"d3-color-green\">3</span> or more stacks, you gain <span class=\"d3-color-green\">8</span> Spirit per second.</p><p>Sweeping Wind's damage turns into Holy.</p> <p class=\"subtle\">Unlocked at level <em>46</em></p>",
    e: "<p>While your vortex is at <span class=\"d3-color-green\">3</span> or more stacks, enemies damaged by Sweeping Wind for <span class=\"d3-color-green\">3</span> consecutive seconds are Frozen for <span class=\"d3-color-green\">2</span> seconds.</p><p>Enemies cannot be frozen by Sweeping Wind more than once every <span class=\"d3-color-green\">3</span> seconds.</p><p>Sweeping Wind's damage turns into Cold.</p> <p class=\"subtle\">Unlocked at level <em>27</em></p>",
    elements: {
      a: "phy",
      b: "fir",
      c: "lit",
      d: "hol",
      e: "col",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/monk_sweepingwind.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">75</span> Spirit</p><p>Surround yourself in a vortex that continuously deals <span class=\"d3-color-green\">105%</span> weapon damage to all enemies within <span class=\"d3-color-green\">10</span> yards. The vortex lasts <span class=\"d3-color-green\">6</span> seconds and is refreshed each time you strike an enemy with a melee attack. Landing a Critical Hit has a chance to increase the vortex effect up to <span class=\"d3-color-green\">3</span> stacks for a total of <span class=\"d3-color-green\">315%</span> weapon damage.</p> <p class=\"special\">Techniques</p> <p class=\"subtle\">Unlocked at level <em>21</em></p> </div> </div>",
  },
  tempestrush: {
    a: "<p>Enemies hit are knocked back and deal <span class=\"d3-color-green\">20%</span> reduced damage for <span class=\"d3-color-green\">4</span> seconds.</p><p>Tempest Rush's damage turns into Fire.</p> <p class=\"subtle\">Unlocked at level <em>56</em></p>",
    b: "<p>Increases your movement speed while using Tempest Rush by <span class=\"d3-color-green\">25%</span>.</p> <p class=\"subtle\">Unlocked at level <em>20</em></p>",
    c: "<p>Enemies within <span class=\"d3-color-green\">20</span> yards take an additional <span class=\"d3-color-green\">135%</span> weapon damage as Lightning every second.</p><p>Tempest Rush's damage turns into Lightning.</p> <p class=\"subtle\">Unlocked at level <em>45</em></p>",
    d: "<p>Reduce the Spirit cost of Tempest Rush to <span class=\"d3-color-green\">25</span> Spirit and increase its damage to <span class=\"d3-color-green\">500%</span> weapon damage as Holy.</p> <p class=\"subtle\">Unlocked at level <em>11</em></p>",
    e: "<p>After you stop channeling Tempest Rush, you cause an icy blast to all enemies within <span class=\"d3-color-green\">15</span> yards. The damage of the explosion increases by <span class=\"d3-color-green\">150%</span> weapon damage as Cold while channeling.</p><p>Tempest Rush's damage turns into Cold.</p> <p class=\"subtle\">Unlocked at level <em>33</em></p>",
    elements: {
      a: "fir",
      b: "phy",
      c: "lit",
      d: "hol",
      e: "col",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/monk_tempestrush.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">30</span> Spirit</p><p>Charge directly through your enemies, dealing <span class=\"d3-color-green\">390%</span> weapon damage while running.</p> <p class=\"special\">Secondary</p> <p class=\"subtle\">Unlocked at level <em>5</em></p> </div> </div>",
  },
  waveoflight: {
    a: "<p>Wave of Light Stuns enemies for <span class=\"d3-color-green\">1</span> second.</p><p>Wave of Light's damage turns into Physical.</p> <p class=\"subtle\">Unlocked at level <em>18</em></p>",
    b: "<p>Release bursts of energy that deal <span class=\"d3-color-green\">830%</span> weapon damage as Fire to nearby enemies.</p> <p class=\"subtle\">Unlocked at level <em>25</em></p>",
    c: "<p>Summon an ancient pillar that deals <span class=\"d3-color-green\">635%</span> weapon damage as Lightning, followed by <span class=\"d3-color-green\">785%</span> weapon damage as Lightning over <span class=\"d3-color-green\">3</span> seconds to enemies who remain in the area.</p> <p class=\"subtle\">Unlocked at level <em>57</em></p>",
    d: "<p>Increases the damage of Wave of Light to <span class=\"d3-color-green\">1045%</span> weapon damage as Holy.</p> <p class=\"subtle\">Unlocked at level <em>35</em></p>",
    e: "<p>Wave of Light deals an additional <span class=\"d3-color-green\">820%</span> weapon damage as Cold in a line.</p> <p class=\"subtle\">Unlocked at level <em>49</em></p>",
    elements: {
      a: "phy",
      b: "fir",
      c: "lit",
      d: "hol",
      e: "col",
      x: "hol",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/monk_waveoflight.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Cost:</span> <span class=\"d3-color-green\">75</span> Spirit</p><p>Focus a wave of light that crushes enemies for <span class=\"d3-color-green\">835%</span> weapon damage as Holy.</p> <p class=\"special\">Secondary</p> <p class=\"subtle\">Unlocked at level <em>12</em></p> </div> </div>",
  },
  wayofthehundredfists: {
    a: "<p>Perform a short dash with the first attack and enemies hit take an additional <span class=\"d3-color-green\">60%</span> weapon damage as Holy over <span class=\"d3-color-green\">3</span> seconds. Fists of Fury damage can stack multiple times on the same enemy.</p> <p class=\"subtle\">Unlocked at level <em>40</em></p>",
    b: "<p>Increase the number of hits in the second strike from <span class=\"d3-color-green\">7</span> to <span class=\"d3-color-green\">10</span> and increasing damage to <span class=\"d3-color-green\">423%</span> weapon damage as Lightning.</p> <p class=\"subtle\">Unlocked at level <em>24</em></p>",
    c: "<p>Critical Hits increase your attack speed and movement speed by <span class=\"d3-color-green\">5%</span> for <span class=\"d3-color-green\">5</span> seconds. This effect can stack up to <span class=\"d3-color-green\">3</span> times.</p><p>Way of the Hundred Fists's damage turns into Fire.</p> <p class=\"subtle\">Unlocked at level <em>32</em></p>",
    d: "<p>Each enemy hit with the third hit increases your damage by <span class=\"d3-color-green\">5%</span> for <span class=\"d3-color-green\">5</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>48</em></p>",
    e: "<p>Every third hit also generates a wave of wind that deals <span class=\"d3-color-green\">500%</span> weapon damage as Cold to enemies directly ahead of you.</p><p>Way of the Hundred Fists's damage turns into Cold.</p> <p class=\"subtle\">Unlocked at level <em>60</em></p>",
    elements: {
      a: "hol",
      b: "lit",
      c: "fir",
      d: "phy",
      e: "col",
      x: "phy",
    },
    x: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-skill d3-icon-skill-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/monk_wayofthehundredfists.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-gold\">Generate:</span> <span class=\"d3-color-green\">12</span> Spirit per attack</p><p>Unleash a rapid series of punches that strike enemies for <span class=\"d3-color-green\">190%</span> weapon damage as Physical.</p> <p class=\"special\">Primary</p> <p class=\"subtle\">Unlocked at level <em>15</em></p> </div> </div>",
  },
};
DiabloCalc.passivetips.monk = {
  alacrity: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/monk_passive_guidinglight.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>Increase the attack speed of Spirit Generators by <span class=\"d3-color-green\">15%</span>.</p> <p class=\"subtle\">Unlocked at level <em>40</em></p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"The harmony of mind, body, and spirit brings many blessings. A monk who has become as one will move like a storm crashing into the mountains. Fast, hard, and without hesitation.\" — Patriarch Anisim</div> </div>",
  beaconofytar: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/monk_passive_beaconofytar.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>Reduce all cooldowns by <span class=\"d3-color-green\">20%</span>.</p> <p class=\"subtle\">Unlocked at level <em>35</em></p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">It is only through hardship that we come to know our limits, and only through knowing our limits that we learn to shatter them.</div> </div>",
  chantofresonance: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/monk_passive_chantofresonance.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>The Spirit costs of Mantra activation effects are reduced by <span class=\"d3-color-green\">50%</span> and you gain <span class=\"d3-color-green\">4</span> Spirit every second when you have a Mantra learned.</p> <p class=\"subtle\">Unlocked at level <em>20</em></p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">The world continues on the noble path, each of us carrying another, all connected, ever onward.</div> </div>",
  combinationstrike: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/monk_passive_combinationstrike.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>Each different Spirit Generator you use increases your damage by <span class=\"d3-color-green\">10%</span> for <span class=\"d3-color-green\">3</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>50</em></p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">Master Wughan was not merely the first to perfect the six techniques. His true accomplishment was in weaving them into a style all his own.</div> </div>",
  determination: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/p1_monk_passive_provocation.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>Each enemy within <span class=\"d3-color-green\">12</span> yards increases your damage by <span class=\"d3-color-green\">4%</span>, up to a maximum of <span class=\"d3-color-green\">20%</span>.</p> <p class=\"subtle\">Unlocked at level <em>30</em></p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"Where a lesser man despairs at the number of his foes, a monk of Ivgorod prays for more.\" —Master Wughan</div> </div>",
  exaltedsoul: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/monk_passive_exaltedsoul.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>Increase maximum Spirit by <span class=\"d3-color-green\">50</span> and increase Spirit Regeneration by <span class=\"d3-color-green\">4</span> per second.</p><p>Spirit fuels your defensive and offensive abilities.</p> <p class=\"subtle\">Unlocked at level <em>13</em></p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"Endeavor to be one with the hidden truth and you will soar beyond the sky.\" —Waykeeper Tzo Krin</div> </div>",
  fleetfooted: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/monk_passive_fleetfooted.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>Increase movement speed by <span class=\"d3-color-green\">10%</span>.</p> <p class=\"subtle\">Unlocked at level <em>10</em></p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">Strength out of place is no strength at all.</div> </div>",
  harmony: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/p1_monk_passive_harmony.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p><span class=\"d3-color-green\">40%</span> of your single elemental resistances from items instead increases your resistance to all elements.</p> <p class=\"subtle\">Unlocked at level <em>45</em></p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">Ice hunters brave months of frozen darkness. Desert traders bear relentless, scorching sun. This world is ours to endure.</div> </div>",
  momentum: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/x1_monk_passive_momentum.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>Moving <span class=\"d3-color-green\">25</span> yards increases your damage by <span class=\"d3-color-green\">20%</span> for <span class=\"d3-color-green\">6</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>66</em></p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">Always in motion, flowing like water.</div> </div>",
  mythicrhythm: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/x1_monk_passive_mythicrhythm.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>Every third hit from a Spirit Generator increases the damage of your next damaging Spirit Spender by <span class=\"d3-color-green\">40%</span>.</p> <p class=\"subtle\">Unlocked at level <em>68</em></p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"The spirit is inconquerable, it folds in upon itself, it grows, always strengthening.\" — Patriarch Anisim</div> </div>",
  neardeathexperience: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/monk_passive_neardeathexperience.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>When receiving fatal damage, you instead restore <span class=\"d3-color-green\">35%</span> Life and <span class=\"d3-color-green\">35%</span> Spirit and are immune to damage and control impairing effects for <span class=\"d3-color-green\">2</span> seconds.</p><p>This effect may occur once every <span class=\"d3-color-green\">60</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>58</em></p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"We do not see what has been done, we only see what remains to be done.\" —Mantra of the Monks of Ivgorod</div> </div>",
  relentlessassault: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/p1_monk_passive_relentlessassault.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>You deal <span class=\"d3-color-green\">20%</span> more damage to enemies that are Blind, Frozen or Stunned.</p> <p class=\"subtle\">Unlocked at level <em>30</em></p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"Vylnas refused to fall, despite his mortal wounds. The last of the Five Monks, he would not let his brothers' sacrifice be in vain; his determination turned the tide of the war, eventually leading to the full withdrawal of Entsteig's forces from the field of battle.\" —Poldamyr's Chronicle of the War of Thorns</div> </div>",
  resolve: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/monk_passive_resolve.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>Damage you deal reduces enemy damage by <span class=\"d3-color-green\">20%</span> for <span class=\"d3-color-green\">4</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>10</em></p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"It is not our place to make demands of nature, nor to acquiesce to those who would. First we learn what is right, then we protect what is right.\" —Master Wughan</div> </div>",
  seizetheinitiative: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/monk_passive_seizetheinitiative.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>Dealing damage to enemies above <span class=\"d3-color-green\">75%</span> Life increases your attack speed by <span class=\"d3-color-green\">30%</span> for <span class=\"d3-color-green\">4</span> seconds.</p> <p class=\"subtle\">Unlocked at level <em>20</em></p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">The Monks of Ivgorod are trained to move like water — flowing freely into open spaces and crashing hard against their foes.</div> </div>",
  sixthsense: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/monk_passive_sixthsense.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>Reduce all non-Physical damage taken by <span class=\"d3-color-green\">25%</span>.</p> <p class=\"subtle\">Unlocked at level <em>27</em></p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">The final test of the Serpent's Form takes place in \"The Pit of 12 Vipers.\" The initiates are not told about the 13th.</div> </div>",
  theguardianspath: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/monk_passive_theguardianspath.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>While dual-wielding, you gain a <span class=\"d3-color-green\">35%</span> chance to dodge incoming attacks. While using a two-handed weapon, all Spirit generation is increased by <span class=\"d3-color-green\">15%</span>.</p> <p class=\"subtle\">Unlocked at level <em>24</em></p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"No weapon can overcome the weakness of an undisciplined mind. They can only serve as an extension of the self.\" —Waykeeper Tzo Krin </div> </div>",
  transcendence: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/monk_passive_transcendence.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>Every point of Spirit spent heals you for <span class=\"d3-color-green\">429</span> Life.</p><p>Heal amount is increased by <span class=\"d3-color-green\">0.4%</span> of your Health Globe Healing Bonus.</p> <p class=\"subtle\">Unlocked at level <em>16</em></p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">A life unlived is no different from death.</div> </div>",
  unity: "<div class=\"tooltip-body \"> <span class=\"d3-icon d3-icon-trait d3-icon-trait-64 \" style=\"background-image: url('http://media.blizzard.com/d3/icons/skills/64/x1_monk_passive_unity.png'); width: 64px; height: 64px;\"> <span class=\"frame\"></span> </span> <div class=\"description\"> <p>Each ally affected by your Mantras increases your damage by <span class=\"d3-color-green\">5%</span>, up to a maximum of <span class=\"d3-color-green\">20%</span>, and has <span class=\"d3-color-green\">5%</span> increased damage.</p> <p class=\"subtle\">Unlocked at level <em>64</em></p> </div> </div> <div class=\"tooltip-extension \"> <div class=\"flavor\">\"I thought I was done for, trampled into the snow. Suddenly I felt her hand on my shoulder. The warmth returned to my bones, and together we repelled the beasts.\" —Legends of the North</div> </div>",
};
