var Passives = {};
var Skills = {};
Passives["barbarian"] = {
  "Passive": "Trait_Barbarian_Fury",
  "Pound of Flesh": "Barbarian_Passive_PoundOfFlesh",
  "Ruthless": "Barbarian_Passive_Ruthless",
  "Nerves of Steel": "Barbarian_Passive_NervesOfSteel",
  "Weapons Master": "Barbarian_Passive_WeaponsMaster",
  "Inspiring Presence": "Barbarian_Passive_InspiringPresence",
  "Berserker Rage": "Barbarian_Passive_BerserkerRage",
  "Bloodthirst": "Barbarian_Passive_Bloodthirst",
  "Animosity": "Barbarian_Passive_Animosity",
  "Superstition": "Barbarian_Passive_Superstition",
  "Tough as Nails": "Barbarian_Passive_ToughAsNails",
  "No Escape": "Barbarian_Passive_NoEscape",
  "Relentless": "Barbarian_Passive_Relentless",
  "Brawler": "Barbarian_Passive_Brawler",
  "Juggernaut": "Barbarian_Passive_Juggernaut",
  "Unforgiving": "Barbarian_Passive_Unforgiving",
  "Boon of Bul-Kathos": "Barbarian_Passive_BoonOfBulKathos",
  "Earthen Might": "X1_Barbarian_Passive_EarthenMight",
  "Rampage": "X1_Barbarian_Passive_Rampage",
  "Sword and Board": "X1_Barbarian_Passive_SwordAndBoard",
};
Skills["barbarian"] = {
  "Bash": "Barbarian_Bash",
  "Cleave": "Barbarian_Cleave",
  "Threatening Shout": "Barbarian_ThreateningShout",
  "Ground Stomp": "Barbarian_GroundStomp",
  "Hammer of the Ancients": "Barbarian_HammerOfTheAncients",
  "Ignore Pain": "Barbarian_IgnorePain",
  "Sprint": "Barbarian_Sprint",
  "Ancient Spear": "X1_Barbarian_AncientSpear",
  "Furious Charge": "Barbarian_FuriousCharge",
  "Battle Rage": "Barbarian_BattleRage",
  "Wrath of the Berserker": "Barbarian_WrathOfTheBerserker",
  "Earthquake": "Barbarian_Earthquake",
  "Leap": "Barbarian_Leap",
  "Weapon Throw": "X1_Barbarian_WeaponThrow",
  "Rend": "Barbarian_Rend",
  "Frenzy": "Barbarian_Frenzy",
  "Call of the Ancients": "Barbarian_CallOfTheAncients",
  "Seismic Slam": "Barbarian_SeismicSlam",
  "Whirlwind": "Barbarian_Whirlwind",
  "Revenge": "Barbarian_Revenge",
  "Overpower": "Barbarian_Overpower",
  "Avalanche": "X1_Barbarian_Avalanche_v2",
  "War Cry": "X1_Barbarian_WarCry_v2",
};
Passives["demonhunter"] = {
  "Thrill of the Hunt": "DemonHunter_Passive_ThrillOfTheHunt",
  "Tactical Advantage": "DemonHunter_Passive_TacticalAdvantage",
  "Blood Vengeance": "DemonHunter_Passive_Vengeance",
  "Steady Aim": "DemonHunter_Passive_SteadyAim",
  "Cull the Weak": "DemonHunter_Passive_CullTheWeak",
  "Night Stalker": "DemonHunter_Passive_NightStalker",
  "Brooding": "DemonHunter_Passive_Brooding",
  "Hot Pursuit": "DemonHunter_Passive_HotPursuit",
  "Archery": "DemonHunter_Passive_Archery",
  "Numbing Traps": "DemonHunter_Passive_NumbingTraps",
  "Perfectionist": "DemonHunter_Passive_Perfectionist",
  "Custom Engineering": "DemonHunter_Passive_CustomEngineering",
  "Grenadier": "DemonHunter_Passive_Grenadier",
  "Sharpshooter": "DemonHunter_Passive_Sharpshooter",
  "Ballistics": "DemonHunter_Passive_Ballistics",
  "Ambush": "X1_DemonHunter_Passive_Ambush",
  "Awareness": "X1_DemonHunter_Passive_Awareness",
  "Single Out": "X1_DemonHunter_Passive_SingleOut",
};
Skills["demonhunter"] = {
  "Multishot": "DemonHunter_Multishot",
  "Fan of Knives": "DemonHunter_FanOfKnives",
  "Bolas": "DemonHunter_Bolas",
  "Entangling Shot": "X1_DemonHunter_EntanglingShot",
  "Vault": "DemonHunter_Vault",
  "Spike Trap": "DemonHunter_SpikeTrap",
  "Grenade": "DemonHunter_Grenades",
  "Chakram": "DemonHunter_Chakram",
  "Caltrops": "DemonHunter_Caltrops",
  "Cluster Arrow": "DemonHunter_ClusterArrow",
  "Marked for Death": "DemonHunter_MarkedForDeath",
  "Sentry": "DemonHunter_Sentry",
  "Hungering Arrow": "DemonHunter_HungeringArrow",
  "Smoke Screen": "DemonHunter_SmokeScreen",
  "Shadow Power": "DemonHunter_ShadowPower",
  "Rain of Vengeance": "DemonHunter_RainOfVengeance",
  "Elemental Arrow": "DemonHunter_ElementalArrow",
  "Rapid Fire": "DemonHunter_RapidFire",
  "Preparation": "DemonHunter_Preparation",
  "Impale": "DemonHunter_Impale",
  "Companion": "X1_DemonHunter_Companion",
  "Strafe": "DemonHunter_Strafe",
  "Vengeance": "X1_DemonHunter_Vengeance",
  "Evasive Fire": "X1_DemonHunter_EvasiveFire",
};
Passives["enchantress"] = {
};
Skills["enchantress"] = {
  "Disorient": "Enchantress_Disorient",
  "Charm": "Enchantress_Charm",
  "Missile Ward": "Enchantress_MissileWard",
  "Powered Armor": "Enchantress_PoweredArmor",
  "Focused Mind": "Enchantress_FocusedMind",
  "Erosion": "Enchantress_ScorchedEarth",
  "Mass Control": "Enchantress_MassCharm",
  "Forceful Push": "Enchantress_ForcefulPush",
};
Passives["monk"] = {
  "": "Trait_Monk_Spirit",
  "Resolve": "Monk_Passive_Resolve",
  "Fleet Footed": "Monk_Passive_FleetFooted",
  "Exalted Soul": "Monk_Passive_ExaltedSoul",
  "Transcendence": "Monk_Passive_Transcendence",
  "Chant of Resonance": "Monk_Passive_ChantOfResonance",
  "The Guardian's Path": "Monk_Passive_TheGuardiansPath",
  "Sixth Sense": "Monk_Passive_SixthSense",
  "Determination": "p1_Monk_Passive_Provocation",
  "Beacon of Ytar": "Monk_Passive_BeaconOfYtar",
  "Alacrity": "Monk_Passive_GuidingLight",
  "Harmony": "p1_Monk_Passive_Harmony",
  "Combination Strike": "Monk_Passive_CombinationStrike",
  "Near Death Experience": "Monk_Passive_NearDeathExperience",
  "Mythic Rhythm": "X1_Monk_Passive_MythicRhythm",
  "Momentum": "X1_Monk_Passive_Momentum",
  "Unity": "X1_Monk_Passive_Unity",
  "Relentless Assault": "p1_Monk_Passive_RelentlessAssault",
  "Seize the Initiative": "Monk_Passive_SeizeTheInitiative",
};
Skills["monk"] = {
  "Fists of Thunder": "Monk_FistsofThunder",
  "Deadly Reach": "Monk_DeadlyReach",
  "Breath of Heaven": "Monk_BreathOfHeaven",
  "Cyclone Strike": "Monk_CycloneStrike",
  "Serenity": "Monk_Serenity",
  "Crippling Wave": "Monk_CripplingWave",
  "Mantra of Healing": "X1_Monk_MantraOfHealing_v2",
  "Way of the Hundred Fists": "Monk_WayOfTheHundredFists",
  "Mantra of Conviction": "X1_Monk_MantraOfConviction_v2",
  "Dashing Strike": "X1_Monk_DashingStrike",
  "Inner Sanctuary": "X1_Monk_InnerSanctuary",
  "Sweeping Wind": "Monk_SweepingWind",
  "Mantra of Retribution": "X1_Monk_MantraOfRetribution_v2",
  "Exploding Palm": "Monk_ExplodingPalm",
  "Seven-Sided Strike": "Monk_SevenSidedStrike",
  "Wave of Light": "Monk_WaveOfLight",
  "Mantra of Salvation": "X1_Monk_MantraOfEvasion_v2",
  "Lashing Tail Kick": "Monk_LashingTailKick",
  "Tempest Rush": "Monk_TempestRush",
  "Mystic Ally": "X1_Monk_MysticAlly_v2",
  "Blinding Flash": "Monk_BlindingFlash",
  "Epiphany": "X1_Monk_Epiphany",
};
Passives["scoundrel"] = {
};
Skills["scoundrel"] = {
  "Hysteria": "Scoundrel_Hysteria",
  "Crippling Shot": "Scoundrel_CripplingShot",
  "Poison Bolts": "Scoundrel_PoisonArrow",
  "Dirty Fighting": "Scoundrel_DirtyFighting",
  "Powered Shot": "Scoundrel_PowerShot",
  "Multishot": "X1_Scoundrel_Multishot",
  "Vanish": "Scoundrel_Vanish",
  "Anatomy": "Scoundrel_Anatomy",
};
Passives["templar"] = {
};
Skills["templar"] = {
  "Heal": "Templar_Heal_110",
  "Charge": "Templar_ShieldCharge",
  "Loyalty": "Templar_Loyalty",
  "Intimidate": "Templar_Intimidate",
  "Inspire": "Templar_Inspire",
  "Intervene": "Templar_Intervene",
  "Onslaught": "Templar_Onslaught",
  "Guardian": "Templar_Guardian",
};
Passives["witchdoctor"] = {
  "Summon Zombie Dogs": "Trait_Witchdoctor_ZombieDogSpawner_Passive",
  "Jungle Fortitude": "Witchdoctor_Passive_JungleFortitude",
  "Circle of Life": "Witchdoctor_Passive_CircleOfLife",
  "Spiritual Attunement": "Witchdoctor_Passive_SpiritualAttunement",
  "Gruesome Feast": "Witchdoctor_Passive_GruesomeFeast",
  "Blood Ritual": "Witchdoctor_Passive_BloodRitual",
  "Bad Medicine": "Witchdoctor_Passive_BadMedicine",
  "Zombie Handler": "Witchdoctor_Passive_ZombieHandler",
  "Pierce the Veil": "Witchdoctor_Passive_PierceTheVeil",
  "Spirit Vessel": "Witchdoctor_Passive_SpiritVessel",
  "Fetish Sycophants": "Witchdoctor_Passive_FetishSycophants",
  "Rush of Essence": "Witchdoctor_Passive_RushOfEssence",
  "Vision Quest": "Witchdoctor_Passive_VisionQuest",
  "Fierce Loyalty": "Witchdoctor_Passive_FierceLoyalty",
  "Grave Injustice": "Witchdoctor_Passive_GraveInjustice",
  "Tribal Rites": "Witchdoctor_Passive_TribalRites",
  "Creeping Death": "Witchdoctor_Passive_CreepingDeath",
  "Swampland Attunement": "Witchdoctor_Passive_PhysicalAttunement",
  "Midnight Feast": "Witchdoctor_Passive_MidnightFeast",
};
Skills["witchdoctor"] = {
  "Summon Zombie Dogs": "Witchdoctor_SummonZombieDog",
  "Poison Dart": "Witchdoctor_PoisonDart",
  "Corpse Spiders": "Witchdoctor_CorpseSpider",
  "Haunt": "Witchdoctor_Haunt",
  "Grasp of the Dead": "Witchdoctor_GraspOfTheDead",
  "Hex": "Witchdoctor_Hex",
  "Soul Harvest": "Witchdoctor_SoulHarvest",
  "Sacrifice": "Witchdoctor_Sacrifice",
  "Locust Swarm": "Witchdoctor_Locust_Swarm",
  "Spirit Barrage": "Witchdoctor_SpiritBarrage",
  "Horrify": "Witchdoctor_Horrify",
  "Firebomb": "Witchdoctor_Firebomb",
  "Acid Cloud": "Witchdoctor_AcidCloud",
  "Gargantuan": "Witchdoctor_Gargantuan",
  "Mass Confusion": "Witchdoctor_MassConfusion",
  "Spirit Walk": "Witchdoctor_SpiritWalk",
  "Fetish Army": "Witchdoctor_FetishArmy",
  "Zombie Charger": "Witchdoctor_ZombieCharger",
  "Firebats": "Witchdoctor_Firebats",
  "Plague of Toads": "Witchdoctor_PlagueOfToads",
  "Big Bad Voodoo": "Witchdoctor_BigBadVoodoo",
  "Wall of Death": "Witchdoctor_WallOfZombies",
  "Piranhas": "Witchdoctor_Piranhas",
};
Passives["wizard"] = {
  "Dominance": "x1_Wizard_Passive_ArcaneAegis",
  "Glass Cannon": "Wizard_Passive_GlassCannon",
  "Prodigy": "Wizard_Passive_Prodigy",
  "Astral Presence": "Wizard_Passive_AstralPresence",
  "Illusionist": "Wizard_Passive_Illusionist",
  "Cold Blooded": "Wizard_Passive_ColdBlooded",
  "Galvanizing Ward": "Wizard_Passive_GalvanizingWard",
  "Power Hungry": "Wizard_Passive_PowerHungry",
  "Blur": "Wizard_Passive_Blur",
  "Evocation": "Wizard_Passive_Evocation",
  "Arcane Dynamo": "Wizard_Passive_ArcaneDynamo",
  "Unstable Anomaly": "Wizard_Passive_UnstableAnomaly",
  "Paralysis": "Wizard_Passive_Paralysis",
  "Unwavering Will": "X1_Wizard_Passive_UnwaveringWill",
  "Conflagration": "Wizard_Passive_Conflagration",
  "Audacity": "X1_Wizard_Passive_Audacity",
  "Temporal Flux": "Wizard_Passive_TemporalFlux",
  "Elemental Exposure": "X1_Wizard_Passive_ElementalExposure",
};
Skills["wizard"] = {
  "Spectral Blade": "Wizard_SpectralBlade",
  "Shock Pulse": "Wizard_ShockPulse",
  "Ice Armor": "Wizard_IceArmor",
  "Wave of Force": "Wizard_WaveOfForce",
  "Mirror Image": "Wizard_MirrorImage",
  "Frost Nova": "Wizard_FrostNova",
  "Electrocute": "Wizard_Electrocute",
  "Arcane Orb": "Wizard_ArcaneOrb",
  "Energy Twister": "Wizard_EnergyTwister",
  "Explosive Blast": "Wizard_ExplosiveBlast",
  "Diamond Skin": "Wizard_DiamondSkin",
  "Slow Time": "Wizard_SlowTime",
  "Hydra": "Wizard_Hydra",
  "Blizzard": "Wizard_Blizzard",
  "Storm Armor": "Wizard_StormArmor",
  "Magic Missile": "Wizard_MagicMissile",
  "Magic Weapon": "Wizard_MagicWeapon",
  "Meteor": "Wizard_Meteor",
  "Disintegrate": "Wizard_Disintegrate",
  "Ray of Frost": "Wizard_RayOfFrost",
  "Energy Armor": "Wizard_EnergyArmor",
  "Familiar": "Wizard_Familiar",
  "Arcane Torrent": "Wizard_ArcaneTorrent",
  "Archon": "Wizard_Archon",
  "Teleport": "Wizard_Teleport",
  "Black Hole": "X1_Wizard_Wormhole",
};
Passives["crusader"] = {
  "Heavenly Strength": "X1_Crusader_Passive_HeavenlyStrength",
  "Hold Your Ground": "X1_Crusader_Passive_HoldYourGround",
  "Indestructible": "X1_Crusader_Passive_Indestructible",
  "Vigilant": "X1_Crusader_Passive_Vigilant",
  "Insurmountable": "X1_Crusader_Passive_Insurmountable",
  "Long Arm of the Law": "X1_Crusader_Passive_LongArmOfTheLaw",
  "Wrathful": "X1_Crusader_Passive_Wrathful",
  "Iron Maiden": "X1_Crusader_Passive_IronMaiden",
  "Finery": "X1_Crusader_Passive_Finery",
  "Holy Cause": "X1_Crusader_Passive_HolyCause",
  "Lord Commander": "X1_Crusader_Passive_LordCommander",
  "Blunt": "X1_Crusader_Passive_Blunt",
  "Towering Shield": "X1_Crusader_Passive_ToweringShield",
  "Righteousness": "X1_Crusader_Passive_Righteousness",
  "Renewal": "X1_Crusader_Passive_Renewal",
  "Divine Fortress": "X1_Crusader_Passive_DivineFortress",
  "Fervor": "X1_Crusader_Passive_Fervor",
  "Fanaticism": "X1_Crusader_Passive_NephalemMajesty",
};
Skills["crusader"] = {
  "Blessed Shield": "X1_Crusader_BlessedShield",
  "Sweep Attack": "X1_Crusader_SweepAttack",
  "Heaven's Fury": "X1_Crusader_HeavensFury3",
  "Phalanx": "x1_Crusader_Phalanx3",
  "Bombardment": "X1_Crusader_Bombardment",
  "Fist of the Heavens": "X1_Crusader_FistOfTheHeavens",
  "Condemn": "X1_Crusader_Condemn",
  "Blessed Hammer": "X1_Crusader_BlessedHammer",
  "Shield Bash": "X1_Crusader_ShieldBash2",
  "Steed Charge": "X1_Crusader_SteedCharge",
  "Judgment": "X1_Crusader_Judgment",
  "Iron Skin": "X1_Crusader_IronSkin",
  "Akarat's Champion": "X1_Crusader_AkaratsChampion",
  "Shield Glare": "X1_Crusader_ShieldGlare",
  "Falling Sword": "X1_Crusader_FallingSword",
  "Punish": "X1_Crusader_Punish",
  "Slash": "X1_Crusader_Slash",
  "Justice": "X1_Crusader_Justice",
  "Provoke": "X1_Crusader_Provoke",
  "Laws of Valor": "X1_Crusader_LawsOfValor2",
  "Laws of Hope": "X1_Crusader_LawsOfHope2",
  "Laws of Justice": "X1_Crusader_LawsOfJustice2",
  "Consecration": "X1_Crusader_Consecration",
  "Smite": "X1_Crusader_Smite",
};
