<?php
require("getter.php");
GetDocs(array(
  "external/jquery.min.js",
  "external/jquery-ui.min.js",
  "external/spin.min.js",
  "external/jquery.cookie.min.js",
  "external/chosen.jquery.min.js",
  "external/Chart.min.js",
  "external/jquery.mousewheel.min.js",
  "external/mwheelIntent.min.js",
  "external/md5.js",
  "external/canvasjs.min.js",
  "external/jquery.ui.touch-punch.min.js",
  "external/gl-matrix.min.js",
  "scripts/errors.js",
  "scripts/main.js",
));
?>