_L.patch.add({
  simMapping: {
    buffs: {
      /*
      absolutezero: {
        category: "$Simulator/Skills$",
        category: "$Simulator/Passives$",
        category: "$Simulator/Item Sets$",
        category: "$Simulator/Items$",
        category: "$Simulator/Status$",
        name: "...",
      },
      */
    },
    opts: {
      buff: "$Simulator/Buff stacks$",
      buffmin: "$Simulator/Buff duration (min)$",
      buffmax: "$Simulator/Buff duration$",
      ticks: "$Simulator/Buff ticks$",
      resource: "$Simulator/Resource$",
      resourcepct: "$Simulator/Resource (percent)$",
      cooldown: "$Simulator/Cooldown$",
      charges: "$Simulator/Charges$",
      interval: "$Simulator/Time since cast$",
      health: "$Simulator/Target HP (percent)$",
      any: "$Simulator/Any condition$",
      all: "$Simulator/All conditions$",
      count: "$Simulator/Number of conditions$",
    },
    status: {
      chilled: "BuffTooltips/DebuffChilled_0",
      frozen: "BuffTooltips/CritDebuffCold_0",
      blinded: "BuffTooltips/DebuffBlind_0",
      stunned: "BuffTooltips/DebuffStunned_0",
      slowed: "BuffTooltips/DebuffSlowed_0",
      knockback: "$Simulator/Knockback$",
      charmed: "$Simulator/Charmed$",
      feared: "BuffTooltips/DebuffFeared_0",
      rooted: "BuffTooltips/DebuffRooted_0",
    },
    targetOptions: {
      distance: {
        name: "$Simulator/Distance$",
        tip: "$Simulator/Player distance from the center of the monster cluster.$"
      },
      radius: {
        name: "$Simulator/Spread$",
        tip: "$Simulator/Maximum monster distance from the cluster center.$",
      },
      size: {
        name: "$Simulator/Size$",
        tip: "$Simulator/Monster hitbox radius.$",
      },
      count: {
        name: "$Simulator/Count$",
        tip: "$Simulator/Number of monsters in the cluster.$",
      },
      globes: {
        name: "$Simulator/Globes/min$",
        tip: "$Simulator/Number of globes per minute generated by the party.$",
      },
    },
  },
});
